#!/bin/sh

URL_TO_LATEST=github.com/Antvirf/stui/releases/latest/download/stui_Linux_x86_64.tar.gz

echo "Downloading and extracting 'stui' to current directory..."
curl -sL $URL_TO_LATEST | tar xzv stui

echo "Moving 'stui' to /usr/local/bin - you will be prompted for sudo access"
# Move stui to /usr/local/bin, overwrite any existing version
sudo mv ./stui /usr/local/bin/stui --force
