repos:
  - repo: local
    hooks:
      - id: make-lint
        name: Run make lint
        entry: bash -c "cd $(git rev-parse --show-toplevel) && make lint"
        language: system
        stages: [pre-commit]
        verbose: true
