ClusterName=stui-test-cluster
SlurmctldHost=localhost
DebugFlags=AuditRPCs

ProctrackType=proctrack/linuxproc
ReturnToService=1
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPort=6818
SlurmUser=slurm
StateSaveLocation=/var/spool/slurmctld
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
SelectType=select/cons_tres
JobAcctGatherType=jobacct_gather/linux
SlurmctldDebug=verbose
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdDebug=verbose

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageUser=slurm 
AccountingStorageEnforce=all
AccountingStorageHost=localhost
AccountingStoreFlags=job_comment

# Configs to help allow multiple daemons on one node
# FOllowing advice from https://slurm.schedmd.com/programmer_guide.html#multiple_slurmd_support
SlurmdLogFile=/var/log/slurm/slurmd.%n.log
SlurmdPidFile=/var/run/slurmd.%n.pid
SlurmdSpoolDir=/var/spool/slurmd.%n


# 8888 fake nodes
NodeName=linux[0001-8888] NodeHostName=localhost Port=[20001-28888] NodeAddr=127.0.0.1 CPUs=2 RealMemory=16000

# Partition configurations
PartitionName=general    Nodes=ALL
PartitionName=chemistry Nodes=linux[0100-0199],linux0001
PartitionName=chem Nodes=linux0101,linux0002
PartitionName=physics Nodes=linux[0200-0299],linux0003
PartitionName=biology Nodes=linux[0300-0399],linux0004
PartitionName=finance Nodes=linux[0400-0499],linux0005
PartitionName=mathematics Nodes=linux[0500-0599],linux0006
PartitionName=unallocated Nodes=linux[0600-8888],linux0007


