/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdJobsRespTime struct for V0041OpenapiSlurmdbdJobsRespTime
type V0041OpenapiSlurmdbdJobsRespTime struct {
	// Elapsed time in seconds
	Elapsed *int32 `json:"elapsed,omitempty"`
	// Time when the job became eligible to run (UNIX timestamp)
	Eligible *int64 `json:"eligible,omitempty"`
	// End time (UNIX timestamp)
	End *int64 `json:"end,omitempty"`
	Planned *V0041OpenapiSlurmdbdJobsRespTimePlanned `json:"planned,omitempty"`
	// Time execution began (UNIX timestamp)
	Start *int64 `json:"start,omitempty"`
	// Time when the job was submitted (UNIX timestamp)
	Submission *int64 `json:"submission,omitempty"`
	// Total time in suspended state in seconds
	Suspended *int32 `json:"suspended,omitempty"`
	System *V0041OpenapiSlurmdbdJobsRespTimeSystem `json:"system,omitempty"`
	Limit *SlurmV0041JobSubmitTimeLimit `json:"limit,omitempty"`
	Total *V0041OpenapiSlurmdbdJobsRespTimeTotal `json:"total,omitempty"`
	User *V0041OpenapiSlurmdbdJobsRespTimeUser `json:"user,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespTime instantiates a new V0041OpenapiSlurmdbdJobsRespTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespTime() *V0041OpenapiSlurmdbdJobsRespTime {
	this := V0041OpenapiSlurmdbdJobsRespTime{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespTimeWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespTimeWithDefaults() *V0041OpenapiSlurmdbdJobsRespTime {
	this := V0041OpenapiSlurmdbdJobsRespTime{}
	return &this
}

// GetElapsed returns the Elapsed field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetElapsed() int32 {
	if o == nil || o.Elapsed == nil {
		var ret int32
		return ret
	}
	return *o.Elapsed
}

// GetElapsedOk returns a tuple with the Elapsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetElapsedOk() (*int32, bool) {
	if o == nil || o.Elapsed == nil {
		return nil, false
	}
	return o.Elapsed, true
}

// HasElapsed returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasElapsed() bool {
	if o != nil && o.Elapsed != nil {
		return true
	}

	return false
}

// SetElapsed gets a reference to the given int32 and assigns it to the Elapsed field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetElapsed(v int32) {
	o.Elapsed = &v
}

// GetEligible returns the Eligible field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetEligible() int64 {
	if o == nil || o.Eligible == nil {
		var ret int64
		return ret
	}
	return *o.Eligible
}

// GetEligibleOk returns a tuple with the Eligible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetEligibleOk() (*int64, bool) {
	if o == nil || o.Eligible == nil {
		return nil, false
	}
	return o.Eligible, true
}

// HasEligible returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasEligible() bool {
	if o != nil && o.Eligible != nil {
		return true
	}

	return false
}

// SetEligible gets a reference to the given int64 and assigns it to the Eligible field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetEligible(v int64) {
	o.Eligible = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetEnd() int64 {
	if o == nil || o.End == nil {
		var ret int64
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetEndOk() (*int64, bool) {
	if o == nil || o.End == nil {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasEnd() bool {
	if o != nil && o.End != nil {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int64 and assigns it to the End field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetEnd(v int64) {
	o.End = &v
}

// GetPlanned returns the Planned field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetPlanned() V0041OpenapiSlurmdbdJobsRespTimePlanned {
	if o == nil || o.Planned == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTimePlanned
		return ret
	}
	return *o.Planned
}

// GetPlannedOk returns a tuple with the Planned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetPlannedOk() (*V0041OpenapiSlurmdbdJobsRespTimePlanned, bool) {
	if o == nil || o.Planned == nil {
		return nil, false
	}
	return o.Planned, true
}

// HasPlanned returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasPlanned() bool {
	if o != nil && o.Planned != nil {
		return true
	}

	return false
}

// SetPlanned gets a reference to the given V0041OpenapiSlurmdbdJobsRespTimePlanned and assigns it to the Planned field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetPlanned(v V0041OpenapiSlurmdbdJobsRespTimePlanned) {
	o.Planned = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetStart() int64 {
	if o == nil || o.Start == nil {
		var ret int64
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetStartOk() (*int64, bool) {
	if o == nil || o.Start == nil {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasStart() bool {
	if o != nil && o.Start != nil {
		return true
	}

	return false
}

// SetStart gets a reference to the given int64 and assigns it to the Start field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetStart(v int64) {
	o.Start = &v
}

// GetSubmission returns the Submission field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSubmission() int64 {
	if o == nil || o.Submission == nil {
		var ret int64
		return ret
	}
	return *o.Submission
}

// GetSubmissionOk returns a tuple with the Submission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSubmissionOk() (*int64, bool) {
	if o == nil || o.Submission == nil {
		return nil, false
	}
	return o.Submission, true
}

// HasSubmission returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasSubmission() bool {
	if o != nil && o.Submission != nil {
		return true
	}

	return false
}

// SetSubmission gets a reference to the given int64 and assigns it to the Submission field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetSubmission(v int64) {
	o.Submission = &v
}

// GetSuspended returns the Suspended field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSuspended() int32 {
	if o == nil || o.Suspended == nil {
		var ret int32
		return ret
	}
	return *o.Suspended
}

// GetSuspendedOk returns a tuple with the Suspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSuspendedOk() (*int32, bool) {
	if o == nil || o.Suspended == nil {
		return nil, false
	}
	return o.Suspended, true
}

// HasSuspended returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasSuspended() bool {
	if o != nil && o.Suspended != nil {
		return true
	}

	return false
}

// SetSuspended gets a reference to the given int32 and assigns it to the Suspended field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetSuspended(v int32) {
	o.Suspended = &v
}

// GetSystem returns the System field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSystem() V0041OpenapiSlurmdbdJobsRespTimeSystem {
	if o == nil || o.System == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTimeSystem
		return ret
	}
	return *o.System
}

// GetSystemOk returns a tuple with the System field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetSystemOk() (*V0041OpenapiSlurmdbdJobsRespTimeSystem, bool) {
	if o == nil || o.System == nil {
		return nil, false
	}
	return o.System, true
}

// HasSystem returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasSystem() bool {
	if o != nil && o.System != nil {
		return true
	}

	return false
}

// SetSystem gets a reference to the given V0041OpenapiSlurmdbdJobsRespTimeSystem and assigns it to the System field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetSystem(v V0041OpenapiSlurmdbdJobsRespTimeSystem) {
	o.System = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetLimit() SlurmV0041JobSubmitTimeLimit {
	if o == nil || o.Limit == nil {
		var ret SlurmV0041JobSubmitTimeLimit
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetLimitOk() (*SlurmV0041JobSubmitTimeLimit, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given SlurmV0041JobSubmitTimeLimit and assigns it to the Limit field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetLimit(v SlurmV0041JobSubmitTimeLimit) {
	o.Limit = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetTotal() V0041OpenapiSlurmdbdJobsRespTimeTotal {
	if o == nil || o.Total == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTimeTotal
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetTotalOk() (*V0041OpenapiSlurmdbdJobsRespTimeTotal, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given V0041OpenapiSlurmdbdJobsRespTimeTotal and assigns it to the Total field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetTotal(v V0041OpenapiSlurmdbdJobsRespTimeTotal) {
	o.Total = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetUser() V0041OpenapiSlurmdbdJobsRespTimeUser {
	if o == nil || o.User == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTimeUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) GetUserOk() (*V0041OpenapiSlurmdbdJobsRespTimeUser, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespTime) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given V0041OpenapiSlurmdbdJobsRespTimeUser and assigns it to the User field.
func (o *V0041OpenapiSlurmdbdJobsRespTime) SetUser(v V0041OpenapiSlurmdbdJobsRespTimeUser) {
	o.User = &v
}

func (o V0041OpenapiSlurmdbdJobsRespTime) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Elapsed != nil {
		toSerialize["elapsed"] = o.Elapsed
	}
	if o.Eligible != nil {
		toSerialize["eligible"] = o.Eligible
	}
	if o.End != nil {
		toSerialize["end"] = o.End
	}
	if o.Planned != nil {
		toSerialize["planned"] = o.Planned
	}
	if o.Start != nil {
		toSerialize["start"] = o.Start
	}
	if o.Submission != nil {
		toSerialize["submission"] = o.Submission
	}
	if o.Suspended != nil {
		toSerialize["suspended"] = o.Suspended
	}
	if o.System != nil {
		toSerialize["system"] = o.System
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdJobsRespTime struct {
	value *V0041OpenapiSlurmdbdJobsRespTime
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespTime) Get() *V0041OpenapiSlurmdbdJobsRespTime {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespTime) Set(val *V0041OpenapiSlurmdbdJobsRespTime) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespTime) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespTime(val *V0041OpenapiSlurmdbdJobsRespTime) *NullableV0041OpenapiSlurmdbdJobsRespTime {
	return &NullableV0041OpenapiSlurmdbdJobsRespTime{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


