/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042UserShort struct for V0042UserShort
type V0042UserShort struct {
	Adminlevel *[]string `json:"adminlevel,omitempty"`
	// Default account
	Defaultaccount *string `json:"defaultaccount,omitempty"`
	// Default WCKey
	Defaultwckey *string `json:"defaultwckey,omitempty"`
}

// NewV0042UserShort instantiates a new V0042UserShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042UserShort() *V0042UserShort {
	this := V0042UserShort{}
	return &this
}

// NewV0042UserShortWithDefaults instantiates a new V0042UserShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042UserShortWithDefaults() *V0042UserShort {
	this := V0042UserShort{}
	return &this
}

// GetAdminlevel returns the Adminlevel field value if set, zero value otherwise.
func (o *V0042UserShort) GetAdminlevel() []string {
	if o == nil || o.Adminlevel == nil {
		var ret []string
		return ret
	}
	return *o.Adminlevel
}

// GetAdminlevelOk returns a tuple with the Adminlevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042UserShort) GetAdminlevelOk() (*[]string, bool) {
	if o == nil || o.Adminlevel == nil {
		return nil, false
	}
	return o.Adminlevel, true
}

// HasAdminlevel returns a boolean if a field has been set.
func (o *V0042UserShort) HasAdminlevel() bool {
	if o != nil && o.Adminlevel != nil {
		return true
	}

	return false
}

// SetAdminlevel gets a reference to the given []string and assigns it to the Adminlevel field.
func (o *V0042UserShort) SetAdminlevel(v []string) {
	o.Adminlevel = &v
}

// GetDefaultaccount returns the Defaultaccount field value if set, zero value otherwise.
func (o *V0042UserShort) GetDefaultaccount() string {
	if o == nil || o.Defaultaccount == nil {
		var ret string
		return ret
	}
	return *o.Defaultaccount
}

// GetDefaultaccountOk returns a tuple with the Defaultaccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042UserShort) GetDefaultaccountOk() (*string, bool) {
	if o == nil || o.Defaultaccount == nil {
		return nil, false
	}
	return o.Defaultaccount, true
}

// HasDefaultaccount returns a boolean if a field has been set.
func (o *V0042UserShort) HasDefaultaccount() bool {
	if o != nil && o.Defaultaccount != nil {
		return true
	}

	return false
}

// SetDefaultaccount gets a reference to the given string and assigns it to the Defaultaccount field.
func (o *V0042UserShort) SetDefaultaccount(v string) {
	o.Defaultaccount = &v
}

// GetDefaultwckey returns the Defaultwckey field value if set, zero value otherwise.
func (o *V0042UserShort) GetDefaultwckey() string {
	if o == nil || o.Defaultwckey == nil {
		var ret string
		return ret
	}
	return *o.Defaultwckey
}

// GetDefaultwckeyOk returns a tuple with the Defaultwckey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042UserShort) GetDefaultwckeyOk() (*string, bool) {
	if o == nil || o.Defaultwckey == nil {
		return nil, false
	}
	return o.Defaultwckey, true
}

// HasDefaultwckey returns a boolean if a field has been set.
func (o *V0042UserShort) HasDefaultwckey() bool {
	if o != nil && o.Defaultwckey != nil {
		return true
	}

	return false
}

// SetDefaultwckey gets a reference to the given string and assigns it to the Defaultwckey field.
func (o *V0042UserShort) SetDefaultwckey(v string) {
	o.Defaultwckey = &v
}

func (o V0042UserShort) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Adminlevel != nil {
		toSerialize["adminlevel"] = o.Adminlevel
	}
	if o.Defaultaccount != nil {
		toSerialize["defaultaccount"] = o.Defaultaccount
	}
	if o.Defaultwckey != nil {
		toSerialize["defaultwckey"] = o.Defaultwckey
	}
	return json.Marshal(toSerialize)
}

type NullableV0042UserShort struct {
	value *V0042UserShort
	isSet bool
}

func (v NullableV0042UserShort) Get() *V0042UserShort {
	return v.value
}

func (v *NullableV0042UserShort) Set(val *V0042UserShort) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042UserShort) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042UserShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042UserShort(val *V0042UserShort) *NullableV0042UserShort {
	return &NullableV0042UserShort{value: val, isSet: true}
}

func (v NullableV0042UserShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042UserShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


