/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043InstanceTime struct for V0043InstanceTime
type V0043InstanceTime struct {
	// When the instance will end (UNIX timestamp) (UNIX timestamp or time string recognized by Slurm (e.g., '[MM/DD[/YY]-]HH:MM[:SS]'))
	TimeEnd *int64 `json:"time_end,omitempty"`
	// When the instance will start (UNIX timestamp) (UNIX timestamp or time string recognized by Slurm (e.g., '[MM/DD[/YY]-]HH:MM[:SS]'))
	TimeStart *int64 `json:"time_start,omitempty"`
}

// NewV0043InstanceTime instantiates a new V0043InstanceTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043InstanceTime() *V0043InstanceTime {
	this := V0043InstanceTime{}
	return &this
}

// NewV0043InstanceTimeWithDefaults instantiates a new V0043InstanceTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043InstanceTimeWithDefaults() *V0043InstanceTime {
	this := V0043InstanceTime{}
	return &this
}

// GetTimeEnd returns the TimeEnd field value if set, zero value otherwise.
func (o *V0043InstanceTime) GetTimeEnd() int64 {
	if o == nil || o.TimeEnd == nil {
		var ret int64
		return ret
	}
	return *o.TimeEnd
}

// GetTimeEndOk returns a tuple with the TimeEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043InstanceTime) GetTimeEndOk() (*int64, bool) {
	if o == nil || o.TimeEnd == nil {
		return nil, false
	}
	return o.TimeEnd, true
}

// HasTimeEnd returns a boolean if a field has been set.
func (o *V0043InstanceTime) HasTimeEnd() bool {
	if o != nil && o.TimeEnd != nil {
		return true
	}

	return false
}

// SetTimeEnd gets a reference to the given int64 and assigns it to the TimeEnd field.
func (o *V0043InstanceTime) SetTimeEnd(v int64) {
	o.TimeEnd = &v
}

// GetTimeStart returns the TimeStart field value if set, zero value otherwise.
func (o *V0043InstanceTime) GetTimeStart() int64 {
	if o == nil || o.TimeStart == nil {
		var ret int64
		return ret
	}
	return *o.TimeStart
}

// GetTimeStartOk returns a tuple with the TimeStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043InstanceTime) GetTimeStartOk() (*int64, bool) {
	if o == nil || o.TimeStart == nil {
		return nil, false
	}
	return o.TimeStart, true
}

// HasTimeStart returns a boolean if a field has been set.
func (o *V0043InstanceTime) HasTimeStart() bool {
	if o != nil && o.TimeStart != nil {
		return true
	}

	return false
}

// SetTimeStart gets a reference to the given int64 and assigns it to the TimeStart field.
func (o *V0043InstanceTime) SetTimeStart(v int64) {
	o.TimeStart = &v
}

func (o V0043InstanceTime) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TimeEnd != nil {
		toSerialize["time_end"] = o.TimeEnd
	}
	if o.TimeStart != nil {
		toSerialize["time_start"] = o.TimeStart
	}
	return json.Marshal(toSerialize)
}

type NullableV0043InstanceTime struct {
	value *V0043InstanceTime
	isSet bool
}

func (v NullableV0043InstanceTime) Get() *V0043InstanceTime {
	return v.value
}

func (v *NullableV0043InstanceTime) Set(val *V0043InstanceTime) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043InstanceTime) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043InstanceTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043InstanceTime(val *V0043InstanceTime) *NullableV0043InstanceTime {
	return &NullableV0043InstanceTime{value: val, isSet: true}
}

func (v NullableV0043InstanceTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043InstanceTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


