/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0040WckeyTagStruct struct for V0040WckeyTagStruct
type V0040WckeyTagStruct struct {
	// WCKey name
	Wckey string `json:"wckey"`
	Flags []string `json:"flags"`
}

// NewV0040WckeyTagStruct instantiates a new V0040WckeyTagStruct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0040WckeyTagStruct(wckey string, flags []string) *V0040WckeyTagStruct {
	this := V0040WckeyTagStruct{}
	this.Wckey = wckey
	this.Flags = flags
	return &this
}

// NewV0040WckeyTagStructWithDefaults instantiates a new V0040WckeyTagStruct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0040WckeyTagStructWithDefaults() *V0040WckeyTagStruct {
	this := V0040WckeyTagStruct{}
	return &this
}

// GetWckey returns the Wckey field value
func (o *V0040WckeyTagStruct) GetWckey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Wckey
}

// GetWckeyOk returns a tuple with the Wckey field value
// and a boolean to check if the value has been set.
func (o *V0040WckeyTagStruct) GetWckeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Wckey, true
}

// SetWckey sets field value
func (o *V0040WckeyTagStruct) SetWckey(v string) {
	o.Wckey = v
}

// GetFlags returns the Flags field value
func (o *V0040WckeyTagStruct) GetFlags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value
// and a boolean to check if the value has been set.
func (o *V0040WckeyTagStruct) GetFlagsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Flags, true
}

// SetFlags sets field value
func (o *V0040WckeyTagStruct) SetFlags(v []string) {
	o.Flags = v
}

func (o V0040WckeyTagStruct) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["wckey"] = o.Wckey
	}
	if true {
		toSerialize["flags"] = o.Flags
	}
	return json.Marshal(toSerialize)
}

type NullableV0040WckeyTagStruct struct {
	value *V0040WckeyTagStruct
	isSet bool
}

func (v NullableV0040WckeyTagStruct) Get() *V0040WckeyTagStruct {
	return v.value
}

func (v *NullableV0040WckeyTagStruct) Set(val *V0040WckeyTagStruct) {
	v.value = val
	v.isSet = true
}

func (v NullableV0040WckeyTagStruct) IsSet() bool {
	return v.isSet
}

func (v *NullableV0040WckeyTagStruct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0040WckeyTagStruct(val *V0040WckeyTagStruct) *NullableV0040WckeyTagStruct {
	return &NullableV0040WckeyTagStruct{value: val, isSet: true}
}

func (v NullableV0040WckeyTagStruct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0040WckeyTagStruct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


