/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042ReservationCoreSpec struct for V0042ReservationCoreSpec
type V0042ReservationCoreSpec struct {
	// Name of reserved node
	Node *string `json:"node,omitempty"`
	// IDs of reserved cores
	Core *string `json:"core,omitempty"`
}

// NewV0042ReservationCoreSpec instantiates a new V0042ReservationCoreSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042ReservationCoreSpec() *V0042ReservationCoreSpec {
	this := V0042ReservationCoreSpec{}
	return &this
}

// NewV0042ReservationCoreSpecWithDefaults instantiates a new V0042ReservationCoreSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042ReservationCoreSpecWithDefaults() *V0042ReservationCoreSpec {
	this := V0042ReservationCoreSpec{}
	return &this
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *V0042ReservationCoreSpec) GetNode() string {
	if o == nil || o.Node == nil {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042ReservationCoreSpec) GetNodeOk() (*string, bool) {
	if o == nil || o.Node == nil {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *V0042ReservationCoreSpec) HasNode() bool {
	if o != nil && o.Node != nil {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *V0042ReservationCoreSpec) SetNode(v string) {
	o.Node = &v
}

// GetCore returns the Core field value if set, zero value otherwise.
func (o *V0042ReservationCoreSpec) GetCore() string {
	if o == nil || o.Core == nil {
		var ret string
		return ret
	}
	return *o.Core
}

// GetCoreOk returns a tuple with the Core field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042ReservationCoreSpec) GetCoreOk() (*string, bool) {
	if o == nil || o.Core == nil {
		return nil, false
	}
	return o.Core, true
}

// HasCore returns a boolean if a field has been set.
func (o *V0042ReservationCoreSpec) HasCore() bool {
	if o != nil && o.Core != nil {
		return true
	}

	return false
}

// SetCore gets a reference to the given string and assigns it to the Core field.
func (o *V0042ReservationCoreSpec) SetCore(v string) {
	o.Core = &v
}

func (o V0042ReservationCoreSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Node != nil {
		toSerialize["node"] = o.Node
	}
	if o.Core != nil {
		toSerialize["core"] = o.Core
	}
	return json.Marshal(toSerialize)
}

type NullableV0042ReservationCoreSpec struct {
	value *V0042ReservationCoreSpec
	isSet bool
}

func (v NullableV0042ReservationCoreSpec) Get() *V0042ReservationCoreSpec {
	return v.value
}

func (v *NullableV0042ReservationCoreSpec) Set(val *V0042ReservationCoreSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042ReservationCoreSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042ReservationCoreSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042ReservationCoreSpec(val *V0042ReservationCoreSpec) *NullableV0042ReservationCoreSpec {
	return &NullableV0042ReservationCoreSpec{value: val, isSet: true}
}

func (v NullableV0042ReservationCoreSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042ReservationCoreSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


