/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043OpenapiDiagResp struct for V0043OpenapiDiagResp
type V0043OpenapiDiagResp struct {
	Statistics V0043StatsMsg `json:"statistics"`
	Meta *V0043OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0043OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0043OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0043OpenapiDiagResp instantiates a new V0043OpenapiDiagResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043OpenapiDiagResp(statistics V0043StatsMsg) *V0043OpenapiDiagResp {
	this := V0043OpenapiDiagResp{}
	this.Statistics = statistics
	return &this
}

// NewV0043OpenapiDiagRespWithDefaults instantiates a new V0043OpenapiDiagResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043OpenapiDiagRespWithDefaults() *V0043OpenapiDiagResp {
	this := V0043OpenapiDiagResp{}
	return &this
}

// GetStatistics returns the Statistics field value
func (o *V0043OpenapiDiagResp) GetStatistics() V0043StatsMsg {
	if o == nil {
		var ret V0043StatsMsg
		return ret
	}

	return o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiDiagResp) GetStatisticsOk() (*V0043StatsMsg, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Statistics, true
}

// SetStatistics sets field value
func (o *V0043OpenapiDiagResp) SetStatistics(v V0043StatsMsg) {
	o.Statistics = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0043OpenapiDiagResp) GetMeta() V0043OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0043OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiDiagResp) GetMetaOk() (*V0043OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0043OpenapiDiagResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0043OpenapiMeta and assigns it to the Meta field.
func (o *V0043OpenapiDiagResp) SetMeta(v V0043OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0043OpenapiDiagResp) GetErrors() []V0043OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0043OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiDiagResp) GetErrorsOk() (*[]V0043OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0043OpenapiDiagResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0043OpenapiError and assigns it to the Errors field.
func (o *V0043OpenapiDiagResp) SetErrors(v []V0043OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0043OpenapiDiagResp) GetWarnings() []V0043OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0043OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiDiagResp) GetWarningsOk() (*[]V0043OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0043OpenapiDiagResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0043OpenapiWarning and assigns it to the Warnings field.
func (o *V0043OpenapiDiagResp) SetWarnings(v []V0043OpenapiWarning) {
	o.Warnings = &v
}

func (o V0043OpenapiDiagResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["statistics"] = o.Statistics
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0043OpenapiDiagResp struct {
	value *V0043OpenapiDiagResp
	isSet bool
}

func (v NullableV0043OpenapiDiagResp) Get() *V0043OpenapiDiagResp {
	return v.value
}

func (v *NullableV0043OpenapiDiagResp) Set(val *V0043OpenapiDiagResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043OpenapiDiagResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043OpenapiDiagResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043OpenapiDiagResp(val *V0043OpenapiDiagResp) *NullableV0043OpenapiDiagResp {
	return &NullableV0043OpenapiDiagResp{value: val, isSet: true}
}

func (v NullableV0043OpenapiDiagResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043OpenapiDiagResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


