/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdConfigRespQos struct for V0041OpenapiSlurmdbdConfigRespQos
type V0041OpenapiSlurmdbdConfigRespQos struct {
	// Arbitrary description
	Description *string `json:"description,omitempty"`
	// Flags, to avoid modifying current values specify NOT_SET
	Flags *[]string `json:"flags,omitempty"`
	// Unique ID
	Id *int32 `json:"id,omitempty"`
	Limits *V0041OpenapiSlurmdbdConfigRespLimits `json:"limits,omitempty"`
	// Name
	Name *string `json:"name,omitempty"`
	Preempt *V0041OpenapiSlurmdbdConfigRespPreempt `json:"preempt,omitempty"`
	Priority *V0041OpenapiSlurmdbdConfigRespPriority `json:"priority,omitempty"`
	UsageFactor *V0041OpenapiSlurmdbdConfigRespUsageFactor `json:"usage_factor,omitempty"`
	UsageThreshold *V0041OpenapiSlurmdbdConfigRespUsageThreshold `json:"usage_threshold,omitempty"`
}

// NewV0041OpenapiSlurmdbdConfigRespQos instantiates a new V0041OpenapiSlurmdbdConfigRespQos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdConfigRespQos() *V0041OpenapiSlurmdbdConfigRespQos {
	this := V0041OpenapiSlurmdbdConfigRespQos{}
	return &this
}

// NewV0041OpenapiSlurmdbdConfigRespQosWithDefaults instantiates a new V0041OpenapiSlurmdbdConfigRespQos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdConfigRespQosWithDefaults() *V0041OpenapiSlurmdbdConfigRespQos {
	this := V0041OpenapiSlurmdbdConfigRespQos{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetDescription(v string) {
	o.Description = &v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetFlags() []string {
	if o == nil || o.Flags == nil {
		var ret []string
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetFlagsOk() (*[]string, bool) {
	if o == nil || o.Flags == nil {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasFlags() bool {
	if o != nil && o.Flags != nil {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetFlags(v []string) {
	o.Flags = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetId(v int32) {
	o.Id = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetLimits() V0041OpenapiSlurmdbdConfigRespLimits {
	if o == nil || o.Limits == nil {
		var ret V0041OpenapiSlurmdbdConfigRespLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetLimitsOk() (*V0041OpenapiSlurmdbdConfigRespLimits, bool) {
	if o == nil || o.Limits == nil {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasLimits() bool {
	if o != nil && o.Limits != nil {
		return true
	}

	return false
}

// SetLimits gets a reference to the given V0041OpenapiSlurmdbdConfigRespLimits and assigns it to the Limits field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetLimits(v V0041OpenapiSlurmdbdConfigRespLimits) {
	o.Limits = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetName(v string) {
	o.Name = &v
}

// GetPreempt returns the Preempt field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetPreempt() V0041OpenapiSlurmdbdConfigRespPreempt {
	if o == nil || o.Preempt == nil {
		var ret V0041OpenapiSlurmdbdConfigRespPreempt
		return ret
	}
	return *o.Preempt
}

// GetPreemptOk returns a tuple with the Preempt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetPreemptOk() (*V0041OpenapiSlurmdbdConfigRespPreempt, bool) {
	if o == nil || o.Preempt == nil {
		return nil, false
	}
	return o.Preempt, true
}

// HasPreempt returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasPreempt() bool {
	if o != nil && o.Preempt != nil {
		return true
	}

	return false
}

// SetPreempt gets a reference to the given V0041OpenapiSlurmdbdConfigRespPreempt and assigns it to the Preempt field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetPreempt(v V0041OpenapiSlurmdbdConfigRespPreempt) {
	o.Preempt = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetPriority() V0041OpenapiSlurmdbdConfigRespPriority {
	if o == nil || o.Priority == nil {
		var ret V0041OpenapiSlurmdbdConfigRespPriority
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetPriorityOk() (*V0041OpenapiSlurmdbdConfigRespPriority, bool) {
	if o == nil || o.Priority == nil {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasPriority() bool {
	if o != nil && o.Priority != nil {
		return true
	}

	return false
}

// SetPriority gets a reference to the given V0041OpenapiSlurmdbdConfigRespPriority and assigns it to the Priority field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetPriority(v V0041OpenapiSlurmdbdConfigRespPriority) {
	o.Priority = &v
}

// GetUsageFactor returns the UsageFactor field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetUsageFactor() V0041OpenapiSlurmdbdConfigRespUsageFactor {
	if o == nil || o.UsageFactor == nil {
		var ret V0041OpenapiSlurmdbdConfigRespUsageFactor
		return ret
	}
	return *o.UsageFactor
}

// GetUsageFactorOk returns a tuple with the UsageFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetUsageFactorOk() (*V0041OpenapiSlurmdbdConfigRespUsageFactor, bool) {
	if o == nil || o.UsageFactor == nil {
		return nil, false
	}
	return o.UsageFactor, true
}

// HasUsageFactor returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasUsageFactor() bool {
	if o != nil && o.UsageFactor != nil {
		return true
	}

	return false
}

// SetUsageFactor gets a reference to the given V0041OpenapiSlurmdbdConfigRespUsageFactor and assigns it to the UsageFactor field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetUsageFactor(v V0041OpenapiSlurmdbdConfigRespUsageFactor) {
	o.UsageFactor = &v
}

// GetUsageThreshold returns the UsageThreshold field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetUsageThreshold() V0041OpenapiSlurmdbdConfigRespUsageThreshold {
	if o == nil || o.UsageThreshold == nil {
		var ret V0041OpenapiSlurmdbdConfigRespUsageThreshold
		return ret
	}
	return *o.UsageThreshold
}

// GetUsageThresholdOk returns a tuple with the UsageThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) GetUsageThresholdOk() (*V0041OpenapiSlurmdbdConfigRespUsageThreshold, bool) {
	if o == nil || o.UsageThreshold == nil {
		return nil, false
	}
	return o.UsageThreshold, true
}

// HasUsageThreshold returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespQos) HasUsageThreshold() bool {
	if o != nil && o.UsageThreshold != nil {
		return true
	}

	return false
}

// SetUsageThreshold gets a reference to the given V0041OpenapiSlurmdbdConfigRespUsageThreshold and assigns it to the UsageThreshold field.
func (o *V0041OpenapiSlurmdbdConfigRespQos) SetUsageThreshold(v V0041OpenapiSlurmdbdConfigRespUsageThreshold) {
	o.UsageThreshold = &v
}

func (o V0041OpenapiSlurmdbdConfigRespQos) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Flags != nil {
		toSerialize["flags"] = o.Flags
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Limits != nil {
		toSerialize["limits"] = o.Limits
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Preempt != nil {
		toSerialize["preempt"] = o.Preempt
	}
	if o.Priority != nil {
		toSerialize["priority"] = o.Priority
	}
	if o.UsageFactor != nil {
		toSerialize["usage_factor"] = o.UsageFactor
	}
	if o.UsageThreshold != nil {
		toSerialize["usage_threshold"] = o.UsageThreshold
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdConfigRespQos struct {
	value *V0041OpenapiSlurmdbdConfigRespQos
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdConfigRespQos) Get() *V0041OpenapiSlurmdbdConfigRespQos {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespQos) Set(val *V0041OpenapiSlurmdbdConfigRespQos) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdConfigRespQos) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespQos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdConfigRespQos(val *V0041OpenapiSlurmdbdConfigRespQos) *NullableV0041OpenapiSlurmdbdConfigRespQos {
	return &NullableV0041OpenapiSlurmdbdConfigRespQos{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdConfigRespQos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespQos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


