/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042JobState struct for V0042JobState
type V0042JobState struct {
	Current *[]string `json:"current,omitempty"`
	// Reason for previous Pending or Failed state
	Reason *string `json:"reason,omitempty"`
}

// NewV0042JobState instantiates a new V0042JobState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042JobState() *V0042JobState {
	this := V0042JobState{}
	return &this
}

// NewV0042JobStateWithDefaults instantiates a new V0042JobState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042JobStateWithDefaults() *V0042JobState {
	this := V0042JobState{}
	return &this
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *V0042JobState) GetCurrent() []string {
	if o == nil || o.Current == nil {
		var ret []string
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042JobState) GetCurrentOk() (*[]string, bool) {
	if o == nil || o.Current == nil {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *V0042JobState) HasCurrent() bool {
	if o != nil && o.Current != nil {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given []string and assigns it to the Current field.
func (o *V0042JobState) SetCurrent(v []string) {
	o.Current = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *V0042JobState) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042JobState) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *V0042JobState) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *V0042JobState) SetReason(v string) {
	o.Reason = &v
}

func (o V0042JobState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Current != nil {
		toSerialize["current"] = o.Current
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	return json.Marshal(toSerialize)
}

type NullableV0042JobState struct {
	value *V0042JobState
	isSet bool
}

func (v NullableV0042JobState) Get() *V0042JobState {
	return v.value
}

func (v *NullableV0042JobState) Set(val *V0042JobState) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042JobState) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042JobState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042JobState(val *V0042JobState) *NullableV0042JobState {
	return &NullableV0042JobState{value: val, isSet: true}
}

func (v NullableV0042JobState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042JobState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


