/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdConfigRespMin struct for V0041OpenapiSlurmdbdConfigRespMin
type V0041OpenapiSlurmdbdConfigRespMin struct {
	PriorityThreshold *V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold `json:"priority_threshold,omitempty"`
}

// NewV0041OpenapiSlurmdbdConfigRespMin instantiates a new V0041OpenapiSlurmdbdConfigRespMin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdConfigRespMin() *V0041OpenapiSlurmdbdConfigRespMin {
	this := V0041OpenapiSlurmdbdConfigRespMin{}
	return &this
}

// NewV0041OpenapiSlurmdbdConfigRespMinWithDefaults instantiates a new V0041OpenapiSlurmdbdConfigRespMin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdConfigRespMinWithDefaults() *V0041OpenapiSlurmdbdConfigRespMin {
	this := V0041OpenapiSlurmdbdConfigRespMin{}
	return &this
}

// GetPriorityThreshold returns the PriorityThreshold field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespMin) GetPriorityThreshold() V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold {
	if o == nil || o.PriorityThreshold == nil {
		var ret V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold
		return ret
	}
	return *o.PriorityThreshold
}

// GetPriorityThresholdOk returns a tuple with the PriorityThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespMin) GetPriorityThresholdOk() (*V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold, bool) {
	if o == nil || o.PriorityThreshold == nil {
		return nil, false
	}
	return o.PriorityThreshold, true
}

// HasPriorityThreshold returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespMin) HasPriorityThreshold() bool {
	if o != nil && o.PriorityThreshold != nil {
		return true
	}

	return false
}

// SetPriorityThreshold gets a reference to the given V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold and assigns it to the PriorityThreshold field.
func (o *V0041OpenapiSlurmdbdConfigRespMin) SetPriorityThreshold(v V0041OpenapiSlurmdbdConfigRespLimitsMinPriorityThreshold) {
	o.PriorityThreshold = &v
}

func (o V0041OpenapiSlurmdbdConfigRespMin) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PriorityThreshold != nil {
		toSerialize["priority_threshold"] = o.PriorityThreshold
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdConfigRespMin struct {
	value *V0041OpenapiSlurmdbdConfigRespMin
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMin) Get() *V0041OpenapiSlurmdbdConfigRespMin {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMin) Set(val *V0041OpenapiSlurmdbdConfigRespMin) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMin) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdConfigRespMin(val *V0041OpenapiSlurmdbdConfigRespMin) *NullableV0041OpenapiSlurmdbdConfigRespMin {
	return &NullableV0041OpenapiSlurmdbdConfigRespMin{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


