/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043Step struct for V0043Step
type V0043Step struct {
	Time *V0043StepTime `json:"time,omitempty"`
	ExitCode *V0043ProcessExitCodeVerbose `json:"exit_code,omitempty"`
	Nodes *V0043StepNodes `json:"nodes,omitempty"`
	Tasks *V0043StepTasks `json:"tasks,omitempty"`
	// Deprecated; Process ID
	// Deprecated
	Pid *string `json:"pid,omitempty"`
	CPU *V0043StepCPU `json:"CPU,omitempty"`
	// User ID that requested termination of the step
	KillRequestUser *string `json:"kill_request_user,omitempty"`
	// Current state
	State *[]string `json:"state,omitempty"`
	Statistics *V0043StepStatistics `json:"statistics,omitempty"`
	Step *V0043StepStep `json:"step,omitempty"`
	Task *V0043StepTask `json:"task,omitempty"`
	Tres *V0043StepTres `json:"tres,omitempty"`
}

// NewV0043Step instantiates a new V0043Step object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043Step() *V0043Step {
	this := V0043Step{}
	return &this
}

// NewV0043StepWithDefaults instantiates a new V0043Step object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043StepWithDefaults() *V0043Step {
	this := V0043Step{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0043Step) GetTime() V0043StepTime {
	if o == nil || o.Time == nil {
		var ret V0043StepTime
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetTimeOk() (*V0043StepTime, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0043Step) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given V0043StepTime and assigns it to the Time field.
func (o *V0043Step) SetTime(v V0043StepTime) {
	o.Time = &v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *V0043Step) GetExitCode() V0043ProcessExitCodeVerbose {
	if o == nil || o.ExitCode == nil {
		var ret V0043ProcessExitCodeVerbose
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetExitCodeOk() (*V0043ProcessExitCodeVerbose, bool) {
	if o == nil || o.ExitCode == nil {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *V0043Step) HasExitCode() bool {
	if o != nil && o.ExitCode != nil {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given V0043ProcessExitCodeVerbose and assigns it to the ExitCode field.
func (o *V0043Step) SetExitCode(v V0043ProcessExitCodeVerbose) {
	o.ExitCode = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *V0043Step) GetNodes() V0043StepNodes {
	if o == nil || o.Nodes == nil {
		var ret V0043StepNodes
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetNodesOk() (*V0043StepNodes, bool) {
	if o == nil || o.Nodes == nil {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *V0043Step) HasNodes() bool {
	if o != nil && o.Nodes != nil {
		return true
	}

	return false
}

// SetNodes gets a reference to the given V0043StepNodes and assigns it to the Nodes field.
func (o *V0043Step) SetNodes(v V0043StepNodes) {
	o.Nodes = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *V0043Step) GetTasks() V0043StepTasks {
	if o == nil || o.Tasks == nil {
		var ret V0043StepTasks
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetTasksOk() (*V0043StepTasks, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *V0043Step) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given V0043StepTasks and assigns it to the Tasks field.
func (o *V0043Step) SetTasks(v V0043StepTasks) {
	o.Tasks = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
// Deprecated
func (o *V0043Step) GetPid() string {
	if o == nil || o.Pid == nil {
		var ret string
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0043Step) GetPidOk() (*string, bool) {
	if o == nil || o.Pid == nil {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *V0043Step) HasPid() bool {
	if o != nil && o.Pid != nil {
		return true
	}

	return false
}

// SetPid gets a reference to the given string and assigns it to the Pid field.
// Deprecated
func (o *V0043Step) SetPid(v string) {
	o.Pid = &v
}

// GetCPU returns the CPU field value if set, zero value otherwise.
func (o *V0043Step) GetCPU() V0043StepCPU {
	if o == nil || o.CPU == nil {
		var ret V0043StepCPU
		return ret
	}
	return *o.CPU
}

// GetCPUOk returns a tuple with the CPU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetCPUOk() (*V0043StepCPU, bool) {
	if o == nil || o.CPU == nil {
		return nil, false
	}
	return o.CPU, true
}

// HasCPU returns a boolean if a field has been set.
func (o *V0043Step) HasCPU() bool {
	if o != nil && o.CPU != nil {
		return true
	}

	return false
}

// SetCPU gets a reference to the given V0043StepCPU and assigns it to the CPU field.
func (o *V0043Step) SetCPU(v V0043StepCPU) {
	o.CPU = &v
}

// GetKillRequestUser returns the KillRequestUser field value if set, zero value otherwise.
func (o *V0043Step) GetKillRequestUser() string {
	if o == nil || o.KillRequestUser == nil {
		var ret string
		return ret
	}
	return *o.KillRequestUser
}

// GetKillRequestUserOk returns a tuple with the KillRequestUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetKillRequestUserOk() (*string, bool) {
	if o == nil || o.KillRequestUser == nil {
		return nil, false
	}
	return o.KillRequestUser, true
}

// HasKillRequestUser returns a boolean if a field has been set.
func (o *V0043Step) HasKillRequestUser() bool {
	if o != nil && o.KillRequestUser != nil {
		return true
	}

	return false
}

// SetKillRequestUser gets a reference to the given string and assigns it to the KillRequestUser field.
func (o *V0043Step) SetKillRequestUser(v string) {
	o.KillRequestUser = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V0043Step) GetState() []string {
	if o == nil || o.State == nil {
		var ret []string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetStateOk() (*[]string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V0043Step) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *V0043Step) SetState(v []string) {
	o.State = &v
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
func (o *V0043Step) GetStatistics() V0043StepStatistics {
	if o == nil || o.Statistics == nil {
		var ret V0043StepStatistics
		return ret
	}
	return *o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetStatisticsOk() (*V0043StepStatistics, bool) {
	if o == nil || o.Statistics == nil {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *V0043Step) HasStatistics() bool {
	if o != nil && o.Statistics != nil {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given V0043StepStatistics and assigns it to the Statistics field.
func (o *V0043Step) SetStatistics(v V0043StepStatistics) {
	o.Statistics = &v
}

// GetStep returns the Step field value if set, zero value otherwise.
func (o *V0043Step) GetStep() V0043StepStep {
	if o == nil || o.Step == nil {
		var ret V0043StepStep
		return ret
	}
	return *o.Step
}

// GetStepOk returns a tuple with the Step field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetStepOk() (*V0043StepStep, bool) {
	if o == nil || o.Step == nil {
		return nil, false
	}
	return o.Step, true
}

// HasStep returns a boolean if a field has been set.
func (o *V0043Step) HasStep() bool {
	if o != nil && o.Step != nil {
		return true
	}

	return false
}

// SetStep gets a reference to the given V0043StepStep and assigns it to the Step field.
func (o *V0043Step) SetStep(v V0043StepStep) {
	o.Step = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *V0043Step) GetTask() V0043StepTask {
	if o == nil || o.Task == nil {
		var ret V0043StepTask
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetTaskOk() (*V0043StepTask, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *V0043Step) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given V0043StepTask and assigns it to the Task field.
func (o *V0043Step) SetTask(v V0043StepTask) {
	o.Task = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0043Step) GetTres() V0043StepTres {
	if o == nil || o.Tres == nil {
		var ret V0043StepTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Step) GetTresOk() (*V0043StepTres, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0043Step) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given V0043StepTres and assigns it to the Tres field.
func (o *V0043Step) SetTres(v V0043StepTres) {
	o.Tres = &v
}

func (o V0043Step) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	if o.ExitCode != nil {
		toSerialize["exit_code"] = o.ExitCode
	}
	if o.Nodes != nil {
		toSerialize["nodes"] = o.Nodes
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.Pid != nil {
		toSerialize["pid"] = o.Pid
	}
	if o.CPU != nil {
		toSerialize["CPU"] = o.CPU
	}
	if o.KillRequestUser != nil {
		toSerialize["kill_request_user"] = o.KillRequestUser
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Statistics != nil {
		toSerialize["statistics"] = o.Statistics
	}
	if o.Step != nil {
		toSerialize["step"] = o.Step
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	return json.Marshal(toSerialize)
}

type NullableV0043Step struct {
	value *V0043Step
	isSet bool
}

func (v NullableV0043Step) Get() *V0043Step {
	return v.value
}

func (v *NullableV0043Step) Set(val *V0043Step) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043Step) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043Step) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043Step(val *V0043Step) *NullableV0043Step {
	return &NullableV0043Step{value: val, isSet: true}
}

func (v NullableV0043Step) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043Step) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


