/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043RollupStatsMonthlyDuration struct for V0043RollupStatsMonthlyDuration
type V0043RollupStatsMonthlyDuration struct {
	// Total time spent doing monthly daily rollup (seconds)
	Last *int64 `json:"last,omitempty"`
	// Longest monthly rollup time (seconds)
	Max *int64 `json:"max,omitempty"`
	// Total time spent doing monthly rollups (seconds)
	Time *int64 `json:"time,omitempty"`
}

// NewV0043RollupStatsMonthlyDuration instantiates a new V0043RollupStatsMonthlyDuration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043RollupStatsMonthlyDuration() *V0043RollupStatsMonthlyDuration {
	this := V0043RollupStatsMonthlyDuration{}
	return &this
}

// NewV0043RollupStatsMonthlyDurationWithDefaults instantiates a new V0043RollupStatsMonthlyDuration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043RollupStatsMonthlyDurationWithDefaults() *V0043RollupStatsMonthlyDuration {
	this := V0043RollupStatsMonthlyDuration{}
	return &this
}

// GetLast returns the Last field value if set, zero value otherwise.
func (o *V0043RollupStatsMonthlyDuration) GetLast() int64 {
	if o == nil || o.Last == nil {
		var ret int64
		return ret
	}
	return *o.Last
}

// GetLastOk returns a tuple with the Last field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043RollupStatsMonthlyDuration) GetLastOk() (*int64, bool) {
	if o == nil || o.Last == nil {
		return nil, false
	}
	return o.Last, true
}

// HasLast returns a boolean if a field has been set.
func (o *V0043RollupStatsMonthlyDuration) HasLast() bool {
	if o != nil && o.Last != nil {
		return true
	}

	return false
}

// SetLast gets a reference to the given int64 and assigns it to the Last field.
func (o *V0043RollupStatsMonthlyDuration) SetLast(v int64) {
	o.Last = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *V0043RollupStatsMonthlyDuration) GetMax() int64 {
	if o == nil || o.Max == nil {
		var ret int64
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043RollupStatsMonthlyDuration) GetMaxOk() (*int64, bool) {
	if o == nil || o.Max == nil {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *V0043RollupStatsMonthlyDuration) HasMax() bool {
	if o != nil && o.Max != nil {
		return true
	}

	return false
}

// SetMax gets a reference to the given int64 and assigns it to the Max field.
func (o *V0043RollupStatsMonthlyDuration) SetMax(v int64) {
	o.Max = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0043RollupStatsMonthlyDuration) GetTime() int64 {
	if o == nil || o.Time == nil {
		var ret int64
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043RollupStatsMonthlyDuration) GetTimeOk() (*int64, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0043RollupStatsMonthlyDuration) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given int64 and assigns it to the Time field.
func (o *V0043RollupStatsMonthlyDuration) SetTime(v int64) {
	o.Time = &v
}

func (o V0043RollupStatsMonthlyDuration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Last != nil {
		toSerialize["last"] = o.Last
	}
	if o.Max != nil {
		toSerialize["max"] = o.Max
	}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableV0043RollupStatsMonthlyDuration struct {
	value *V0043RollupStatsMonthlyDuration
	isSet bool
}

func (v NullableV0043RollupStatsMonthlyDuration) Get() *V0043RollupStatsMonthlyDuration {
	return v.value
}

func (v *NullableV0043RollupStatsMonthlyDuration) Set(val *V0043RollupStatsMonthlyDuration) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043RollupStatsMonthlyDuration) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043RollupStatsMonthlyDuration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043RollupStatsMonthlyDuration(val *V0043RollupStatsMonthlyDuration) *NullableV0043RollupStatsMonthlyDuration {
	return &NullableV0043RollupStatsMonthlyDuration{value: val, isSet: true}
}

func (v NullableV0043RollupStatsMonthlyDuration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043RollupStatsMonthlyDuration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


