/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSharesRespSharesTres struct for V0041OpenapiSharesRespSharesTres
type V0041OpenapiSharesRespSharesTres struct {
	// Currently running tres-secs = grp_used_tres_run_secs
	RunSeconds *[]V0041OpenapiSharesRespSharesTresRunSeconds `json:"run_seconds,omitempty"`
	// TRES-minute limit
	GroupMinutes *[]V0041OpenapiSharesRespSharesTresRunSeconds `json:"group_minutes,omitempty"`
	// Measure of each TRES usage
	Usage *[]V0041OpenapiSharesRespSharesTresUsage `json:"usage,omitempty"`
}

// NewV0041OpenapiSharesRespSharesTres instantiates a new V0041OpenapiSharesRespSharesTres object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSharesRespSharesTres() *V0041OpenapiSharesRespSharesTres {
	this := V0041OpenapiSharesRespSharesTres{}
	return &this
}

// NewV0041OpenapiSharesRespSharesTresWithDefaults instantiates a new V0041OpenapiSharesRespSharesTres object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSharesRespSharesTresWithDefaults() *V0041OpenapiSharesRespSharesTres {
	this := V0041OpenapiSharesRespSharesTres{}
	return &this
}

// GetRunSeconds returns the RunSeconds field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespSharesTres) GetRunSeconds() []V0041OpenapiSharesRespSharesTresRunSeconds {
	if o == nil || o.RunSeconds == nil {
		var ret []V0041OpenapiSharesRespSharesTresRunSeconds
		return ret
	}
	return *o.RunSeconds
}

// GetRunSecondsOk returns a tuple with the RunSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespSharesTres) GetRunSecondsOk() (*[]V0041OpenapiSharesRespSharesTresRunSeconds, bool) {
	if o == nil || o.RunSeconds == nil {
		return nil, false
	}
	return o.RunSeconds, true
}

// HasRunSeconds returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespSharesTres) HasRunSeconds() bool {
	if o != nil && o.RunSeconds != nil {
		return true
	}

	return false
}

// SetRunSeconds gets a reference to the given []V0041OpenapiSharesRespSharesTresRunSeconds and assigns it to the RunSeconds field.
func (o *V0041OpenapiSharesRespSharesTres) SetRunSeconds(v []V0041OpenapiSharesRespSharesTresRunSeconds) {
	o.RunSeconds = &v
}

// GetGroupMinutes returns the GroupMinutes field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespSharesTres) GetGroupMinutes() []V0041OpenapiSharesRespSharesTresRunSeconds {
	if o == nil || o.GroupMinutes == nil {
		var ret []V0041OpenapiSharesRespSharesTresRunSeconds
		return ret
	}
	return *o.GroupMinutes
}

// GetGroupMinutesOk returns a tuple with the GroupMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespSharesTres) GetGroupMinutesOk() (*[]V0041OpenapiSharesRespSharesTresRunSeconds, bool) {
	if o == nil || o.GroupMinutes == nil {
		return nil, false
	}
	return o.GroupMinutes, true
}

// HasGroupMinutes returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespSharesTres) HasGroupMinutes() bool {
	if o != nil && o.GroupMinutes != nil {
		return true
	}

	return false
}

// SetGroupMinutes gets a reference to the given []V0041OpenapiSharesRespSharesTresRunSeconds and assigns it to the GroupMinutes field.
func (o *V0041OpenapiSharesRespSharesTres) SetGroupMinutes(v []V0041OpenapiSharesRespSharesTresRunSeconds) {
	o.GroupMinutes = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespSharesTres) GetUsage() []V0041OpenapiSharesRespSharesTresUsage {
	if o == nil || o.Usage == nil {
		var ret []V0041OpenapiSharesRespSharesTresUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespSharesTres) GetUsageOk() (*[]V0041OpenapiSharesRespSharesTresUsage, bool) {
	if o == nil || o.Usage == nil {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespSharesTres) HasUsage() bool {
	if o != nil && o.Usage != nil {
		return true
	}

	return false
}

// SetUsage gets a reference to the given []V0041OpenapiSharesRespSharesTresUsage and assigns it to the Usage field.
func (o *V0041OpenapiSharesRespSharesTres) SetUsage(v []V0041OpenapiSharesRespSharesTresUsage) {
	o.Usage = &v
}

func (o V0041OpenapiSharesRespSharesTres) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RunSeconds != nil {
		toSerialize["run_seconds"] = o.RunSeconds
	}
	if o.GroupMinutes != nil {
		toSerialize["group_minutes"] = o.GroupMinutes
	}
	if o.Usage != nil {
		toSerialize["usage"] = o.Usage
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSharesRespSharesTres struct {
	value *V0041OpenapiSharesRespSharesTres
	isSet bool
}

func (v NullableV0041OpenapiSharesRespSharesTres) Get() *V0041OpenapiSharesRespSharesTres {
	return v.value
}

func (v *NullableV0041OpenapiSharesRespSharesTres) Set(val *V0041OpenapiSharesRespSharesTres) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSharesRespSharesTres) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSharesRespSharesTres) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSharesRespSharesTres(val *V0041OpenapiSharesRespSharesTres) *NullableV0041OpenapiSharesRespSharesTres {
	return &NullableV0041OpenapiSharesRespSharesTres{value: val, isSet: true}
}

func (v NullableV0041OpenapiSharesRespSharesTres) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSharesRespSharesTres) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


