/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043QosPreempt struct for V0043QosPreempt
type V0043QosPreempt struct {
	List *[]string `json:"list,omitempty"`
	// PreemptMode - Mechanism used to preempt jobs or enable gang scheduling
	Mode *[]string `json:"mode,omitempty"`
	ExemptTime *V0043Uint32NoValStruct `json:"exempt_time,omitempty"`
}

// NewV0043QosPreempt instantiates a new V0043QosPreempt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043QosPreempt() *V0043QosPreempt {
	this := V0043QosPreempt{}
	return &this
}

// NewV0043QosPreemptWithDefaults instantiates a new V0043QosPreempt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043QosPreemptWithDefaults() *V0043QosPreempt {
	this := V0043QosPreempt{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise.
func (o *V0043QosPreempt) GetList() []string {
	if o == nil || o.List == nil {
		var ret []string
		return ret
	}
	return *o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043QosPreempt) GetListOk() (*[]string, bool) {
	if o == nil || o.List == nil {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *V0043QosPreempt) HasList() bool {
	if o != nil && o.List != nil {
		return true
	}

	return false
}

// SetList gets a reference to the given []string and assigns it to the List field.
func (o *V0043QosPreempt) SetList(v []string) {
	o.List = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *V0043QosPreempt) GetMode() []string {
	if o == nil || o.Mode == nil {
		var ret []string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043QosPreempt) GetModeOk() (*[]string, bool) {
	if o == nil || o.Mode == nil {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *V0043QosPreempt) HasMode() bool {
	if o != nil && o.Mode != nil {
		return true
	}

	return false
}

// SetMode gets a reference to the given []string and assigns it to the Mode field.
func (o *V0043QosPreempt) SetMode(v []string) {
	o.Mode = &v
}

// GetExemptTime returns the ExemptTime field value if set, zero value otherwise.
func (o *V0043QosPreempt) GetExemptTime() V0043Uint32NoValStruct {
	if o == nil || o.ExemptTime == nil {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.ExemptTime
}

// GetExemptTimeOk returns a tuple with the ExemptTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043QosPreempt) GetExemptTimeOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || o.ExemptTime == nil {
		return nil, false
	}
	return o.ExemptTime, true
}

// HasExemptTime returns a boolean if a field has been set.
func (o *V0043QosPreempt) HasExemptTime() bool {
	if o != nil && o.ExemptTime != nil {
		return true
	}

	return false
}

// SetExemptTime gets a reference to the given V0043Uint32NoValStruct and assigns it to the ExemptTime field.
func (o *V0043QosPreempt) SetExemptTime(v V0043Uint32NoValStruct) {
	o.ExemptTime = &v
}

func (o V0043QosPreempt) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.List != nil {
		toSerialize["list"] = o.List
	}
	if o.Mode != nil {
		toSerialize["mode"] = o.Mode
	}
	if o.ExemptTime != nil {
		toSerialize["exempt_time"] = o.ExemptTime
	}
	return json.Marshal(toSerialize)
}

type NullableV0043QosPreempt struct {
	value *V0043QosPreempt
	isSet bool
}

func (v NullableV0043QosPreempt) Get() *V0043QosPreempt {
	return v.value
}

func (v *NullableV0043QosPreempt) Set(val *V0043QosPreempt) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043QosPreempt) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043QosPreempt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043QosPreempt(val *V0043QosPreempt) *NullableV0043QosPreempt {
	return &NullableV0043QosPreempt{value: val, isSet: true}
}

func (v NullableV0043QosPreempt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043QosPreempt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


