/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042QosLimitsMaxTresMinutesPer struct for V0042QosLimitsMaxTresMinutesPer
type V0042QosLimitsMaxTresMinutesPer struct {
	Qos *[]V0042Tres `json:"qos,omitempty"`
	Job *[]V0042Tres `json:"job,omitempty"`
	Account *[]V0042Tres `json:"account,omitempty"`
	User *[]V0042Tres `json:"user,omitempty"`
}

// NewV0042QosLimitsMaxTresMinutesPer instantiates a new V0042QosLimitsMaxTresMinutesPer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042QosLimitsMaxTresMinutesPer() *V0042QosLimitsMaxTresMinutesPer {
	this := V0042QosLimitsMaxTresMinutesPer{}
	return &this
}

// NewV0042QosLimitsMaxTresMinutesPerWithDefaults instantiates a new V0042QosLimitsMaxTresMinutesPer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042QosLimitsMaxTresMinutesPerWithDefaults() *V0042QosLimitsMaxTresMinutesPer {
	this := V0042QosLimitsMaxTresMinutesPer{}
	return &this
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutesPer) GetQos() []V0042Tres {
	if o == nil || o.Qos == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) GetQosOk() (*[]V0042Tres, bool) {
	if o == nil || o.Qos == nil {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) HasQos() bool {
	if o != nil && o.Qos != nil {
		return true
	}

	return false
}

// SetQos gets a reference to the given []V0042Tres and assigns it to the Qos field.
func (o *V0042QosLimitsMaxTresMinutesPer) SetQos(v []V0042Tres) {
	o.Qos = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutesPer) GetJob() []V0042Tres {
	if o == nil || o.Job == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) GetJobOk() (*[]V0042Tres, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given []V0042Tres and assigns it to the Job field.
func (o *V0042QosLimitsMaxTresMinutesPer) SetJob(v []V0042Tres) {
	o.Job = &v
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutesPer) GetAccount() []V0042Tres {
	if o == nil || o.Account == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) GetAccountOk() (*[]V0042Tres, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given []V0042Tres and assigns it to the Account field.
func (o *V0042QosLimitsMaxTresMinutesPer) SetAccount(v []V0042Tres) {
	o.Account = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutesPer) GetUser() []V0042Tres {
	if o == nil || o.User == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) GetUserOk() (*[]V0042Tres, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutesPer) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given []V0042Tres and assigns it to the User field.
func (o *V0042QosLimitsMaxTresMinutesPer) SetUser(v []V0042Tres) {
	o.User = &v
}

func (o V0042QosLimitsMaxTresMinutesPer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Qos != nil {
		toSerialize["qos"] = o.Qos
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableV0042QosLimitsMaxTresMinutesPer struct {
	value *V0042QosLimitsMaxTresMinutesPer
	isSet bool
}

func (v NullableV0042QosLimitsMaxTresMinutesPer) Get() *V0042QosLimitsMaxTresMinutesPer {
	return v.value
}

func (v *NullableV0042QosLimitsMaxTresMinutesPer) Set(val *V0042QosLimitsMaxTresMinutesPer) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042QosLimitsMaxTresMinutesPer) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042QosLimitsMaxTresMinutesPer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042QosLimitsMaxTresMinutesPer(val *V0042QosLimitsMaxTresMinutesPer) *NullableV0042QosLimitsMaxTresMinutesPer {
	return &NullableV0042QosLimitsMaxTresMinutesPer{value: val, isSet: true}
}

func (v NullableV0042QosLimitsMaxTresMinutesPer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042QosLimitsMaxTresMinutesPer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


