/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// InlineResponse200MetaClient struct for InlineResponse200MetaClient
type InlineResponse200MetaClient struct {
	// Client source description
	Source *string `json:"source,omitempty"`
	// Client user (if known)
	User *string `json:"user,omitempty"`
	// Client group (if known)
	Group *string `json:"group,omitempty"`
}

// NewInlineResponse200MetaClient instantiates a new InlineResponse200MetaClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse200MetaClient() *InlineResponse200MetaClient {
	this := InlineResponse200MetaClient{}
	return &this
}

// NewInlineResponse200MetaClientWithDefaults instantiates a new InlineResponse200MetaClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse200MetaClientWithDefaults() *InlineResponse200MetaClient {
	this := InlineResponse200MetaClient{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *InlineResponse200MetaClient) GetSource() string {
	if o == nil || o.Source == nil {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200MetaClient) GetSourceOk() (*string, bool) {
	if o == nil || o.Source == nil {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *InlineResponse200MetaClient) HasSource() bool {
	if o != nil && o.Source != nil {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *InlineResponse200MetaClient) SetSource(v string) {
	o.Source = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *InlineResponse200MetaClient) GetUser() string {
	if o == nil || o.User == nil {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200MetaClient) GetUserOk() (*string, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *InlineResponse200MetaClient) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *InlineResponse200MetaClient) SetUser(v string) {
	o.User = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *InlineResponse200MetaClient) GetGroup() string {
	if o == nil || o.Group == nil {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse200MetaClient) GetGroupOk() (*string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *InlineResponse200MetaClient) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *InlineResponse200MetaClient) SetGroup(v string) {
	o.Group = &v
}

func (o InlineResponse200MetaClient) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Source != nil {
		toSerialize["source"] = o.Source
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse200MetaClient struct {
	value *InlineResponse200MetaClient
	isSet bool
}

func (v NullableInlineResponse200MetaClient) Get() *InlineResponse200MetaClient {
	return v.value
}

func (v *NullableInlineResponse200MetaClient) Set(val *InlineResponse200MetaClient) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse200MetaClient) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse200MetaClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse200MetaClient(val *InlineResponse200MetaClient) *NullableInlineResponse200MetaClient {
	return &NullableInlineResponse200MetaClient{value: val, isSet: true}
}

func (v NullableInlineResponse200MetaClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse200MetaClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


