/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042JobTimeTotal struct for V0042JobTimeTotal
type V0042JobTimeTotal struct {
	// Sum of System and User CPU time used by the job in seconds
	Seconds *int64 `json:"seconds,omitempty"`
	// Sum of System and User CPU time used by the job in microseconds
	Microseconds *int64 `json:"microseconds,omitempty"`
}

// NewV0042JobTimeTotal instantiates a new V0042JobTimeTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042JobTimeTotal() *V0042JobTimeTotal {
	this := V0042JobTimeTotal{}
	return &this
}

// NewV0042JobTimeTotalWithDefaults instantiates a new V0042JobTimeTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042JobTimeTotalWithDefaults() *V0042JobTimeTotal {
	this := V0042JobTimeTotal{}
	return &this
}

// GetSeconds returns the Seconds field value if set, zero value otherwise.
func (o *V0042JobTimeTotal) GetSeconds() int64 {
	if o == nil || o.Seconds == nil {
		var ret int64
		return ret
	}
	return *o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042JobTimeTotal) GetSecondsOk() (*int64, bool) {
	if o == nil || o.Seconds == nil {
		return nil, false
	}
	return o.Seconds, true
}

// HasSeconds returns a boolean if a field has been set.
func (o *V0042JobTimeTotal) HasSeconds() bool {
	if o != nil && o.Seconds != nil {
		return true
	}

	return false
}

// SetSeconds gets a reference to the given int64 and assigns it to the Seconds field.
func (o *V0042JobTimeTotal) SetSeconds(v int64) {
	o.Seconds = &v
}

// GetMicroseconds returns the Microseconds field value if set, zero value otherwise.
func (o *V0042JobTimeTotal) GetMicroseconds() int64 {
	if o == nil || o.Microseconds == nil {
		var ret int64
		return ret
	}
	return *o.Microseconds
}

// GetMicrosecondsOk returns a tuple with the Microseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042JobTimeTotal) GetMicrosecondsOk() (*int64, bool) {
	if o == nil || o.Microseconds == nil {
		return nil, false
	}
	return o.Microseconds, true
}

// HasMicroseconds returns a boolean if a field has been set.
func (o *V0042JobTimeTotal) HasMicroseconds() bool {
	if o != nil && o.Microseconds != nil {
		return true
	}

	return false
}

// SetMicroseconds gets a reference to the given int64 and assigns it to the Microseconds field.
func (o *V0042JobTimeTotal) SetMicroseconds(v int64) {
	o.Microseconds = &v
}

func (o V0042JobTimeTotal) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Seconds != nil {
		toSerialize["seconds"] = o.Seconds
	}
	if o.Microseconds != nil {
		toSerialize["microseconds"] = o.Microseconds
	}
	return json.Marshal(toSerialize)
}

type NullableV0042JobTimeTotal struct {
	value *V0042JobTimeTotal
	isSet bool
}

func (v NullableV0042JobTimeTotal) Get() *V0042JobTimeTotal {
	return v.value
}

func (v *NullableV0042JobTimeTotal) Set(val *V0042JobTimeTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042JobTimeTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042JobTimeTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042JobTimeTotal(val *V0042JobTimeTotal) *NullableV0042JobTimeTotal {
	return &NullableV0042JobTimeTotal{value: val, isSet: true}
}

func (v NullableV0042JobTimeTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042JobTimeTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


