/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042AssocShort struct for V0042AssocShort
type V0042AssocShort struct {
	// Account name
	Account *string `json:"account,omitempty"`
	// Cluster name
	Cluster *string `json:"cluster,omitempty"`
	// Partition name
	Partition *string `json:"partition,omitempty"`
	// User name
	User string `json:"user"`
	// Numeric association ID
	Id *int32 `json:"id,omitempty"`
}

// NewV0042AssocShort instantiates a new V0042AssocShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042AssocShort(user string) *V0042AssocShort {
	this := V0042AssocShort{}
	this.User = user
	return &this
}

// NewV0042AssocShortWithDefaults instantiates a new V0042AssocShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042AssocShortWithDefaults() *V0042AssocShort {
	this := V0042AssocShort{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0042AssocShort) GetAccount() string {
	if o == nil || o.Account == nil {
		var ret string
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042AssocShort) GetAccountOk() (*string, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0042AssocShort) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given string and assigns it to the Account field.
func (o *V0042AssocShort) SetAccount(v string) {
	o.Account = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *V0042AssocShort) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042AssocShort) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *V0042AssocShort) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *V0042AssocShort) SetCluster(v string) {
	o.Cluster = &v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *V0042AssocShort) GetPartition() string {
	if o == nil || o.Partition == nil {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042AssocShort) GetPartitionOk() (*string, bool) {
	if o == nil || o.Partition == nil {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *V0042AssocShort) HasPartition() bool {
	if o != nil && o.Partition != nil {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *V0042AssocShort) SetPartition(v string) {
	o.Partition = &v
}

// GetUser returns the User field value
func (o *V0042AssocShort) GetUser() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *V0042AssocShort) GetUserOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *V0042AssocShort) SetUser(v string) {
	o.User = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V0042AssocShort) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042AssocShort) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V0042AssocShort) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V0042AssocShort) SetId(v int32) {
	o.Id = &v
}

func (o V0042AssocShort) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.Partition != nil {
		toSerialize["partition"] = o.Partition
	}
	if true {
		toSerialize["user"] = o.User
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableV0042AssocShort struct {
	value *V0042AssocShort
	isSet bool
}

func (v NullableV0042AssocShort) Get() *V0042AssocShort {
	return v.value
}

func (v *NullableV0042AssocShort) Set(val *V0042AssocShort) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042AssocShort) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042AssocShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042AssocShort(val *V0042AssocShort) *NullableV0042AssocShort {
	return &NullableV0042AssocShort{value: val, isSet: true}
}

func (v NullableV0042AssocShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042AssocShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


