/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042OpenapiSharesResp struct for V0042OpenapiSharesResp
type V0042OpenapiSharesResp struct {
	Shares V0042SharesRespMsg `json:"shares"`
	Meta *V0042OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0042OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0042OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0042OpenapiSharesResp instantiates a new V0042OpenapiSharesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042OpenapiSharesResp(shares V0042SharesRespMsg) *V0042OpenapiSharesResp {
	this := V0042OpenapiSharesResp{}
	this.Shares = shares
	return &this
}

// NewV0042OpenapiSharesRespWithDefaults instantiates a new V0042OpenapiSharesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042OpenapiSharesRespWithDefaults() *V0042OpenapiSharesResp {
	this := V0042OpenapiSharesResp{}
	return &this
}

// GetShares returns the Shares field value
func (o *V0042OpenapiSharesResp) GetShares() V0042SharesRespMsg {
	if o == nil {
		var ret V0042SharesRespMsg
		return ret
	}

	return o.Shares
}

// GetSharesOk returns a tuple with the Shares field value
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSharesResp) GetSharesOk() (*V0042SharesRespMsg, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Shares, true
}

// SetShares sets field value
func (o *V0042OpenapiSharesResp) SetShares(v V0042SharesRespMsg) {
	o.Shares = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0042OpenapiSharesResp) GetMeta() V0042OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0042OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSharesResp) GetMetaOk() (*V0042OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0042OpenapiSharesResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0042OpenapiMeta and assigns it to the Meta field.
func (o *V0042OpenapiSharesResp) SetMeta(v V0042OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0042OpenapiSharesResp) GetErrors() []V0042OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0042OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSharesResp) GetErrorsOk() (*[]V0042OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0042OpenapiSharesResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0042OpenapiError and assigns it to the Errors field.
func (o *V0042OpenapiSharesResp) SetErrors(v []V0042OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0042OpenapiSharesResp) GetWarnings() []V0042OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0042OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSharesResp) GetWarningsOk() (*[]V0042OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0042OpenapiSharesResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0042OpenapiWarning and assigns it to the Warnings field.
func (o *V0042OpenapiSharesResp) SetWarnings(v []V0042OpenapiWarning) {
	o.Warnings = &v
}

func (o V0042OpenapiSharesResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["shares"] = o.Shares
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0042OpenapiSharesResp struct {
	value *V0042OpenapiSharesResp
	isSet bool
}

func (v NullableV0042OpenapiSharesResp) Get() *V0042OpenapiSharesResp {
	return v.value
}

func (v *NullableV0042OpenapiSharesResp) Set(val *V0042OpenapiSharesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042OpenapiSharesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042OpenapiSharesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042OpenapiSharesResp(val *V0042OpenapiSharesResp) *NullableV0042OpenapiSharesResp {
	return &NullableV0042OpenapiSharesResp{value: val, isSet: true}
}

func (v NullableV0042OpenapiSharesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042OpenapiSharesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


