/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// SlurmV0041JobSubmitRlimitsCore Largest core file that can be created, in bytes.
type SlurmV0041JobSubmitRlimitsCore struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int64 `json:"number,omitempty"`
}

// NewSlurmV0041JobSubmitRlimitsCore instantiates a new SlurmV0041JobSubmitRlimitsCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041JobSubmitRlimitsCore() *SlurmV0041JobSubmitRlimitsCore {
	this := SlurmV0041JobSubmitRlimitsCore{}
	return &this
}

// NewSlurmV0041JobSubmitRlimitsCoreWithDefaults instantiates a new SlurmV0041JobSubmitRlimitsCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041JobSubmitRlimitsCoreWithDefaults() *SlurmV0041JobSubmitRlimitsCore {
	this := SlurmV0041JobSubmitRlimitsCore{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitRlimitsCore) GetSet() bool {
	if o == nil || o.Set == nil {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) GetSetOk() (*bool, bool) {
	if o == nil || o.Set == nil {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) HasSet() bool {
	if o != nil && o.Set != nil {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmV0041JobSubmitRlimitsCore) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitRlimitsCore) GetInfinite() bool {
	if o == nil || o.Infinite == nil {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) GetInfiniteOk() (*bool, bool) {
	if o == nil || o.Infinite == nil {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) HasInfinite() bool {
	if o != nil && o.Infinite != nil {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmV0041JobSubmitRlimitsCore) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitRlimitsCore) GetNumber() int64 {
	if o == nil || o.Number == nil {
		var ret int64
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) GetNumberOk() (*int64, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitRlimitsCore) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int64 and assigns it to the Number field.
func (o *SlurmV0041JobSubmitRlimitsCore) SetNumber(v int64) {
	o.Number = &v
}

func (o SlurmV0041JobSubmitRlimitsCore) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Set != nil {
		toSerialize["set"] = o.Set
	}
	if o.Infinite != nil {
		toSerialize["infinite"] = o.Infinite
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	return json.Marshal(toSerialize)
}

type NullableSlurmV0041JobSubmitRlimitsCore struct {
	value *SlurmV0041JobSubmitRlimitsCore
	isSet bool
}

func (v NullableSlurmV0041JobSubmitRlimitsCore) Get() *SlurmV0041JobSubmitRlimitsCore {
	return v.value
}

func (v *NullableSlurmV0041JobSubmitRlimitsCore) Set(val *SlurmV0041JobSubmitRlimitsCore) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041JobSubmitRlimitsCore) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041JobSubmitRlimitsCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041JobSubmitRlimitsCore(val *SlurmV0041JobSubmitRlimitsCore) *NullableSlurmV0041JobSubmitRlimitsCore {
	return &NullableSlurmV0041JobSubmitRlimitsCore{value: val, isSet: true}
}

func (v NullableSlurmV0041JobSubmitRlimitsCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041JobSubmitRlimitsCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


