/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043AssocSharesObjWrap struct for V0043AssocSharesObjWrap
type V0043AssocSharesObjWrap struct {
	// Association ID
	Id *int32 `json:"id,omitempty"`
	// Cluster name
	Cluster *string `json:"cluster,omitempty"`
	// Share name
	Name *string `json:"name,omitempty"`
	// Parent name
	Parent *string `json:"parent,omitempty"`
	// Partition name
	Partition *string `json:"partition,omitempty"`
	SharesNormalized *V0043Float64NoValStruct `json:"shares_normalized,omitempty"`
	Shares *V0043Uint32NoValStruct `json:"shares,omitempty"`
	Tres *V0043AssocSharesObjWrapTres `json:"tres,omitempty"`
	EffectiveUsage *V0043Float64NoValStruct `json:"effective_usage,omitempty"`
	UsageNormalized *V0043Float64NoValStruct `json:"usage_normalized,omitempty"`
	// Measure of tresbillableunits usage
	Usage *int64 `json:"usage,omitempty"`
	Fairshare *V0043AssocSharesObjWrapFairshare `json:"fairshare,omitempty"`
	// User or account association
	Type *[]string `json:"type,omitempty"`
}

// NewV0043AssocSharesObjWrap instantiates a new V0043AssocSharesObjWrap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043AssocSharesObjWrap() *V0043AssocSharesObjWrap {
	this := V0043AssocSharesObjWrap{}
	return &this
}

// NewV0043AssocSharesObjWrapWithDefaults instantiates a new V0043AssocSharesObjWrap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043AssocSharesObjWrapWithDefaults() *V0043AssocSharesObjWrap {
	this := V0043AssocSharesObjWrap{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *V0043AssocSharesObjWrap) SetId(v int32) {
	o.Id = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *V0043AssocSharesObjWrap) SetCluster(v string) {
	o.Cluster = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0043AssocSharesObjWrap) SetName(v string) {
	o.Name = &v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetParent() string {
	if o == nil || o.Parent == nil {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetParentOk() (*string, bool) {
	if o == nil || o.Parent == nil {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasParent() bool {
	if o != nil && o.Parent != nil {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *V0043AssocSharesObjWrap) SetParent(v string) {
	o.Parent = &v
}

// GetPartition returns the Partition field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetPartition() string {
	if o == nil || o.Partition == nil {
		var ret string
		return ret
	}
	return *o.Partition
}

// GetPartitionOk returns a tuple with the Partition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetPartitionOk() (*string, bool) {
	if o == nil || o.Partition == nil {
		return nil, false
	}
	return o.Partition, true
}

// HasPartition returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasPartition() bool {
	if o != nil && o.Partition != nil {
		return true
	}

	return false
}

// SetPartition gets a reference to the given string and assigns it to the Partition field.
func (o *V0043AssocSharesObjWrap) SetPartition(v string) {
	o.Partition = &v
}

// GetSharesNormalized returns the SharesNormalized field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetSharesNormalized() V0043Float64NoValStruct {
	if o == nil || o.SharesNormalized == nil {
		var ret V0043Float64NoValStruct
		return ret
	}
	return *o.SharesNormalized
}

// GetSharesNormalizedOk returns a tuple with the SharesNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetSharesNormalizedOk() (*V0043Float64NoValStruct, bool) {
	if o == nil || o.SharesNormalized == nil {
		return nil, false
	}
	return o.SharesNormalized, true
}

// HasSharesNormalized returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasSharesNormalized() bool {
	if o != nil && o.SharesNormalized != nil {
		return true
	}

	return false
}

// SetSharesNormalized gets a reference to the given V0043Float64NoValStruct and assigns it to the SharesNormalized field.
func (o *V0043AssocSharesObjWrap) SetSharesNormalized(v V0043Float64NoValStruct) {
	o.SharesNormalized = &v
}

// GetShares returns the Shares field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetShares() V0043Uint32NoValStruct {
	if o == nil || o.Shares == nil {
		var ret V0043Uint32NoValStruct
		return ret
	}
	return *o.Shares
}

// GetSharesOk returns a tuple with the Shares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetSharesOk() (*V0043Uint32NoValStruct, bool) {
	if o == nil || o.Shares == nil {
		return nil, false
	}
	return o.Shares, true
}

// HasShares returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasShares() bool {
	if o != nil && o.Shares != nil {
		return true
	}

	return false
}

// SetShares gets a reference to the given V0043Uint32NoValStruct and assigns it to the Shares field.
func (o *V0043AssocSharesObjWrap) SetShares(v V0043Uint32NoValStruct) {
	o.Shares = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetTres() V0043AssocSharesObjWrapTres {
	if o == nil || o.Tres == nil {
		var ret V0043AssocSharesObjWrapTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetTresOk() (*V0043AssocSharesObjWrapTres, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given V0043AssocSharesObjWrapTres and assigns it to the Tres field.
func (o *V0043AssocSharesObjWrap) SetTres(v V0043AssocSharesObjWrapTres) {
	o.Tres = &v
}

// GetEffectiveUsage returns the EffectiveUsage field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetEffectiveUsage() V0043Float64NoValStruct {
	if o == nil || o.EffectiveUsage == nil {
		var ret V0043Float64NoValStruct
		return ret
	}
	return *o.EffectiveUsage
}

// GetEffectiveUsageOk returns a tuple with the EffectiveUsage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetEffectiveUsageOk() (*V0043Float64NoValStruct, bool) {
	if o == nil || o.EffectiveUsage == nil {
		return nil, false
	}
	return o.EffectiveUsage, true
}

// HasEffectiveUsage returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasEffectiveUsage() bool {
	if o != nil && o.EffectiveUsage != nil {
		return true
	}

	return false
}

// SetEffectiveUsage gets a reference to the given V0043Float64NoValStruct and assigns it to the EffectiveUsage field.
func (o *V0043AssocSharesObjWrap) SetEffectiveUsage(v V0043Float64NoValStruct) {
	o.EffectiveUsage = &v
}

// GetUsageNormalized returns the UsageNormalized field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetUsageNormalized() V0043Float64NoValStruct {
	if o == nil || o.UsageNormalized == nil {
		var ret V0043Float64NoValStruct
		return ret
	}
	return *o.UsageNormalized
}

// GetUsageNormalizedOk returns a tuple with the UsageNormalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetUsageNormalizedOk() (*V0043Float64NoValStruct, bool) {
	if o == nil || o.UsageNormalized == nil {
		return nil, false
	}
	return o.UsageNormalized, true
}

// HasUsageNormalized returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasUsageNormalized() bool {
	if o != nil && o.UsageNormalized != nil {
		return true
	}

	return false
}

// SetUsageNormalized gets a reference to the given V0043Float64NoValStruct and assigns it to the UsageNormalized field.
func (o *V0043AssocSharesObjWrap) SetUsageNormalized(v V0043Float64NoValStruct) {
	o.UsageNormalized = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetUsage() int64 {
	if o == nil || o.Usage == nil {
		var ret int64
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetUsageOk() (*int64, bool) {
	if o == nil || o.Usage == nil {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasUsage() bool {
	if o != nil && o.Usage != nil {
		return true
	}

	return false
}

// SetUsage gets a reference to the given int64 and assigns it to the Usage field.
func (o *V0043AssocSharesObjWrap) SetUsage(v int64) {
	o.Usage = &v
}

// GetFairshare returns the Fairshare field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetFairshare() V0043AssocSharesObjWrapFairshare {
	if o == nil || o.Fairshare == nil {
		var ret V0043AssocSharesObjWrapFairshare
		return ret
	}
	return *o.Fairshare
}

// GetFairshareOk returns a tuple with the Fairshare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetFairshareOk() (*V0043AssocSharesObjWrapFairshare, bool) {
	if o == nil || o.Fairshare == nil {
		return nil, false
	}
	return o.Fairshare, true
}

// HasFairshare returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasFairshare() bool {
	if o != nil && o.Fairshare != nil {
		return true
	}

	return false
}

// SetFairshare gets a reference to the given V0043AssocSharesObjWrapFairshare and assigns it to the Fairshare field.
func (o *V0043AssocSharesObjWrap) SetFairshare(v V0043AssocSharesObjWrapFairshare) {
	o.Fairshare = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V0043AssocSharesObjWrap) GetType() []string {
	if o == nil || o.Type == nil {
		var ret []string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043AssocSharesObjWrap) GetTypeOk() (*[]string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V0043AssocSharesObjWrap) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given []string and assigns it to the Type field.
func (o *V0043AssocSharesObjWrap) SetType(v []string) {
	o.Type = &v
}

func (o V0043AssocSharesObjWrap) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Parent != nil {
		toSerialize["parent"] = o.Parent
	}
	if o.Partition != nil {
		toSerialize["partition"] = o.Partition
	}
	if o.SharesNormalized != nil {
		toSerialize["shares_normalized"] = o.SharesNormalized
	}
	if o.Shares != nil {
		toSerialize["shares"] = o.Shares
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	if o.EffectiveUsage != nil {
		toSerialize["effective_usage"] = o.EffectiveUsage
	}
	if o.UsageNormalized != nil {
		toSerialize["usage_normalized"] = o.UsageNormalized
	}
	if o.Usage != nil {
		toSerialize["usage"] = o.Usage
	}
	if o.Fairshare != nil {
		toSerialize["fairshare"] = o.Fairshare
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableV0043AssocSharesObjWrap struct {
	value *V0043AssocSharesObjWrap
	isSet bool
}

func (v NullableV0043AssocSharesObjWrap) Get() *V0043AssocSharesObjWrap {
	return v.value
}

func (v *NullableV0043AssocSharesObjWrap) Set(val *V0043AssocSharesObjWrap) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043AssocSharesObjWrap) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043AssocSharesObjWrap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043AssocSharesObjWrap(val *V0043AssocSharesObjWrap) *NullableV0043AssocSharesObjWrap {
	return &NullableV0043AssocSharesObjWrap{value: val, isSet: true}
}

func (v NullableV0043AssocSharesObjWrap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043AssocSharesObjWrap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


