/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043StatsRpcTime struct for V0043StatsRpcTime
type V0043StatsRpcTime struct {
	// Average RPC processing time in microseconds
	Average *int64 `json:"average,omitempty"`
	// Total RPC processing time in microseconds
	Total *int64 `json:"total,omitempty"`
}

// NewV0043StatsRpcTime instantiates a new V0043StatsRpcTime object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043StatsRpcTime() *V0043StatsRpcTime {
	this := V0043StatsRpcTime{}
	return &this
}

// NewV0043StatsRpcTimeWithDefaults instantiates a new V0043StatsRpcTime object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043StatsRpcTimeWithDefaults() *V0043StatsRpcTime {
	this := V0043StatsRpcTime{}
	return &this
}

// GetAverage returns the Average field value if set, zero value otherwise.
func (o *V0043StatsRpcTime) GetAverage() int64 {
	if o == nil || o.Average == nil {
		var ret int64
		return ret
	}
	return *o.Average
}

// GetAverageOk returns a tuple with the Average field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043StatsRpcTime) GetAverageOk() (*int64, bool) {
	if o == nil || o.Average == nil {
		return nil, false
	}
	return o.Average, true
}

// HasAverage returns a boolean if a field has been set.
func (o *V0043StatsRpcTime) HasAverage() bool {
	if o != nil && o.Average != nil {
		return true
	}

	return false
}

// SetAverage gets a reference to the given int64 and assigns it to the Average field.
func (o *V0043StatsRpcTime) SetAverage(v int64) {
	o.Average = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0043StatsRpcTime) GetTotal() int64 {
	if o == nil || o.Total == nil {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043StatsRpcTime) GetTotalOk() (*int64, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0043StatsRpcTime) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *V0043StatsRpcTime) SetTotal(v int64) {
	o.Total = &v
}

func (o V0043StatsRpcTime) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Average != nil {
		toSerialize["average"] = o.Average
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableV0043StatsRpcTime struct {
	value *V0043StatsRpcTime
	isSet bool
}

func (v NullableV0043StatsRpcTime) Get() *V0043StatsRpcTime {
	return v.value
}

func (v *NullableV0043StatsRpcTime) Set(val *V0043StatsRpcTime) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043StatsRpcTime) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043StatsRpcTime) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043StatsRpcTime(val *V0043StatsRpcTime) *NullableV0043StatsRpcTime {
	return &NullableV0043StatsRpcTime{value: val, isSet: true}
}

func (v NullableV0043StatsRpcTime) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043StatsRpcTime) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


