/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// SlurmV0041JobSubmitPriority Request specific job priority
type SlurmV0041JobSubmitPriority struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewSlurmV0041JobSubmitPriority instantiates a new SlurmV0041JobSubmitPriority object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041JobSubmitPriority() *SlurmV0041JobSubmitPriority {
	this := SlurmV0041JobSubmitPriority{}
	return &this
}

// NewSlurmV0041JobSubmitPriorityWithDefaults instantiates a new SlurmV0041JobSubmitPriority object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041JobSubmitPriorityWithDefaults() *SlurmV0041JobSubmitPriority {
	this := SlurmV0041JobSubmitPriority{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitPriority) GetSet() bool {
	if o == nil || o.Set == nil {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitPriority) GetSetOk() (*bool, bool) {
	if o == nil || o.Set == nil {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitPriority) HasSet() bool {
	if o != nil && o.Set != nil {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmV0041JobSubmitPriority) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitPriority) GetInfinite() bool {
	if o == nil || o.Infinite == nil {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitPriority) GetInfiniteOk() (*bool, bool) {
	if o == nil || o.Infinite == nil {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitPriority) HasInfinite() bool {
	if o != nil && o.Infinite != nil {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmV0041JobSubmitPriority) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmV0041JobSubmitPriority) GetNumber() int32 {
	if o == nil || o.Number == nil {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041JobSubmitPriority) GetNumberOk() (*int32, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmV0041JobSubmitPriority) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SlurmV0041JobSubmitPriority) SetNumber(v int32) {
	o.Number = &v
}

func (o SlurmV0041JobSubmitPriority) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Set != nil {
		toSerialize["set"] = o.Set
	}
	if o.Infinite != nil {
		toSerialize["infinite"] = o.Infinite
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	return json.Marshal(toSerialize)
}

type NullableSlurmV0041JobSubmitPriority struct {
	value *SlurmV0041JobSubmitPriority
	isSet bool
}

func (v NullableSlurmV0041JobSubmitPriority) Get() *SlurmV0041JobSubmitPriority {
	return v.value
}

func (v *NullableSlurmV0041JobSubmitPriority) Set(val *SlurmV0041JobSubmitPriority) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041JobSubmitPriority) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041JobSubmitPriority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041JobSubmitPriority(val *SlurmV0041JobSubmitPriority) *NullableSlurmV0041JobSubmitPriority {
	return &NullableSlurmV0041JobSubmitPriority{value: val, isSet: true}
}

func (v NullableSlurmV0041JobSubmitPriority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041JobSubmitPriority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


