/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSharesRespSharesTresRunSeconds struct for V0041OpenapiSharesRespSharesTresRunSeconds
type V0041OpenapiSharesRespSharesTresRunSeconds struct {
	// TRES name
	Name *string `json:"name,omitempty"`
	Value *V0041OpenapiSharesRespSharesTresValue `json:"value,omitempty"`
}

// NewV0041OpenapiSharesRespSharesTresRunSeconds instantiates a new V0041OpenapiSharesRespSharesTresRunSeconds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSharesRespSharesTresRunSeconds() *V0041OpenapiSharesRespSharesTresRunSeconds {
	this := V0041OpenapiSharesRespSharesTresRunSeconds{}
	return &this
}

// NewV0041OpenapiSharesRespSharesTresRunSecondsWithDefaults instantiates a new V0041OpenapiSharesRespSharesTresRunSeconds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSharesRespSharesTresRunSecondsWithDefaults() *V0041OpenapiSharesRespSharesTresRunSeconds {
	this := V0041OpenapiSharesRespSharesTresRunSeconds{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) GetValue() V0041OpenapiSharesRespSharesTresValue {
	if o == nil || o.Value == nil {
		var ret V0041OpenapiSharesRespSharesTresValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) GetValueOk() (*V0041OpenapiSharesRespSharesTresValue, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given V0041OpenapiSharesRespSharesTresValue and assigns it to the Value field.
func (o *V0041OpenapiSharesRespSharesTresRunSeconds) SetValue(v V0041OpenapiSharesRespSharesTresValue) {
	o.Value = &v
}

func (o V0041OpenapiSharesRespSharesTresRunSeconds) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSharesRespSharesTresRunSeconds struct {
	value *V0041OpenapiSharesRespSharesTresRunSeconds
	isSet bool
}

func (v NullableV0041OpenapiSharesRespSharesTresRunSeconds) Get() *V0041OpenapiSharesRespSharesTresRunSeconds {
	return v.value
}

func (v *NullableV0041OpenapiSharesRespSharesTresRunSeconds) Set(val *V0041OpenapiSharesRespSharesTresRunSeconds) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSharesRespSharesTresRunSeconds) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSharesRespSharesTresRunSeconds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSharesRespSharesTresRunSeconds(val *V0041OpenapiSharesRespSharesTresRunSeconds) *NullableV0041OpenapiSharesRespSharesTresRunSeconds {
	return &NullableV0041OpenapiSharesRespSharesTresRunSeconds{value: val, isSet: true}
}

func (v NullableV0041OpenapiSharesRespSharesTresRunSeconds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSharesRespSharesTresRunSeconds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


