/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042OpenapiSlurmdbdConfigResp struct for V0042OpenapiSlurmdbdConfigResp
type V0042OpenapiSlurmdbdConfigResp struct {
	Clusters *[]V0042ClusterRec `json:"clusters,omitempty"`
	Tres *[]V0042Tres `json:"tres,omitempty"`
	Accounts *[]V0042Account `json:"accounts,omitempty"`
	Users *[]V0042User `json:"users,omitempty"`
	Qos *[]V0042Qos `json:"qos,omitempty"`
	Wckeys *[]V0042Wckey `json:"wckeys,omitempty"`
	Associations *[]V0042Assoc `json:"associations,omitempty"`
	Instances *[]V0042Instance `json:"instances,omitempty"`
	Meta *V0042OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0042OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0042OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0042OpenapiSlurmdbdConfigResp instantiates a new V0042OpenapiSlurmdbdConfigResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042OpenapiSlurmdbdConfigResp() *V0042OpenapiSlurmdbdConfigResp {
	this := V0042OpenapiSlurmdbdConfigResp{}
	return &this
}

// NewV0042OpenapiSlurmdbdConfigRespWithDefaults instantiates a new V0042OpenapiSlurmdbdConfigResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042OpenapiSlurmdbdConfigRespWithDefaults() *V0042OpenapiSlurmdbdConfigResp {
	this := V0042OpenapiSlurmdbdConfigResp{}
	return &this
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetClusters() []V0042ClusterRec {
	if o == nil || o.Clusters == nil {
		var ret []V0042ClusterRec
		return ret
	}
	return *o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetClustersOk() (*[]V0042ClusterRec, bool) {
	if o == nil || o.Clusters == nil {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasClusters() bool {
	if o != nil && o.Clusters != nil {
		return true
	}

	return false
}

// SetClusters gets a reference to the given []V0042ClusterRec and assigns it to the Clusters field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetClusters(v []V0042ClusterRec) {
	o.Clusters = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetTres() []V0042Tres {
	if o == nil || o.Tres == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetTresOk() (*[]V0042Tres, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given []V0042Tres and assigns it to the Tres field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetTres(v []V0042Tres) {
	o.Tres = &v
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetAccounts() []V0042Account {
	if o == nil || o.Accounts == nil {
		var ret []V0042Account
		return ret
	}
	return *o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetAccountsOk() (*[]V0042Account, bool) {
	if o == nil || o.Accounts == nil {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasAccounts() bool {
	if o != nil && o.Accounts != nil {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []V0042Account and assigns it to the Accounts field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetAccounts(v []V0042Account) {
	o.Accounts = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetUsers() []V0042User {
	if o == nil || o.Users == nil {
		var ret []V0042User
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetUsersOk() (*[]V0042User, bool) {
	if o == nil || o.Users == nil {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasUsers() bool {
	if o != nil && o.Users != nil {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []V0042User and assigns it to the Users field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetUsers(v []V0042User) {
	o.Users = &v
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetQos() []V0042Qos {
	if o == nil || o.Qos == nil {
		var ret []V0042Qos
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetQosOk() (*[]V0042Qos, bool) {
	if o == nil || o.Qos == nil {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasQos() bool {
	if o != nil && o.Qos != nil {
		return true
	}

	return false
}

// SetQos gets a reference to the given []V0042Qos and assigns it to the Qos field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetQos(v []V0042Qos) {
	o.Qos = &v
}

// GetWckeys returns the Wckeys field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetWckeys() []V0042Wckey {
	if o == nil || o.Wckeys == nil {
		var ret []V0042Wckey
		return ret
	}
	return *o.Wckeys
}

// GetWckeysOk returns a tuple with the Wckeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetWckeysOk() (*[]V0042Wckey, bool) {
	if o == nil || o.Wckeys == nil {
		return nil, false
	}
	return o.Wckeys, true
}

// HasWckeys returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasWckeys() bool {
	if o != nil && o.Wckeys != nil {
		return true
	}

	return false
}

// SetWckeys gets a reference to the given []V0042Wckey and assigns it to the Wckeys field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetWckeys(v []V0042Wckey) {
	o.Wckeys = &v
}

// GetAssociations returns the Associations field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetAssociations() []V0042Assoc {
	if o == nil || o.Associations == nil {
		var ret []V0042Assoc
		return ret
	}
	return *o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetAssociationsOk() (*[]V0042Assoc, bool) {
	if o == nil || o.Associations == nil {
		return nil, false
	}
	return o.Associations, true
}

// HasAssociations returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasAssociations() bool {
	if o != nil && o.Associations != nil {
		return true
	}

	return false
}

// SetAssociations gets a reference to the given []V0042Assoc and assigns it to the Associations field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetAssociations(v []V0042Assoc) {
	o.Associations = &v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetInstances() []V0042Instance {
	if o == nil || o.Instances == nil {
		var ret []V0042Instance
		return ret
	}
	return *o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetInstancesOk() (*[]V0042Instance, bool) {
	if o == nil || o.Instances == nil {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasInstances() bool {
	if o != nil && o.Instances != nil {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []V0042Instance and assigns it to the Instances field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetInstances(v []V0042Instance) {
	o.Instances = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetMeta() V0042OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0042OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetMetaOk() (*V0042OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0042OpenapiMeta and assigns it to the Meta field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetMeta(v V0042OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetErrors() []V0042OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0042OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetErrorsOk() (*[]V0042OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0042OpenapiError and assigns it to the Errors field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetErrors(v []V0042OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0042OpenapiSlurmdbdConfigResp) GetWarnings() []V0042OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0042OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) GetWarningsOk() (*[]V0042OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0042OpenapiSlurmdbdConfigResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0042OpenapiWarning and assigns it to the Warnings field.
func (o *V0042OpenapiSlurmdbdConfigResp) SetWarnings(v []V0042OpenapiWarning) {
	o.Warnings = &v
}

func (o V0042OpenapiSlurmdbdConfigResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Clusters != nil {
		toSerialize["clusters"] = o.Clusters
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	if o.Accounts != nil {
		toSerialize["accounts"] = o.Accounts
	}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	if o.Qos != nil {
		toSerialize["qos"] = o.Qos
	}
	if o.Wckeys != nil {
		toSerialize["wckeys"] = o.Wckeys
	}
	if o.Associations != nil {
		toSerialize["associations"] = o.Associations
	}
	if o.Instances != nil {
		toSerialize["instances"] = o.Instances
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0042OpenapiSlurmdbdConfigResp struct {
	value *V0042OpenapiSlurmdbdConfigResp
	isSet bool
}

func (v NullableV0042OpenapiSlurmdbdConfigResp) Get() *V0042OpenapiSlurmdbdConfigResp {
	return v.value
}

func (v *NullableV0042OpenapiSlurmdbdConfigResp) Set(val *V0042OpenapiSlurmdbdConfigResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042OpenapiSlurmdbdConfigResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042OpenapiSlurmdbdConfigResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042OpenapiSlurmdbdConfigResp(val *V0042OpenapiSlurmdbdConfigResp) *NullableV0042OpenapiSlurmdbdConfigResp {
	return &NullableV0042OpenapiSlurmdbdConfigResp{value: val, isSet: true}
}

func (v NullableV0042OpenapiSlurmdbdConfigResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042OpenapiSlurmdbdConfigResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


