/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042Step struct for V0042Step
type V0042Step struct {
	Time *V0042StepTime `json:"time,omitempty"`
	ExitCode *V0042ProcessExitCodeVerbose `json:"exit_code,omitempty"`
	Nodes *V0042StepNodes `json:"nodes,omitempty"`
	Tasks *V0042StepTasks `json:"tasks,omitempty"`
	// Deprecated; Process ID
	// Deprecated
	Pid *string `json:"pid,omitempty"`
	CPU *V0042StepCPU `json:"CPU,omitempty"`
	// User ID that requested termination of the step
	KillRequestUser *string `json:"kill_request_user,omitempty"`
	State *[]string `json:"state,omitempty"`
	Statistics *V0042StepStatistics `json:"statistics,omitempty"`
	Step *V0042StepStep `json:"step,omitempty"`
	Task *V0042StepTask `json:"task,omitempty"`
	Tres *V0042StepTres `json:"tres,omitempty"`
}

// NewV0042Step instantiates a new V0042Step object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042Step() *V0042Step {
	this := V0042Step{}
	return &this
}

// NewV0042StepWithDefaults instantiates a new V0042Step object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042StepWithDefaults() *V0042Step {
	this := V0042Step{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0042Step) GetTime() V0042StepTime {
	if o == nil || o.Time == nil {
		var ret V0042StepTime
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetTimeOk() (*V0042StepTime, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0042Step) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given V0042StepTime and assigns it to the Time field.
func (o *V0042Step) SetTime(v V0042StepTime) {
	o.Time = &v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *V0042Step) GetExitCode() V0042ProcessExitCodeVerbose {
	if o == nil || o.ExitCode == nil {
		var ret V0042ProcessExitCodeVerbose
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetExitCodeOk() (*V0042ProcessExitCodeVerbose, bool) {
	if o == nil || o.ExitCode == nil {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *V0042Step) HasExitCode() bool {
	if o != nil && o.ExitCode != nil {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given V0042ProcessExitCodeVerbose and assigns it to the ExitCode field.
func (o *V0042Step) SetExitCode(v V0042ProcessExitCodeVerbose) {
	o.ExitCode = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *V0042Step) GetNodes() V0042StepNodes {
	if o == nil || o.Nodes == nil {
		var ret V0042StepNodes
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetNodesOk() (*V0042StepNodes, bool) {
	if o == nil || o.Nodes == nil {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *V0042Step) HasNodes() bool {
	if o != nil && o.Nodes != nil {
		return true
	}

	return false
}

// SetNodes gets a reference to the given V0042StepNodes and assigns it to the Nodes field.
func (o *V0042Step) SetNodes(v V0042StepNodes) {
	o.Nodes = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *V0042Step) GetTasks() V0042StepTasks {
	if o == nil || o.Tasks == nil {
		var ret V0042StepTasks
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetTasksOk() (*V0042StepTasks, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *V0042Step) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given V0042StepTasks and assigns it to the Tasks field.
func (o *V0042Step) SetTasks(v V0042StepTasks) {
	o.Tasks = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
// Deprecated
func (o *V0042Step) GetPid() string {
	if o == nil || o.Pid == nil {
		var ret string
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0042Step) GetPidOk() (*string, bool) {
	if o == nil || o.Pid == nil {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *V0042Step) HasPid() bool {
	if o != nil && o.Pid != nil {
		return true
	}

	return false
}

// SetPid gets a reference to the given string and assigns it to the Pid field.
// Deprecated
func (o *V0042Step) SetPid(v string) {
	o.Pid = &v
}

// GetCPU returns the CPU field value if set, zero value otherwise.
func (o *V0042Step) GetCPU() V0042StepCPU {
	if o == nil || o.CPU == nil {
		var ret V0042StepCPU
		return ret
	}
	return *o.CPU
}

// GetCPUOk returns a tuple with the CPU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetCPUOk() (*V0042StepCPU, bool) {
	if o == nil || o.CPU == nil {
		return nil, false
	}
	return o.CPU, true
}

// HasCPU returns a boolean if a field has been set.
func (o *V0042Step) HasCPU() bool {
	if o != nil && o.CPU != nil {
		return true
	}

	return false
}

// SetCPU gets a reference to the given V0042StepCPU and assigns it to the CPU field.
func (o *V0042Step) SetCPU(v V0042StepCPU) {
	o.CPU = &v
}

// GetKillRequestUser returns the KillRequestUser field value if set, zero value otherwise.
func (o *V0042Step) GetKillRequestUser() string {
	if o == nil || o.KillRequestUser == nil {
		var ret string
		return ret
	}
	return *o.KillRequestUser
}

// GetKillRequestUserOk returns a tuple with the KillRequestUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetKillRequestUserOk() (*string, bool) {
	if o == nil || o.KillRequestUser == nil {
		return nil, false
	}
	return o.KillRequestUser, true
}

// HasKillRequestUser returns a boolean if a field has been set.
func (o *V0042Step) HasKillRequestUser() bool {
	if o != nil && o.KillRequestUser != nil {
		return true
	}

	return false
}

// SetKillRequestUser gets a reference to the given string and assigns it to the KillRequestUser field.
func (o *V0042Step) SetKillRequestUser(v string) {
	o.KillRequestUser = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V0042Step) GetState() []string {
	if o == nil || o.State == nil {
		var ret []string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetStateOk() (*[]string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V0042Step) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *V0042Step) SetState(v []string) {
	o.State = &v
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
func (o *V0042Step) GetStatistics() V0042StepStatistics {
	if o == nil || o.Statistics == nil {
		var ret V0042StepStatistics
		return ret
	}
	return *o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetStatisticsOk() (*V0042StepStatistics, bool) {
	if o == nil || o.Statistics == nil {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *V0042Step) HasStatistics() bool {
	if o != nil && o.Statistics != nil {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given V0042StepStatistics and assigns it to the Statistics field.
func (o *V0042Step) SetStatistics(v V0042StepStatistics) {
	o.Statistics = &v
}

// GetStep returns the Step field value if set, zero value otherwise.
func (o *V0042Step) GetStep() V0042StepStep {
	if o == nil || o.Step == nil {
		var ret V0042StepStep
		return ret
	}
	return *o.Step
}

// GetStepOk returns a tuple with the Step field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetStepOk() (*V0042StepStep, bool) {
	if o == nil || o.Step == nil {
		return nil, false
	}
	return o.Step, true
}

// HasStep returns a boolean if a field has been set.
func (o *V0042Step) HasStep() bool {
	if o != nil && o.Step != nil {
		return true
	}

	return false
}

// SetStep gets a reference to the given V0042StepStep and assigns it to the Step field.
func (o *V0042Step) SetStep(v V0042StepStep) {
	o.Step = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *V0042Step) GetTask() V0042StepTask {
	if o == nil || o.Task == nil {
		var ret V0042StepTask
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetTaskOk() (*V0042StepTask, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *V0042Step) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given V0042StepTask and assigns it to the Task field.
func (o *V0042Step) SetTask(v V0042StepTask) {
	o.Task = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0042Step) GetTres() V0042StepTres {
	if o == nil || o.Tres == nil {
		var ret V0042StepTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Step) GetTresOk() (*V0042StepTres, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0042Step) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given V0042StepTres and assigns it to the Tres field.
func (o *V0042Step) SetTres(v V0042StepTres) {
	o.Tres = &v
}

func (o V0042Step) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	if o.ExitCode != nil {
		toSerialize["exit_code"] = o.ExitCode
	}
	if o.Nodes != nil {
		toSerialize["nodes"] = o.Nodes
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.Pid != nil {
		toSerialize["pid"] = o.Pid
	}
	if o.CPU != nil {
		toSerialize["CPU"] = o.CPU
	}
	if o.KillRequestUser != nil {
		toSerialize["kill_request_user"] = o.KillRequestUser
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Statistics != nil {
		toSerialize["statistics"] = o.Statistics
	}
	if o.Step != nil {
		toSerialize["step"] = o.Step
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	return json.Marshal(toSerialize)
}

type NullableV0042Step struct {
	value *V0042Step
	isSet bool
}

func (v NullableV0042Step) Get() *V0042Step {
	return v.value
}

func (v *NullableV0042Step) Set(val *V0042Step) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042Step) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042Step) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042Step(val *V0042Step) *NullableV0042Step {
	return &NullableV0042Step{value: val, isSet: true}
}

func (v NullableV0042Step) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042Step) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


