/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042OpenapiPingArrayResp struct for V0042OpenapiPingArrayResp
type V0042OpenapiPingArrayResp struct {
	Pings []V0042ControllerPing `json:"pings"`
	Meta *V0042OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0042OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0042OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0042OpenapiPingArrayResp instantiates a new V0042OpenapiPingArrayResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042OpenapiPingArrayResp(pings []V0042ControllerPing) *V0042OpenapiPingArrayResp {
	this := V0042OpenapiPingArrayResp{}
	this.Pings = pings
	return &this
}

// NewV0042OpenapiPingArrayRespWithDefaults instantiates a new V0042OpenapiPingArrayResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042OpenapiPingArrayRespWithDefaults() *V0042OpenapiPingArrayResp {
	this := V0042OpenapiPingArrayResp{}
	return &this
}

// GetPings returns the Pings field value
func (o *V0042OpenapiPingArrayResp) GetPings() []V0042ControllerPing {
	if o == nil {
		var ret []V0042ControllerPing
		return ret
	}

	return o.Pings
}

// GetPingsOk returns a tuple with the Pings field value
// and a boolean to check if the value has been set.
func (o *V0042OpenapiPingArrayResp) GetPingsOk() (*[]V0042ControllerPing, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Pings, true
}

// SetPings sets field value
func (o *V0042OpenapiPingArrayResp) SetPings(v []V0042ControllerPing) {
	o.Pings = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0042OpenapiPingArrayResp) GetMeta() V0042OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0042OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiPingArrayResp) GetMetaOk() (*V0042OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0042OpenapiPingArrayResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0042OpenapiMeta and assigns it to the Meta field.
func (o *V0042OpenapiPingArrayResp) SetMeta(v V0042OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0042OpenapiPingArrayResp) GetErrors() []V0042OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0042OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiPingArrayResp) GetErrorsOk() (*[]V0042OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0042OpenapiPingArrayResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0042OpenapiError and assigns it to the Errors field.
func (o *V0042OpenapiPingArrayResp) SetErrors(v []V0042OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0042OpenapiPingArrayResp) GetWarnings() []V0042OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0042OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042OpenapiPingArrayResp) GetWarningsOk() (*[]V0042OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0042OpenapiPingArrayResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0042OpenapiWarning and assigns it to the Warnings field.
func (o *V0042OpenapiPingArrayResp) SetWarnings(v []V0042OpenapiWarning) {
	o.Warnings = &v
}

func (o V0042OpenapiPingArrayResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pings"] = o.Pings
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0042OpenapiPingArrayResp struct {
	value *V0042OpenapiPingArrayResp
	isSet bool
}

func (v NullableV0042OpenapiPingArrayResp) Get() *V0042OpenapiPingArrayResp {
	return v.value
}

func (v *NullableV0042OpenapiPingArrayResp) Set(val *V0042OpenapiPingArrayResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042OpenapiPingArrayResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042OpenapiPingArrayResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042OpenapiPingArrayResp(val *V0042OpenapiPingArrayResp) *NullableV0042OpenapiPingArrayResp {
	return &NullableV0042OpenapiPingArrayResp{value: val, isSet: true}
}

func (v NullableV0042OpenapiPingArrayResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042OpenapiPingArrayResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


