/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiJobInfoRespPower struct for V0041OpenapiJobInfoRespPower
type V0041OpenapiJobInfoRespPower struct {
	// Deprecated
	Flags *[]interface{} `json:"flags,omitempty"`
}

// NewV0041OpenapiJobInfoRespPower instantiates a new V0041OpenapiJobInfoRespPower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiJobInfoRespPower() *V0041OpenapiJobInfoRespPower {
	this := V0041OpenapiJobInfoRespPower{}
	return &this
}

// NewV0041OpenapiJobInfoRespPowerWithDefaults instantiates a new V0041OpenapiJobInfoRespPower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiJobInfoRespPowerWithDefaults() *V0041OpenapiJobInfoRespPower {
	this := V0041OpenapiJobInfoRespPower{}
	return &this
}

// GetFlags returns the Flags field value if set, zero value otherwise.
// Deprecated
func (o *V0041OpenapiJobInfoRespPower) GetFlags() []interface{} {
	if o == nil || o.Flags == nil {
		var ret []interface{}
		return ret
	}
	return *o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0041OpenapiJobInfoRespPower) GetFlagsOk() (*[]interface{}, bool) {
	if o == nil || o.Flags == nil {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespPower) HasFlags() bool {
	if o != nil && o.Flags != nil {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []interface{} and assigns it to the Flags field.
// Deprecated
func (o *V0041OpenapiJobInfoRespPower) SetFlags(v []interface{}) {
	o.Flags = &v
}

func (o V0041OpenapiJobInfoRespPower) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Flags != nil {
		toSerialize["flags"] = o.Flags
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiJobInfoRespPower struct {
	value *V0041OpenapiJobInfoRespPower
	isSet bool
}

func (v NullableV0041OpenapiJobInfoRespPower) Get() *V0041OpenapiJobInfoRespPower {
	return v.value
}

func (v *NullableV0041OpenapiJobInfoRespPower) Set(val *V0041OpenapiJobInfoRespPower) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiJobInfoRespPower) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiJobInfoRespPower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiJobInfoRespPower(val *V0041OpenapiJobInfoRespPower) *NullableV0041OpenapiJobInfoRespPower {
	return &NullableV0041OpenapiJobInfoRespPower{value: val, isSet: true}
}

func (v NullableV0041OpenapiJobInfoRespPower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiJobInfoRespPower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


