/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiInstancesResp struct for V0041OpenapiInstancesResp
type V0041OpenapiInstancesResp struct {
	// instances
	Instances []V0041OpenapiSlurmdbdConfigRespInstances `json:"instances"`
	Meta *InlineResponse200Meta `json:"meta,omitempty"`
	// Query errors
	Errors *[]InlineResponse200Errors `json:"errors,omitempty"`
	// Query warnings
	Warnings *[]InlineResponse200Warnings `json:"warnings,omitempty"`
}

// NewV0041OpenapiInstancesResp instantiates a new V0041OpenapiInstancesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiInstancesResp(instances []V0041OpenapiSlurmdbdConfigRespInstances) *V0041OpenapiInstancesResp {
	this := V0041OpenapiInstancesResp{}
	this.Instances = instances
	return &this
}

// NewV0041OpenapiInstancesRespWithDefaults instantiates a new V0041OpenapiInstancesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiInstancesRespWithDefaults() *V0041OpenapiInstancesResp {
	this := V0041OpenapiInstancesResp{}
	return &this
}

// GetInstances returns the Instances field value
func (o *V0041OpenapiInstancesResp) GetInstances() []V0041OpenapiSlurmdbdConfigRespInstances {
	if o == nil {
		var ret []V0041OpenapiSlurmdbdConfigRespInstances
		return ret
	}

	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value
// and a boolean to check if the value has been set.
func (o *V0041OpenapiInstancesResp) GetInstancesOk() (*[]V0041OpenapiSlurmdbdConfigRespInstances, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Instances, true
}

// SetInstances sets field value
func (o *V0041OpenapiInstancesResp) SetInstances(v []V0041OpenapiSlurmdbdConfigRespInstances) {
	o.Instances = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0041OpenapiInstancesResp) GetMeta() InlineResponse200Meta {
	if o == nil || o.Meta == nil {
		var ret InlineResponse200Meta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiInstancesResp) GetMetaOk() (*InlineResponse200Meta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0041OpenapiInstancesResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given InlineResponse200Meta and assigns it to the Meta field.
func (o *V0041OpenapiInstancesResp) SetMeta(v InlineResponse200Meta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0041OpenapiInstancesResp) GetErrors() []InlineResponse200Errors {
	if o == nil || o.Errors == nil {
		var ret []InlineResponse200Errors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiInstancesResp) GetErrorsOk() (*[]InlineResponse200Errors, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0041OpenapiInstancesResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []InlineResponse200Errors and assigns it to the Errors field.
func (o *V0041OpenapiInstancesResp) SetErrors(v []InlineResponse200Errors) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0041OpenapiInstancesResp) GetWarnings() []InlineResponse200Warnings {
	if o == nil || o.Warnings == nil {
		var ret []InlineResponse200Warnings
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiInstancesResp) GetWarningsOk() (*[]InlineResponse200Warnings, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0041OpenapiInstancesResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []InlineResponse200Warnings and assigns it to the Warnings field.
func (o *V0041OpenapiInstancesResp) SetWarnings(v []InlineResponse200Warnings) {
	o.Warnings = &v
}

func (o V0041OpenapiInstancesResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["instances"] = o.Instances
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiInstancesResp struct {
	value *V0041OpenapiInstancesResp
	isSet bool
}

func (v NullableV0041OpenapiInstancesResp) Get() *V0041OpenapiInstancesResp {
	return v.value
}

func (v *NullableV0041OpenapiInstancesResp) Set(val *V0041OpenapiInstancesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiInstancesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiInstancesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiInstancesResp(val *V0041OpenapiInstancesResp) *NullableV0041OpenapiInstancesResp {
	return &NullableV0041OpenapiInstancesResp{value: val, isSet: true}
}

func (v NullableV0041OpenapiInstancesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiInstancesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


