/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043Instance struct for V0043Instance
type V0043Instance struct {
	// Cluster name
	Cluster *string `json:"cluster,omitempty"`
	// Arbitrary string used for node filtering if extra constraints are enabled
	Extra *string `json:"extra,omitempty"`
	// Cloud instance ID
	InstanceId *string `json:"instance_id,omitempty"`
	// Cloud instance type
	InstanceType *string `json:"instance_type,omitempty"`
	// NodeName
	NodeName *string `json:"node_name,omitempty"`
	Time *V0043InstanceTime `json:"time,omitempty"`
}

// NewV0043Instance instantiates a new V0043Instance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043Instance() *V0043Instance {
	this := V0043Instance{}
	return &this
}

// NewV0043InstanceWithDefaults instantiates a new V0043Instance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043InstanceWithDefaults() *V0043Instance {
	this := V0043Instance{}
	return &this
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *V0043Instance) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *V0043Instance) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *V0043Instance) SetCluster(v string) {
	o.Cluster = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *V0043Instance) GetExtra() string {
	if o == nil || o.Extra == nil {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetExtraOk() (*string, bool) {
	if o == nil || o.Extra == nil {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *V0043Instance) HasExtra() bool {
	if o != nil && o.Extra != nil {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *V0043Instance) SetExtra(v string) {
	o.Extra = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *V0043Instance) GetInstanceId() string {
	if o == nil || o.InstanceId == nil {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetInstanceIdOk() (*string, bool) {
	if o == nil || o.InstanceId == nil {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *V0043Instance) HasInstanceId() bool {
	if o != nil && o.InstanceId != nil {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *V0043Instance) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *V0043Instance) GetInstanceType() string {
	if o == nil || o.InstanceType == nil {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetInstanceTypeOk() (*string, bool) {
	if o == nil || o.InstanceType == nil {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *V0043Instance) HasInstanceType() bool {
	if o != nil && o.InstanceType != nil {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *V0043Instance) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetNodeName returns the NodeName field value if set, zero value otherwise.
func (o *V0043Instance) GetNodeName() string {
	if o == nil || o.NodeName == nil {
		var ret string
		return ret
	}
	return *o.NodeName
}

// GetNodeNameOk returns a tuple with the NodeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetNodeNameOk() (*string, bool) {
	if o == nil || o.NodeName == nil {
		return nil, false
	}
	return o.NodeName, true
}

// HasNodeName returns a boolean if a field has been set.
func (o *V0043Instance) HasNodeName() bool {
	if o != nil && o.NodeName != nil {
		return true
	}

	return false
}

// SetNodeName gets a reference to the given string and assigns it to the NodeName field.
func (o *V0043Instance) SetNodeName(v string) {
	o.NodeName = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0043Instance) GetTime() V0043InstanceTime {
	if o == nil || o.Time == nil {
		var ret V0043InstanceTime
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043Instance) GetTimeOk() (*V0043InstanceTime, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0043Instance) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given V0043InstanceTime and assigns it to the Time field.
func (o *V0043Instance) SetTime(v V0043InstanceTime) {
	o.Time = &v
}

func (o V0043Instance) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.Extra != nil {
		toSerialize["extra"] = o.Extra
	}
	if o.InstanceId != nil {
		toSerialize["instance_id"] = o.InstanceId
	}
	if o.InstanceType != nil {
		toSerialize["instance_type"] = o.InstanceType
	}
	if o.NodeName != nil {
		toSerialize["node_name"] = o.NodeName
	}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	return json.Marshal(toSerialize)
}

type NullableV0043Instance struct {
	value *V0043Instance
	isSet bool
}

func (v NullableV0043Instance) Get() *V0043Instance {
	return v.value
}

func (v *NullableV0043Instance) Set(val *V0043Instance) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043Instance) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043Instance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043Instance(val *V0043Instance) *NullableV0043Instance {
	return &NullableV0043Instance{value: val, isSet: true}
}

func (v NullableV0043Instance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043Instance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


