/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// SlurmdbV0041UsersAssociationAssociationCondition Filters to select associations for users
type SlurmdbV0041UsersAssociationAssociationCondition struct {
	// CSV accounts list
	Accounts *[]string `json:"accounts,omitempty"`
	Association *SlurmdbV0041UsersAssociationAssociationConditionAssociation `json:"association,omitempty"`
	// CSV clusters list
	Clusters *[]string `json:"clusters,omitempty"`
	// CSV partitions list
	Partitions *[]string `json:"partitions,omitempty"`
	// CSV users list
	Users []string `json:"users"`
	// CSV WCKeys list
	Wckeys *[]string `json:"wckeys,omitempty"`
}

// NewSlurmdbV0041UsersAssociationAssociationCondition instantiates a new SlurmdbV0041UsersAssociationAssociationCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041UsersAssociationAssociationCondition(users []string) *SlurmdbV0041UsersAssociationAssociationCondition {
	this := SlurmdbV0041UsersAssociationAssociationCondition{}
	this.Users = users
	return &this
}

// NewSlurmdbV0041UsersAssociationAssociationConditionWithDefaults instantiates a new SlurmdbV0041UsersAssociationAssociationCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041UsersAssociationAssociationConditionWithDefaults() *SlurmdbV0041UsersAssociationAssociationCondition {
	this := SlurmdbV0041UsersAssociationAssociationCondition{}
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetAccounts() []string {
	if o == nil || o.Accounts == nil {
		var ret []string
		return ret
	}
	return *o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetAccountsOk() (*[]string, bool) {
	if o == nil || o.Accounts == nil {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) HasAccounts() bool {
	if o != nil && o.Accounts != nil {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []string and assigns it to the Accounts field.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetAccounts(v []string) {
	o.Accounts = &v
}

// GetAssociation returns the Association field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetAssociation() SlurmdbV0041UsersAssociationAssociationConditionAssociation {
	if o == nil || o.Association == nil {
		var ret SlurmdbV0041UsersAssociationAssociationConditionAssociation
		return ret
	}
	return *o.Association
}

// GetAssociationOk returns a tuple with the Association field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetAssociationOk() (*SlurmdbV0041UsersAssociationAssociationConditionAssociation, bool) {
	if o == nil || o.Association == nil {
		return nil, false
	}
	return o.Association, true
}

// HasAssociation returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) HasAssociation() bool {
	if o != nil && o.Association != nil {
		return true
	}

	return false
}

// SetAssociation gets a reference to the given SlurmdbV0041UsersAssociationAssociationConditionAssociation and assigns it to the Association field.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetAssociation(v SlurmdbV0041UsersAssociationAssociationConditionAssociation) {
	o.Association = &v
}

// GetClusters returns the Clusters field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetClusters() []string {
	if o == nil || o.Clusters == nil {
		var ret []string
		return ret
	}
	return *o.Clusters
}

// GetClustersOk returns a tuple with the Clusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetClustersOk() (*[]string, bool) {
	if o == nil || o.Clusters == nil {
		return nil, false
	}
	return o.Clusters, true
}

// HasClusters returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) HasClusters() bool {
	if o != nil && o.Clusters != nil {
		return true
	}

	return false
}

// SetClusters gets a reference to the given []string and assigns it to the Clusters field.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetClusters(v []string) {
	o.Clusters = &v
}

// GetPartitions returns the Partitions field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetPartitions() []string {
	if o == nil || o.Partitions == nil {
		var ret []string
		return ret
	}
	return *o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetPartitionsOk() (*[]string, bool) {
	if o == nil || o.Partitions == nil {
		return nil, false
	}
	return o.Partitions, true
}

// HasPartitions returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) HasPartitions() bool {
	if o != nil && o.Partitions != nil {
		return true
	}

	return false
}

// SetPartitions gets a reference to the given []string and assigns it to the Partitions field.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetPartitions(v []string) {
	o.Partitions = &v
}

// GetUsers returns the Users field value
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetUsersOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Users, true
}

// SetUsers sets field value
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetUsers(v []string) {
	o.Users = v
}

// GetWckeys returns the Wckeys field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetWckeys() []string {
	if o == nil || o.Wckeys == nil {
		var ret []string
		return ret
	}
	return *o.Wckeys
}

// GetWckeysOk returns a tuple with the Wckeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) GetWckeysOk() (*[]string, bool) {
	if o == nil || o.Wckeys == nil {
		return nil, false
	}
	return o.Wckeys, true
}

// HasWckeys returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) HasWckeys() bool {
	if o != nil && o.Wckeys != nil {
		return true
	}

	return false
}

// SetWckeys gets a reference to the given []string and assigns it to the Wckeys field.
func (o *SlurmdbV0041UsersAssociationAssociationCondition) SetWckeys(v []string) {
	o.Wckeys = &v
}

func (o SlurmdbV0041UsersAssociationAssociationCondition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Accounts != nil {
		toSerialize["accounts"] = o.Accounts
	}
	if o.Association != nil {
		toSerialize["association"] = o.Association
	}
	if o.Clusters != nil {
		toSerialize["clusters"] = o.Clusters
	}
	if o.Partitions != nil {
		toSerialize["partitions"] = o.Partitions
	}
	if true {
		toSerialize["users"] = o.Users
	}
	if o.Wckeys != nil {
		toSerialize["wckeys"] = o.Wckeys
	}
	return json.Marshal(toSerialize)
}

type NullableSlurmdbV0041UsersAssociationAssociationCondition struct {
	value *SlurmdbV0041UsersAssociationAssociationCondition
	isSet bool
}

func (v NullableSlurmdbV0041UsersAssociationAssociationCondition) Get() *SlurmdbV0041UsersAssociationAssociationCondition {
	return v.value
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationCondition) Set(val *SlurmdbV0041UsersAssociationAssociationCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041UsersAssociationAssociationCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041UsersAssociationAssociationCondition(val *SlurmdbV0041UsersAssociationAssociationCondition) *NullableSlurmdbV0041UsersAssociationAssociationCondition {
	return &NullableSlurmdbV0041UsersAssociationAssociationCondition{value: val, isSet: true}
}

func (v NullableSlurmdbV0041UsersAssociationAssociationCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


