/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042JobArrayLimitsMax struct for V0042JobArrayLimitsMax
type V0042JobArrayLimitsMax struct {
	Running *V0042JobArrayLimitsMaxRunning `json:"running,omitempty"`
}

// NewV0042JobArrayLimitsMax instantiates a new V0042JobArrayLimitsMax object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042JobArrayLimitsMax() *V0042JobArrayLimitsMax {
	this := V0042JobArrayLimitsMax{}
	return &this
}

// NewV0042JobArrayLimitsMaxWithDefaults instantiates a new V0042JobArrayLimitsMax object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042JobArrayLimitsMaxWithDefaults() *V0042JobArrayLimitsMax {
	this := V0042JobArrayLimitsMax{}
	return &this
}

// GetRunning returns the Running field value if set, zero value otherwise.
func (o *V0042JobArrayLimitsMax) GetRunning() V0042JobArrayLimitsMaxRunning {
	if o == nil || o.Running == nil {
		var ret V0042JobArrayLimitsMaxRunning
		return ret
	}
	return *o.Running
}

// GetRunningOk returns a tuple with the Running field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042JobArrayLimitsMax) GetRunningOk() (*V0042JobArrayLimitsMaxRunning, bool) {
	if o == nil || o.Running == nil {
		return nil, false
	}
	return o.Running, true
}

// HasRunning returns a boolean if a field has been set.
func (o *V0042JobArrayLimitsMax) HasRunning() bool {
	if o != nil && o.Running != nil {
		return true
	}

	return false
}

// SetRunning gets a reference to the given V0042JobArrayLimitsMaxRunning and assigns it to the Running field.
func (o *V0042JobArrayLimitsMax) SetRunning(v V0042JobArrayLimitsMaxRunning) {
	o.Running = &v
}

func (o V0042JobArrayLimitsMax) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Running != nil {
		toSerialize["running"] = o.Running
	}
	return json.Marshal(toSerialize)
}

type NullableV0042JobArrayLimitsMax struct {
	value *V0042JobArrayLimitsMax
	isSet bool
}

func (v NullableV0042JobArrayLimitsMax) Get() *V0042JobArrayLimitsMax {
	return v.value
}

func (v *NullableV0042JobArrayLimitsMax) Set(val *V0042JobArrayLimitsMax) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042JobArrayLimitsMax) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042JobArrayLimitsMax) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042JobArrayLimitsMax(val *V0042JobArrayLimitsMax) *NullableV0042JobArrayLimitsMax {
	return &NullableV0042JobArrayLimitsMax{value: val, isSet: true}
}

func (v NullableV0042JobArrayLimitsMax) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042JobArrayLimitsMax) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


