/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer struct for V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer
type V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer struct {
	// MaxTRESMinsPerJob
	Job *[]SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres `json:"job,omitempty"`
}

// NewV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer instantiates a new V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer() *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer {
	this := V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer{}
	return &this
}

// NewV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPerWithDefaults instantiates a new V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPerWithDefaults() *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer {
	this := V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer{}
	return &this
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) GetJob() []SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres {
	if o == nil || o.Job == nil {
		var ret []SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) GetJobOk() (*[]SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given []SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres and assigns it to the Job field.
func (o *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) SetJob(v []SlurmdbV0041UsersAssociationAssociationConditionAssociationGrptres) {
	o.Job = &v
}

func (o V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer struct {
	value *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) Get() *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) Set(val *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer(val *V0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) *NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer {
	return &NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespMaxTresMinutesPer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


