/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiAssocsRemovedResp struct for V0041OpenapiAssocsRemovedResp
type V0041OpenapiAssocsRemovedResp struct {
	// removed_associations
	RemovedAssociations []string `json:"removed_associations"`
	Meta *InlineResponse200Meta `json:"meta,omitempty"`
	// Query errors
	Errors *[]InlineResponse200Errors `json:"errors,omitempty"`
	// Query warnings
	Warnings *[]InlineResponse200Warnings `json:"warnings,omitempty"`
}

// NewV0041OpenapiAssocsRemovedResp instantiates a new V0041OpenapiAssocsRemovedResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiAssocsRemovedResp(removedAssociations []string) *V0041OpenapiAssocsRemovedResp {
	this := V0041OpenapiAssocsRemovedResp{}
	this.RemovedAssociations = removedAssociations
	return &this
}

// NewV0041OpenapiAssocsRemovedRespWithDefaults instantiates a new V0041OpenapiAssocsRemovedResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiAssocsRemovedRespWithDefaults() *V0041OpenapiAssocsRemovedResp {
	this := V0041OpenapiAssocsRemovedResp{}
	return &this
}

// GetRemovedAssociations returns the RemovedAssociations field value
func (o *V0041OpenapiAssocsRemovedResp) GetRemovedAssociations() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemovedAssociations
}

// GetRemovedAssociationsOk returns a tuple with the RemovedAssociations field value
// and a boolean to check if the value has been set.
func (o *V0041OpenapiAssocsRemovedResp) GetRemovedAssociationsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RemovedAssociations, true
}

// SetRemovedAssociations sets field value
func (o *V0041OpenapiAssocsRemovedResp) SetRemovedAssociations(v []string) {
	o.RemovedAssociations = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0041OpenapiAssocsRemovedResp) GetMeta() InlineResponse200Meta {
	if o == nil || o.Meta == nil {
		var ret InlineResponse200Meta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiAssocsRemovedResp) GetMetaOk() (*InlineResponse200Meta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0041OpenapiAssocsRemovedResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given InlineResponse200Meta and assigns it to the Meta field.
func (o *V0041OpenapiAssocsRemovedResp) SetMeta(v InlineResponse200Meta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0041OpenapiAssocsRemovedResp) GetErrors() []InlineResponse200Errors {
	if o == nil || o.Errors == nil {
		var ret []InlineResponse200Errors
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiAssocsRemovedResp) GetErrorsOk() (*[]InlineResponse200Errors, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0041OpenapiAssocsRemovedResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []InlineResponse200Errors and assigns it to the Errors field.
func (o *V0041OpenapiAssocsRemovedResp) SetErrors(v []InlineResponse200Errors) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0041OpenapiAssocsRemovedResp) GetWarnings() []InlineResponse200Warnings {
	if o == nil || o.Warnings == nil {
		var ret []InlineResponse200Warnings
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiAssocsRemovedResp) GetWarningsOk() (*[]InlineResponse200Warnings, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0041OpenapiAssocsRemovedResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []InlineResponse200Warnings and assigns it to the Warnings field.
func (o *V0041OpenapiAssocsRemovedResp) SetWarnings(v []InlineResponse200Warnings) {
	o.Warnings = &v
}

func (o V0041OpenapiAssocsRemovedResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["removed_associations"] = o.RemovedAssociations
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiAssocsRemovedResp struct {
	value *V0041OpenapiAssocsRemovedResp
	isSet bool
}

func (v NullableV0041OpenapiAssocsRemovedResp) Get() *V0041OpenapiAssocsRemovedResp {
	return v.value
}

func (v *NullableV0041OpenapiAssocsRemovedResp) Set(val *V0041OpenapiAssocsRemovedResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiAssocsRemovedResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiAssocsRemovedResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiAssocsRemovedResp(val *V0041OpenapiAssocsRemovedResp) *NullableV0041OpenapiAssocsRemovedResp {
	return &NullableV0041OpenapiAssocsRemovedResp{value: val, isSet: true}
}

func (v NullableV0041OpenapiAssocsRemovedResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiAssocsRemovedResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


