/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042QosLimitsMaxTresMinutes struct for V0042QosLimitsMaxTresMinutes
type V0042QosLimitsMaxTresMinutes struct {
	Total *[]V0042Tres `json:"total,omitempty"`
	Per *V0042QosLimitsMaxTresMinutesPer `json:"per,omitempty"`
}

// NewV0042QosLimitsMaxTresMinutes instantiates a new V0042QosLimitsMaxTresMinutes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042QosLimitsMaxTresMinutes() *V0042QosLimitsMaxTresMinutes {
	this := V0042QosLimitsMaxTresMinutes{}
	return &this
}

// NewV0042QosLimitsMaxTresMinutesWithDefaults instantiates a new V0042QosLimitsMaxTresMinutes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042QosLimitsMaxTresMinutesWithDefaults() *V0042QosLimitsMaxTresMinutes {
	this := V0042QosLimitsMaxTresMinutes{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutes) GetTotal() []V0042Tres {
	if o == nil || o.Total == nil {
		var ret []V0042Tres
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutes) GetTotalOk() (*[]V0042Tres, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutes) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given []V0042Tres and assigns it to the Total field.
func (o *V0042QosLimitsMaxTresMinutes) SetTotal(v []V0042Tres) {
	o.Total = &v
}

// GetPer returns the Per field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxTresMinutes) GetPer() V0042QosLimitsMaxTresMinutesPer {
	if o == nil || o.Per == nil {
		var ret V0042QosLimitsMaxTresMinutesPer
		return ret
	}
	return *o.Per
}

// GetPerOk returns a tuple with the Per field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxTresMinutes) GetPerOk() (*V0042QosLimitsMaxTresMinutesPer, bool) {
	if o == nil || o.Per == nil {
		return nil, false
	}
	return o.Per, true
}

// HasPer returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxTresMinutes) HasPer() bool {
	if o != nil && o.Per != nil {
		return true
	}

	return false
}

// SetPer gets a reference to the given V0042QosLimitsMaxTresMinutesPer and assigns it to the Per field.
func (o *V0042QosLimitsMaxTresMinutes) SetPer(v V0042QosLimitsMaxTresMinutesPer) {
	o.Per = &v
}

func (o V0042QosLimitsMaxTresMinutes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	if o.Per != nil {
		toSerialize["per"] = o.Per
	}
	return json.Marshal(toSerialize)
}

type NullableV0042QosLimitsMaxTresMinutes struct {
	value *V0042QosLimitsMaxTresMinutes
	isSet bool
}

func (v NullableV0042QosLimitsMaxTresMinutes) Get() *V0042QosLimitsMaxTresMinutes {
	return v.value
}

func (v *NullableV0042QosLimitsMaxTresMinutes) Set(val *V0042QosLimitsMaxTresMinutes) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042QosLimitsMaxTresMinutes) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042QosLimitsMaxTresMinutes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042QosLimitsMaxTresMinutes(val *V0042QosLimitsMaxTresMinutes) *NullableV0042QosLimitsMaxTresMinutes {
	return &NullableV0042QosLimitsMaxTresMinutes{value: val, isSet: true}
}

func (v NullableV0042QosLimitsMaxTresMinutes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042QosLimitsMaxTresMinutes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


