/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	// HetJob description
	Hetjob *[]SlurmV0041JobSubmitJobs `json:"hetjob,omitempty"`
	Job *SlurmV0041JobSubmitJob `json:"job,omitempty"`
}

// NewInlineObject1 instantiates a new InlineObject1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject1() *InlineObject1 {
	this := InlineObject1{}
	return &this
}

// NewInlineObject1WithDefaults instantiates a new InlineObject1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject1WithDefaults() *InlineObject1 {
	this := InlineObject1{}
	return &this
}

// GetHetjob returns the Hetjob field value if set, zero value otherwise.
func (o *InlineObject1) GetHetjob() []SlurmV0041JobSubmitJobs {
	if o == nil || o.Hetjob == nil {
		var ret []SlurmV0041JobSubmitJobs
		return ret
	}
	return *o.Hetjob
}

// GetHetjobOk returns a tuple with the Hetjob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetHetjobOk() (*[]SlurmV0041JobSubmitJobs, bool) {
	if o == nil || o.Hetjob == nil {
		return nil, false
	}
	return o.Hetjob, true
}

// HasHetjob returns a boolean if a field has been set.
func (o *InlineObject1) HasHetjob() bool {
	if o != nil && o.Hetjob != nil {
		return true
	}

	return false
}

// SetHetjob gets a reference to the given []SlurmV0041JobSubmitJobs and assigns it to the Hetjob field.
func (o *InlineObject1) SetHetjob(v []SlurmV0041JobSubmitJobs) {
	o.Hetjob = &v
}

// GetJob returns the Job field value if set, zero value otherwise.
func (o *InlineObject1) GetJob() SlurmV0041JobSubmitJob {
	if o == nil || o.Job == nil {
		var ret SlurmV0041JobSubmitJob
		return ret
	}
	return *o.Job
}

// GetJobOk returns a tuple with the Job field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject1) GetJobOk() (*SlurmV0041JobSubmitJob, bool) {
	if o == nil || o.Job == nil {
		return nil, false
	}
	return o.Job, true
}

// HasJob returns a boolean if a field has been set.
func (o *InlineObject1) HasJob() bool {
	if o != nil && o.Job != nil {
		return true
	}

	return false
}

// SetJob gets a reference to the given SlurmV0041JobSubmitJob and assigns it to the Job field.
func (o *InlineObject1) SetJob(v SlurmV0041JobSubmitJob) {
	o.Job = &v
}

func (o InlineObject1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Hetjob != nil {
		toSerialize["hetjob"] = o.Hetjob
	}
	if o.Job != nil {
		toSerialize["job"] = o.Job
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject1 struct {
	value *InlineObject1
	isSet bool
}

func (v NullableInlineObject1) Get() *InlineObject1 {
	return v.value
}

func (v *NullableInlineObject1) Set(val *InlineObject1) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1(val *InlineObject1) *NullableInlineObject1 {
	return &NullableInlineObject1{value: val, isSet: true}
}

func (v NullableInlineObject1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


