/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042Node struct for V0042Node
type V0042Node struct {
	// Computer architecture
	Architecture *string `json:"architecture,omitempty"`
	// Alternate network path to be used for sbcast network traffic
	BurstbufferNetworkAddress *string `json:"burstbuffer_network_address,omitempty"`
	// Number of Baseboards in nodes with a baseboard controller
	Boards *int32 `json:"boards,omitempty"`
	BootTime *V0042Uint64NoValStruct `json:"boot_time,omitempty"`
	// Cluster name (only set in federated environments)
	ClusterName *string `json:"cluster_name,omitempty"`
	// Number of cores in a single physical processor socket
	Cores *int32 `json:"cores,omitempty"`
	// Number of cores reserved for system use
	SpecializedCores *int32 `json:"specialized_cores,omitempty"`
	// Default method for binding tasks to allocated CPUs
	CpuBinding *int32 `json:"cpu_binding,omitempty"`
	// CPU load as reported by the OS
	CpuLoad *int32 `json:"cpu_load,omitempty"`
	FreeMem *V0042Uint64NoValStruct `json:"free_mem,omitempty"`
	// Total CPUs, including cores and threads
	Cpus *int32 `json:"cpus,omitempty"`
	// Number of effective CPUs (excluding specialized CPUs)
	EffectiveCpus *int32 `json:"effective_cpus,omitempty"`
	// Abstract CPU IDs on this node reserved for exclusive use by slurmd and slurmstepd
	SpecializedCpus *string `json:"specialized_cpus,omitempty"`
	Energy *V0042AcctGatherEnergy `json:"energy,omitempty"`
	// Deprecated
	ExternalSensors *map[string]interface{} `json:"external_sensors,omitempty"`
	// Arbitrary string used for node filtering if extra constraints are enabled
	Extra *string `json:"extra,omitempty"`
	// Deprecated
	Power *map[string]interface{} `json:"power,omitempty"`
	Features *[]string `json:"features,omitempty"`
	ActiveFeatures *[]string `json:"active_features,omitempty"`
	// CPU cores reserved for jobs that also use a GPU
	GpuSpec *string `json:"gpu_spec,omitempty"`
	// Generic resources
	Gres *string `json:"gres,omitempty"`
	// Drained generic resources
	GresDrained *string `json:"gres_drained,omitempty"`
	// Generic resources currently in use
	GresUsed *string `json:"gres_used,omitempty"`
	// Cloud instance ID
	InstanceId *string `json:"instance_id,omitempty"`
	// Cloud instance type
	InstanceType *string `json:"instance_type,omitempty"`
	LastBusy *V0042Uint64NoValStruct `json:"last_busy,omitempty"`
	// Multi-Category Security label
	McsLabel *string `json:"mcs_label,omitempty"`
	// Combined memory limit, in MB, for Slurm compute node daemons
	SpecializedMemory *int64 `json:"specialized_memory,omitempty"`
	// NodeName
	Name *string `json:"name,omitempty"`
	NextStateAfterReboot *[]string `json:"next_state_after_reboot,omitempty"`
	// NodeAddr, used to establish a communication path
	Address *string `json:"address,omitempty"`
	// NodeHostname
	Hostname *string `json:"hostname,omitempty"`
	State *[]string `json:"state,omitempty"`
	// Operating system reported by the node
	OperatingSystem *string `json:"operating_system,omitempty"`
	// User allowed to run jobs on this node (unset if no restriction)
	Owner *string `json:"owner,omitempty"`
	Partitions *[]string `json:"partitions,omitempty"`
	// TCP port number of the slurmd
	Port *int32 `json:"port,omitempty"`
	// Total memory in MB on the node
	RealMemory *int64 `json:"real_memory,omitempty"`
	// Number of CPU cores per GPU restricted to GPU jobs
	ResCoresPerGpu *int32 `json:"res_cores_per_gpu,omitempty"`
	// Arbitrary comment
	Comment *string `json:"comment,omitempty"`
	// Describes why the node is in a \"DOWN\", \"DRAINED\", \"DRAINING\", \"FAILING\" or \"FAIL\" state
	Reason *string `json:"reason,omitempty"`
	ReasonChangedAt *V0042Uint64NoValStruct `json:"reason_changed_at,omitempty"`
	// User who set the reason
	ReasonSetByUser *string `json:"reason_set_by_user,omitempty"`
	ResumeAfter *V0042Uint64NoValStruct `json:"resume_after,omitempty"`
	// Name of reservation containing this node
	Reservation *string `json:"reservation,omitempty"`
	// Total memory in MB currently allocated for jobs
	AllocMemory *int64 `json:"alloc_memory,omitempty"`
	// Total number of CPUs currently allocated for jobs
	AllocCpus *int32 `json:"alloc_cpus,omitempty"`
	// Total number of idle CPUs
	AllocIdleCpus *int32 `json:"alloc_idle_cpus,omitempty"`
	// Trackable resources currently allocated for jobs
	TresUsed *string `json:"tres_used,omitempty"`
	// Ignored. Was weighted number of billable trackable resources allocated
	// Deprecated
	TresWeighted *float64 `json:"tres_weighted,omitempty"`
	SlurmdStartTime *V0042Uint64NoValStruct `json:"slurmd_start_time,omitempty"`
	// Number of physical processor sockets/chips on the node
	Sockets *int32 `json:"sockets,omitempty"`
	// Number of logical threads in a single physical core
	Threads *int32 `json:"threads,omitempty"`
	// Total size in MB of temporary disk storage in TmpFS
	TemporaryDisk *int32 `json:"temporary_disk,omitempty"`
	// Weight of the node for scheduling purposes
	Weight *int32 `json:"weight,omitempty"`
	// Configured trackable resources
	Tres *string `json:"tres,omitempty"`
	// Slurmd version
	Version *string `json:"version,omitempty"`
}

// NewV0042Node instantiates a new V0042Node object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042Node() *V0042Node {
	this := V0042Node{}
	return &this
}

// NewV0042NodeWithDefaults instantiates a new V0042Node object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042NodeWithDefaults() *V0042Node {
	this := V0042Node{}
	return &this
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *V0042Node) GetArchitecture() string {
	if o == nil || o.Architecture == nil {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetArchitectureOk() (*string, bool) {
	if o == nil || o.Architecture == nil {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *V0042Node) HasArchitecture() bool {
	if o != nil && o.Architecture != nil {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *V0042Node) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetBurstbufferNetworkAddress returns the BurstbufferNetworkAddress field value if set, zero value otherwise.
func (o *V0042Node) GetBurstbufferNetworkAddress() string {
	if o == nil || o.BurstbufferNetworkAddress == nil {
		var ret string
		return ret
	}
	return *o.BurstbufferNetworkAddress
}

// GetBurstbufferNetworkAddressOk returns a tuple with the BurstbufferNetworkAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetBurstbufferNetworkAddressOk() (*string, bool) {
	if o == nil || o.BurstbufferNetworkAddress == nil {
		return nil, false
	}
	return o.BurstbufferNetworkAddress, true
}

// HasBurstbufferNetworkAddress returns a boolean if a field has been set.
func (o *V0042Node) HasBurstbufferNetworkAddress() bool {
	if o != nil && o.BurstbufferNetworkAddress != nil {
		return true
	}

	return false
}

// SetBurstbufferNetworkAddress gets a reference to the given string and assigns it to the BurstbufferNetworkAddress field.
func (o *V0042Node) SetBurstbufferNetworkAddress(v string) {
	o.BurstbufferNetworkAddress = &v
}

// GetBoards returns the Boards field value if set, zero value otherwise.
func (o *V0042Node) GetBoards() int32 {
	if o == nil || o.Boards == nil {
		var ret int32
		return ret
	}
	return *o.Boards
}

// GetBoardsOk returns a tuple with the Boards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetBoardsOk() (*int32, bool) {
	if o == nil || o.Boards == nil {
		return nil, false
	}
	return o.Boards, true
}

// HasBoards returns a boolean if a field has been set.
func (o *V0042Node) HasBoards() bool {
	if o != nil && o.Boards != nil {
		return true
	}

	return false
}

// SetBoards gets a reference to the given int32 and assigns it to the Boards field.
func (o *V0042Node) SetBoards(v int32) {
	o.Boards = &v
}

// GetBootTime returns the BootTime field value if set, zero value otherwise.
func (o *V0042Node) GetBootTime() V0042Uint64NoValStruct {
	if o == nil || o.BootTime == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.BootTime
}

// GetBootTimeOk returns a tuple with the BootTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetBootTimeOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.BootTime == nil {
		return nil, false
	}
	return o.BootTime, true
}

// HasBootTime returns a boolean if a field has been set.
func (o *V0042Node) HasBootTime() bool {
	if o != nil && o.BootTime != nil {
		return true
	}

	return false
}

// SetBootTime gets a reference to the given V0042Uint64NoValStruct and assigns it to the BootTime field.
func (o *V0042Node) SetBootTime(v V0042Uint64NoValStruct) {
	o.BootTime = &v
}

// GetClusterName returns the ClusterName field value if set, zero value otherwise.
func (o *V0042Node) GetClusterName() string {
	if o == nil || o.ClusterName == nil {
		var ret string
		return ret
	}
	return *o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetClusterNameOk() (*string, bool) {
	if o == nil || o.ClusterName == nil {
		return nil, false
	}
	return o.ClusterName, true
}

// HasClusterName returns a boolean if a field has been set.
func (o *V0042Node) HasClusterName() bool {
	if o != nil && o.ClusterName != nil {
		return true
	}

	return false
}

// SetClusterName gets a reference to the given string and assigns it to the ClusterName field.
func (o *V0042Node) SetClusterName(v string) {
	o.ClusterName = &v
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *V0042Node) GetCores() int32 {
	if o == nil || o.Cores == nil {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetCoresOk() (*int32, bool) {
	if o == nil || o.Cores == nil {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *V0042Node) HasCores() bool {
	if o != nil && o.Cores != nil {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *V0042Node) SetCores(v int32) {
	o.Cores = &v
}

// GetSpecializedCores returns the SpecializedCores field value if set, zero value otherwise.
func (o *V0042Node) GetSpecializedCores() int32 {
	if o == nil || o.SpecializedCores == nil {
		var ret int32
		return ret
	}
	return *o.SpecializedCores
}

// GetSpecializedCoresOk returns a tuple with the SpecializedCores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetSpecializedCoresOk() (*int32, bool) {
	if o == nil || o.SpecializedCores == nil {
		return nil, false
	}
	return o.SpecializedCores, true
}

// HasSpecializedCores returns a boolean if a field has been set.
func (o *V0042Node) HasSpecializedCores() bool {
	if o != nil && o.SpecializedCores != nil {
		return true
	}

	return false
}

// SetSpecializedCores gets a reference to the given int32 and assigns it to the SpecializedCores field.
func (o *V0042Node) SetSpecializedCores(v int32) {
	o.SpecializedCores = &v
}

// GetCpuBinding returns the CpuBinding field value if set, zero value otherwise.
func (o *V0042Node) GetCpuBinding() int32 {
	if o == nil || o.CpuBinding == nil {
		var ret int32
		return ret
	}
	return *o.CpuBinding
}

// GetCpuBindingOk returns a tuple with the CpuBinding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetCpuBindingOk() (*int32, bool) {
	if o == nil || o.CpuBinding == nil {
		return nil, false
	}
	return o.CpuBinding, true
}

// HasCpuBinding returns a boolean if a field has been set.
func (o *V0042Node) HasCpuBinding() bool {
	if o != nil && o.CpuBinding != nil {
		return true
	}

	return false
}

// SetCpuBinding gets a reference to the given int32 and assigns it to the CpuBinding field.
func (o *V0042Node) SetCpuBinding(v int32) {
	o.CpuBinding = &v
}

// GetCpuLoad returns the CpuLoad field value if set, zero value otherwise.
func (o *V0042Node) GetCpuLoad() int32 {
	if o == nil || o.CpuLoad == nil {
		var ret int32
		return ret
	}
	return *o.CpuLoad
}

// GetCpuLoadOk returns a tuple with the CpuLoad field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetCpuLoadOk() (*int32, bool) {
	if o == nil || o.CpuLoad == nil {
		return nil, false
	}
	return o.CpuLoad, true
}

// HasCpuLoad returns a boolean if a field has been set.
func (o *V0042Node) HasCpuLoad() bool {
	if o != nil && o.CpuLoad != nil {
		return true
	}

	return false
}

// SetCpuLoad gets a reference to the given int32 and assigns it to the CpuLoad field.
func (o *V0042Node) SetCpuLoad(v int32) {
	o.CpuLoad = &v
}

// GetFreeMem returns the FreeMem field value if set, zero value otherwise.
func (o *V0042Node) GetFreeMem() V0042Uint64NoValStruct {
	if o == nil || o.FreeMem == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.FreeMem
}

// GetFreeMemOk returns a tuple with the FreeMem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetFreeMemOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.FreeMem == nil {
		return nil, false
	}
	return o.FreeMem, true
}

// HasFreeMem returns a boolean if a field has been set.
func (o *V0042Node) HasFreeMem() bool {
	if o != nil && o.FreeMem != nil {
		return true
	}

	return false
}

// SetFreeMem gets a reference to the given V0042Uint64NoValStruct and assigns it to the FreeMem field.
func (o *V0042Node) SetFreeMem(v V0042Uint64NoValStruct) {
	o.FreeMem = &v
}

// GetCpus returns the Cpus field value if set, zero value otherwise.
func (o *V0042Node) GetCpus() int32 {
	if o == nil || o.Cpus == nil {
		var ret int32
		return ret
	}
	return *o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetCpusOk() (*int32, bool) {
	if o == nil || o.Cpus == nil {
		return nil, false
	}
	return o.Cpus, true
}

// HasCpus returns a boolean if a field has been set.
func (o *V0042Node) HasCpus() bool {
	if o != nil && o.Cpus != nil {
		return true
	}

	return false
}

// SetCpus gets a reference to the given int32 and assigns it to the Cpus field.
func (o *V0042Node) SetCpus(v int32) {
	o.Cpus = &v
}

// GetEffectiveCpus returns the EffectiveCpus field value if set, zero value otherwise.
func (o *V0042Node) GetEffectiveCpus() int32 {
	if o == nil || o.EffectiveCpus == nil {
		var ret int32
		return ret
	}
	return *o.EffectiveCpus
}

// GetEffectiveCpusOk returns a tuple with the EffectiveCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetEffectiveCpusOk() (*int32, bool) {
	if o == nil || o.EffectiveCpus == nil {
		return nil, false
	}
	return o.EffectiveCpus, true
}

// HasEffectiveCpus returns a boolean if a field has been set.
func (o *V0042Node) HasEffectiveCpus() bool {
	if o != nil && o.EffectiveCpus != nil {
		return true
	}

	return false
}

// SetEffectiveCpus gets a reference to the given int32 and assigns it to the EffectiveCpus field.
func (o *V0042Node) SetEffectiveCpus(v int32) {
	o.EffectiveCpus = &v
}

// GetSpecializedCpus returns the SpecializedCpus field value if set, zero value otherwise.
func (o *V0042Node) GetSpecializedCpus() string {
	if o == nil || o.SpecializedCpus == nil {
		var ret string
		return ret
	}
	return *o.SpecializedCpus
}

// GetSpecializedCpusOk returns a tuple with the SpecializedCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetSpecializedCpusOk() (*string, bool) {
	if o == nil || o.SpecializedCpus == nil {
		return nil, false
	}
	return o.SpecializedCpus, true
}

// HasSpecializedCpus returns a boolean if a field has been set.
func (o *V0042Node) HasSpecializedCpus() bool {
	if o != nil && o.SpecializedCpus != nil {
		return true
	}

	return false
}

// SetSpecializedCpus gets a reference to the given string and assigns it to the SpecializedCpus field.
func (o *V0042Node) SetSpecializedCpus(v string) {
	o.SpecializedCpus = &v
}

// GetEnergy returns the Energy field value if set, zero value otherwise.
func (o *V0042Node) GetEnergy() V0042AcctGatherEnergy {
	if o == nil || o.Energy == nil {
		var ret V0042AcctGatherEnergy
		return ret
	}
	return *o.Energy
}

// GetEnergyOk returns a tuple with the Energy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetEnergyOk() (*V0042AcctGatherEnergy, bool) {
	if o == nil || o.Energy == nil {
		return nil, false
	}
	return o.Energy, true
}

// HasEnergy returns a boolean if a field has been set.
func (o *V0042Node) HasEnergy() bool {
	if o != nil && o.Energy != nil {
		return true
	}

	return false
}

// SetEnergy gets a reference to the given V0042AcctGatherEnergy and assigns it to the Energy field.
func (o *V0042Node) SetEnergy(v V0042AcctGatherEnergy) {
	o.Energy = &v
}

// GetExternalSensors returns the ExternalSensors field value if set, zero value otherwise.
// Deprecated
func (o *V0042Node) GetExternalSensors() map[string]interface{} {
	if o == nil || o.ExternalSensors == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.ExternalSensors
}

// GetExternalSensorsOk returns a tuple with the ExternalSensors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0042Node) GetExternalSensorsOk() (*map[string]interface{}, bool) {
	if o == nil || o.ExternalSensors == nil {
		return nil, false
	}
	return o.ExternalSensors, true
}

// HasExternalSensors returns a boolean if a field has been set.
func (o *V0042Node) HasExternalSensors() bool {
	if o != nil && o.ExternalSensors != nil {
		return true
	}

	return false
}

// SetExternalSensors gets a reference to the given map[string]interface{} and assigns it to the ExternalSensors field.
// Deprecated
func (o *V0042Node) SetExternalSensors(v map[string]interface{}) {
	o.ExternalSensors = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *V0042Node) GetExtra() string {
	if o == nil || o.Extra == nil {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetExtraOk() (*string, bool) {
	if o == nil || o.Extra == nil {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *V0042Node) HasExtra() bool {
	if o != nil && o.Extra != nil {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *V0042Node) SetExtra(v string) {
	o.Extra = &v
}

// GetPower returns the Power field value if set, zero value otherwise.
// Deprecated
func (o *V0042Node) GetPower() map[string]interface{} {
	if o == nil || o.Power == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Power
}

// GetPowerOk returns a tuple with the Power field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0042Node) GetPowerOk() (*map[string]interface{}, bool) {
	if o == nil || o.Power == nil {
		return nil, false
	}
	return o.Power, true
}

// HasPower returns a boolean if a field has been set.
func (o *V0042Node) HasPower() bool {
	if o != nil && o.Power != nil {
		return true
	}

	return false
}

// SetPower gets a reference to the given map[string]interface{} and assigns it to the Power field.
// Deprecated
func (o *V0042Node) SetPower(v map[string]interface{}) {
	o.Power = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *V0042Node) GetFeatures() []string {
	if o == nil || o.Features == nil {
		var ret []string
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetFeaturesOk() (*[]string, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *V0042Node) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *V0042Node) SetFeatures(v []string) {
	o.Features = &v
}

// GetActiveFeatures returns the ActiveFeatures field value if set, zero value otherwise.
func (o *V0042Node) GetActiveFeatures() []string {
	if o == nil || o.ActiveFeatures == nil {
		var ret []string
		return ret
	}
	return *o.ActiveFeatures
}

// GetActiveFeaturesOk returns a tuple with the ActiveFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetActiveFeaturesOk() (*[]string, bool) {
	if o == nil || o.ActiveFeatures == nil {
		return nil, false
	}
	return o.ActiveFeatures, true
}

// HasActiveFeatures returns a boolean if a field has been set.
func (o *V0042Node) HasActiveFeatures() bool {
	if o != nil && o.ActiveFeatures != nil {
		return true
	}

	return false
}

// SetActiveFeatures gets a reference to the given []string and assigns it to the ActiveFeatures field.
func (o *V0042Node) SetActiveFeatures(v []string) {
	o.ActiveFeatures = &v
}

// GetGpuSpec returns the GpuSpec field value if set, zero value otherwise.
func (o *V0042Node) GetGpuSpec() string {
	if o == nil || o.GpuSpec == nil {
		var ret string
		return ret
	}
	return *o.GpuSpec
}

// GetGpuSpecOk returns a tuple with the GpuSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetGpuSpecOk() (*string, bool) {
	if o == nil || o.GpuSpec == nil {
		return nil, false
	}
	return o.GpuSpec, true
}

// HasGpuSpec returns a boolean if a field has been set.
func (o *V0042Node) HasGpuSpec() bool {
	if o != nil && o.GpuSpec != nil {
		return true
	}

	return false
}

// SetGpuSpec gets a reference to the given string and assigns it to the GpuSpec field.
func (o *V0042Node) SetGpuSpec(v string) {
	o.GpuSpec = &v
}

// GetGres returns the Gres field value if set, zero value otherwise.
func (o *V0042Node) GetGres() string {
	if o == nil || o.Gres == nil {
		var ret string
		return ret
	}
	return *o.Gres
}

// GetGresOk returns a tuple with the Gres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetGresOk() (*string, bool) {
	if o == nil || o.Gres == nil {
		return nil, false
	}
	return o.Gres, true
}

// HasGres returns a boolean if a field has been set.
func (o *V0042Node) HasGres() bool {
	if o != nil && o.Gres != nil {
		return true
	}

	return false
}

// SetGres gets a reference to the given string and assigns it to the Gres field.
func (o *V0042Node) SetGres(v string) {
	o.Gres = &v
}

// GetGresDrained returns the GresDrained field value if set, zero value otherwise.
func (o *V0042Node) GetGresDrained() string {
	if o == nil || o.GresDrained == nil {
		var ret string
		return ret
	}
	return *o.GresDrained
}

// GetGresDrainedOk returns a tuple with the GresDrained field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetGresDrainedOk() (*string, bool) {
	if o == nil || o.GresDrained == nil {
		return nil, false
	}
	return o.GresDrained, true
}

// HasGresDrained returns a boolean if a field has been set.
func (o *V0042Node) HasGresDrained() bool {
	if o != nil && o.GresDrained != nil {
		return true
	}

	return false
}

// SetGresDrained gets a reference to the given string and assigns it to the GresDrained field.
func (o *V0042Node) SetGresDrained(v string) {
	o.GresDrained = &v
}

// GetGresUsed returns the GresUsed field value if set, zero value otherwise.
func (o *V0042Node) GetGresUsed() string {
	if o == nil || o.GresUsed == nil {
		var ret string
		return ret
	}
	return *o.GresUsed
}

// GetGresUsedOk returns a tuple with the GresUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetGresUsedOk() (*string, bool) {
	if o == nil || o.GresUsed == nil {
		return nil, false
	}
	return o.GresUsed, true
}

// HasGresUsed returns a boolean if a field has been set.
func (o *V0042Node) HasGresUsed() bool {
	if o != nil && o.GresUsed != nil {
		return true
	}

	return false
}

// SetGresUsed gets a reference to the given string and assigns it to the GresUsed field.
func (o *V0042Node) SetGresUsed(v string) {
	o.GresUsed = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *V0042Node) GetInstanceId() string {
	if o == nil || o.InstanceId == nil {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetInstanceIdOk() (*string, bool) {
	if o == nil || o.InstanceId == nil {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *V0042Node) HasInstanceId() bool {
	if o != nil && o.InstanceId != nil {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *V0042Node) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *V0042Node) GetInstanceType() string {
	if o == nil || o.InstanceType == nil {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetInstanceTypeOk() (*string, bool) {
	if o == nil || o.InstanceType == nil {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *V0042Node) HasInstanceType() bool {
	if o != nil && o.InstanceType != nil {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *V0042Node) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetLastBusy returns the LastBusy field value if set, zero value otherwise.
func (o *V0042Node) GetLastBusy() V0042Uint64NoValStruct {
	if o == nil || o.LastBusy == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.LastBusy
}

// GetLastBusyOk returns a tuple with the LastBusy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetLastBusyOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.LastBusy == nil {
		return nil, false
	}
	return o.LastBusy, true
}

// HasLastBusy returns a boolean if a field has been set.
func (o *V0042Node) HasLastBusy() bool {
	if o != nil && o.LastBusy != nil {
		return true
	}

	return false
}

// SetLastBusy gets a reference to the given V0042Uint64NoValStruct and assigns it to the LastBusy field.
func (o *V0042Node) SetLastBusy(v V0042Uint64NoValStruct) {
	o.LastBusy = &v
}

// GetMcsLabel returns the McsLabel field value if set, zero value otherwise.
func (o *V0042Node) GetMcsLabel() string {
	if o == nil || o.McsLabel == nil {
		var ret string
		return ret
	}
	return *o.McsLabel
}

// GetMcsLabelOk returns a tuple with the McsLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetMcsLabelOk() (*string, bool) {
	if o == nil || o.McsLabel == nil {
		return nil, false
	}
	return o.McsLabel, true
}

// HasMcsLabel returns a boolean if a field has been set.
func (o *V0042Node) HasMcsLabel() bool {
	if o != nil && o.McsLabel != nil {
		return true
	}

	return false
}

// SetMcsLabel gets a reference to the given string and assigns it to the McsLabel field.
func (o *V0042Node) SetMcsLabel(v string) {
	o.McsLabel = &v
}

// GetSpecializedMemory returns the SpecializedMemory field value if set, zero value otherwise.
func (o *V0042Node) GetSpecializedMemory() int64 {
	if o == nil || o.SpecializedMemory == nil {
		var ret int64
		return ret
	}
	return *o.SpecializedMemory
}

// GetSpecializedMemoryOk returns a tuple with the SpecializedMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetSpecializedMemoryOk() (*int64, bool) {
	if o == nil || o.SpecializedMemory == nil {
		return nil, false
	}
	return o.SpecializedMemory, true
}

// HasSpecializedMemory returns a boolean if a field has been set.
func (o *V0042Node) HasSpecializedMemory() bool {
	if o != nil && o.SpecializedMemory != nil {
		return true
	}

	return false
}

// SetSpecializedMemory gets a reference to the given int64 and assigns it to the SpecializedMemory field.
func (o *V0042Node) SetSpecializedMemory(v int64) {
	o.SpecializedMemory = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V0042Node) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V0042Node) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V0042Node) SetName(v string) {
	o.Name = &v
}

// GetNextStateAfterReboot returns the NextStateAfterReboot field value if set, zero value otherwise.
func (o *V0042Node) GetNextStateAfterReboot() []string {
	if o == nil || o.NextStateAfterReboot == nil {
		var ret []string
		return ret
	}
	return *o.NextStateAfterReboot
}

// GetNextStateAfterRebootOk returns a tuple with the NextStateAfterReboot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetNextStateAfterRebootOk() (*[]string, bool) {
	if o == nil || o.NextStateAfterReboot == nil {
		return nil, false
	}
	return o.NextStateAfterReboot, true
}

// HasNextStateAfterReboot returns a boolean if a field has been set.
func (o *V0042Node) HasNextStateAfterReboot() bool {
	if o != nil && o.NextStateAfterReboot != nil {
		return true
	}

	return false
}

// SetNextStateAfterReboot gets a reference to the given []string and assigns it to the NextStateAfterReboot field.
func (o *V0042Node) SetNextStateAfterReboot(v []string) {
	o.NextStateAfterReboot = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *V0042Node) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *V0042Node) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *V0042Node) SetAddress(v string) {
	o.Address = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *V0042Node) GetHostname() string {
	if o == nil || o.Hostname == nil {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetHostnameOk() (*string, bool) {
	if o == nil || o.Hostname == nil {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *V0042Node) HasHostname() bool {
	if o != nil && o.Hostname != nil {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *V0042Node) SetHostname(v string) {
	o.Hostname = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V0042Node) GetState() []string {
	if o == nil || o.State == nil {
		var ret []string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetStateOk() (*[]string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V0042Node) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *V0042Node) SetState(v []string) {
	o.State = &v
}

// GetOperatingSystem returns the OperatingSystem field value if set, zero value otherwise.
func (o *V0042Node) GetOperatingSystem() string {
	if o == nil || o.OperatingSystem == nil {
		var ret string
		return ret
	}
	return *o.OperatingSystem
}

// GetOperatingSystemOk returns a tuple with the OperatingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetOperatingSystemOk() (*string, bool) {
	if o == nil || o.OperatingSystem == nil {
		return nil, false
	}
	return o.OperatingSystem, true
}

// HasOperatingSystem returns a boolean if a field has been set.
func (o *V0042Node) HasOperatingSystem() bool {
	if o != nil && o.OperatingSystem != nil {
		return true
	}

	return false
}

// SetOperatingSystem gets a reference to the given string and assigns it to the OperatingSystem field.
func (o *V0042Node) SetOperatingSystem(v string) {
	o.OperatingSystem = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *V0042Node) GetOwner() string {
	if o == nil || o.Owner == nil {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetOwnerOk() (*string, bool) {
	if o == nil || o.Owner == nil {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *V0042Node) HasOwner() bool {
	if o != nil && o.Owner != nil {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *V0042Node) SetOwner(v string) {
	o.Owner = &v
}

// GetPartitions returns the Partitions field value if set, zero value otherwise.
func (o *V0042Node) GetPartitions() []string {
	if o == nil || o.Partitions == nil {
		var ret []string
		return ret
	}
	return *o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetPartitionsOk() (*[]string, bool) {
	if o == nil || o.Partitions == nil {
		return nil, false
	}
	return o.Partitions, true
}

// HasPartitions returns a boolean if a field has been set.
func (o *V0042Node) HasPartitions() bool {
	if o != nil && o.Partitions != nil {
		return true
	}

	return false
}

// SetPartitions gets a reference to the given []string and assigns it to the Partitions field.
func (o *V0042Node) SetPartitions(v []string) {
	o.Partitions = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *V0042Node) GetPort() int32 {
	if o == nil || o.Port == nil {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetPortOk() (*int32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *V0042Node) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *V0042Node) SetPort(v int32) {
	o.Port = &v
}

// GetRealMemory returns the RealMemory field value if set, zero value otherwise.
func (o *V0042Node) GetRealMemory() int64 {
	if o == nil || o.RealMemory == nil {
		var ret int64
		return ret
	}
	return *o.RealMemory
}

// GetRealMemoryOk returns a tuple with the RealMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetRealMemoryOk() (*int64, bool) {
	if o == nil || o.RealMemory == nil {
		return nil, false
	}
	return o.RealMemory, true
}

// HasRealMemory returns a boolean if a field has been set.
func (o *V0042Node) HasRealMemory() bool {
	if o != nil && o.RealMemory != nil {
		return true
	}

	return false
}

// SetRealMemory gets a reference to the given int64 and assigns it to the RealMemory field.
func (o *V0042Node) SetRealMemory(v int64) {
	o.RealMemory = &v
}

// GetResCoresPerGpu returns the ResCoresPerGpu field value if set, zero value otherwise.
func (o *V0042Node) GetResCoresPerGpu() int32 {
	if o == nil || o.ResCoresPerGpu == nil {
		var ret int32
		return ret
	}
	return *o.ResCoresPerGpu
}

// GetResCoresPerGpuOk returns a tuple with the ResCoresPerGpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetResCoresPerGpuOk() (*int32, bool) {
	if o == nil || o.ResCoresPerGpu == nil {
		return nil, false
	}
	return o.ResCoresPerGpu, true
}

// HasResCoresPerGpu returns a boolean if a field has been set.
func (o *V0042Node) HasResCoresPerGpu() bool {
	if o != nil && o.ResCoresPerGpu != nil {
		return true
	}

	return false
}

// SetResCoresPerGpu gets a reference to the given int32 and assigns it to the ResCoresPerGpu field.
func (o *V0042Node) SetResCoresPerGpu(v int32) {
	o.ResCoresPerGpu = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *V0042Node) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *V0042Node) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *V0042Node) SetComment(v string) {
	o.Comment = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *V0042Node) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *V0042Node) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *V0042Node) SetReason(v string) {
	o.Reason = &v
}

// GetReasonChangedAt returns the ReasonChangedAt field value if set, zero value otherwise.
func (o *V0042Node) GetReasonChangedAt() V0042Uint64NoValStruct {
	if o == nil || o.ReasonChangedAt == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.ReasonChangedAt
}

// GetReasonChangedAtOk returns a tuple with the ReasonChangedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetReasonChangedAtOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.ReasonChangedAt == nil {
		return nil, false
	}
	return o.ReasonChangedAt, true
}

// HasReasonChangedAt returns a boolean if a field has been set.
func (o *V0042Node) HasReasonChangedAt() bool {
	if o != nil && o.ReasonChangedAt != nil {
		return true
	}

	return false
}

// SetReasonChangedAt gets a reference to the given V0042Uint64NoValStruct and assigns it to the ReasonChangedAt field.
func (o *V0042Node) SetReasonChangedAt(v V0042Uint64NoValStruct) {
	o.ReasonChangedAt = &v
}

// GetReasonSetByUser returns the ReasonSetByUser field value if set, zero value otherwise.
func (o *V0042Node) GetReasonSetByUser() string {
	if o == nil || o.ReasonSetByUser == nil {
		var ret string
		return ret
	}
	return *o.ReasonSetByUser
}

// GetReasonSetByUserOk returns a tuple with the ReasonSetByUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetReasonSetByUserOk() (*string, bool) {
	if o == nil || o.ReasonSetByUser == nil {
		return nil, false
	}
	return o.ReasonSetByUser, true
}

// HasReasonSetByUser returns a boolean if a field has been set.
func (o *V0042Node) HasReasonSetByUser() bool {
	if o != nil && o.ReasonSetByUser != nil {
		return true
	}

	return false
}

// SetReasonSetByUser gets a reference to the given string and assigns it to the ReasonSetByUser field.
func (o *V0042Node) SetReasonSetByUser(v string) {
	o.ReasonSetByUser = &v
}

// GetResumeAfter returns the ResumeAfter field value if set, zero value otherwise.
func (o *V0042Node) GetResumeAfter() V0042Uint64NoValStruct {
	if o == nil || o.ResumeAfter == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.ResumeAfter
}

// GetResumeAfterOk returns a tuple with the ResumeAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetResumeAfterOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.ResumeAfter == nil {
		return nil, false
	}
	return o.ResumeAfter, true
}

// HasResumeAfter returns a boolean if a field has been set.
func (o *V0042Node) HasResumeAfter() bool {
	if o != nil && o.ResumeAfter != nil {
		return true
	}

	return false
}

// SetResumeAfter gets a reference to the given V0042Uint64NoValStruct and assigns it to the ResumeAfter field.
func (o *V0042Node) SetResumeAfter(v V0042Uint64NoValStruct) {
	o.ResumeAfter = &v
}

// GetReservation returns the Reservation field value if set, zero value otherwise.
func (o *V0042Node) GetReservation() string {
	if o == nil || o.Reservation == nil {
		var ret string
		return ret
	}
	return *o.Reservation
}

// GetReservationOk returns a tuple with the Reservation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetReservationOk() (*string, bool) {
	if o == nil || o.Reservation == nil {
		return nil, false
	}
	return o.Reservation, true
}

// HasReservation returns a boolean if a field has been set.
func (o *V0042Node) HasReservation() bool {
	if o != nil && o.Reservation != nil {
		return true
	}

	return false
}

// SetReservation gets a reference to the given string and assigns it to the Reservation field.
func (o *V0042Node) SetReservation(v string) {
	o.Reservation = &v
}

// GetAllocMemory returns the AllocMemory field value if set, zero value otherwise.
func (o *V0042Node) GetAllocMemory() int64 {
	if o == nil || o.AllocMemory == nil {
		var ret int64
		return ret
	}
	return *o.AllocMemory
}

// GetAllocMemoryOk returns a tuple with the AllocMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetAllocMemoryOk() (*int64, bool) {
	if o == nil || o.AllocMemory == nil {
		return nil, false
	}
	return o.AllocMemory, true
}

// HasAllocMemory returns a boolean if a field has been set.
func (o *V0042Node) HasAllocMemory() bool {
	if o != nil && o.AllocMemory != nil {
		return true
	}

	return false
}

// SetAllocMemory gets a reference to the given int64 and assigns it to the AllocMemory field.
func (o *V0042Node) SetAllocMemory(v int64) {
	o.AllocMemory = &v
}

// GetAllocCpus returns the AllocCpus field value if set, zero value otherwise.
func (o *V0042Node) GetAllocCpus() int32 {
	if o == nil || o.AllocCpus == nil {
		var ret int32
		return ret
	}
	return *o.AllocCpus
}

// GetAllocCpusOk returns a tuple with the AllocCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetAllocCpusOk() (*int32, bool) {
	if o == nil || o.AllocCpus == nil {
		return nil, false
	}
	return o.AllocCpus, true
}

// HasAllocCpus returns a boolean if a field has been set.
func (o *V0042Node) HasAllocCpus() bool {
	if o != nil && o.AllocCpus != nil {
		return true
	}

	return false
}

// SetAllocCpus gets a reference to the given int32 and assigns it to the AllocCpus field.
func (o *V0042Node) SetAllocCpus(v int32) {
	o.AllocCpus = &v
}

// GetAllocIdleCpus returns the AllocIdleCpus field value if set, zero value otherwise.
func (o *V0042Node) GetAllocIdleCpus() int32 {
	if o == nil || o.AllocIdleCpus == nil {
		var ret int32
		return ret
	}
	return *o.AllocIdleCpus
}

// GetAllocIdleCpusOk returns a tuple with the AllocIdleCpus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetAllocIdleCpusOk() (*int32, bool) {
	if o == nil || o.AllocIdleCpus == nil {
		return nil, false
	}
	return o.AllocIdleCpus, true
}

// HasAllocIdleCpus returns a boolean if a field has been set.
func (o *V0042Node) HasAllocIdleCpus() bool {
	if o != nil && o.AllocIdleCpus != nil {
		return true
	}

	return false
}

// SetAllocIdleCpus gets a reference to the given int32 and assigns it to the AllocIdleCpus field.
func (o *V0042Node) SetAllocIdleCpus(v int32) {
	o.AllocIdleCpus = &v
}

// GetTresUsed returns the TresUsed field value if set, zero value otherwise.
func (o *V0042Node) GetTresUsed() string {
	if o == nil || o.TresUsed == nil {
		var ret string
		return ret
	}
	return *o.TresUsed
}

// GetTresUsedOk returns a tuple with the TresUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetTresUsedOk() (*string, bool) {
	if o == nil || o.TresUsed == nil {
		return nil, false
	}
	return o.TresUsed, true
}

// HasTresUsed returns a boolean if a field has been set.
func (o *V0042Node) HasTresUsed() bool {
	if o != nil && o.TresUsed != nil {
		return true
	}

	return false
}

// SetTresUsed gets a reference to the given string and assigns it to the TresUsed field.
func (o *V0042Node) SetTresUsed(v string) {
	o.TresUsed = &v
}

// GetTresWeighted returns the TresWeighted field value if set, zero value otherwise.
// Deprecated
func (o *V0042Node) GetTresWeighted() float64 {
	if o == nil || o.TresWeighted == nil {
		var ret float64
		return ret
	}
	return *o.TresWeighted
}

// GetTresWeightedOk returns a tuple with the TresWeighted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *V0042Node) GetTresWeightedOk() (*float64, bool) {
	if o == nil || o.TresWeighted == nil {
		return nil, false
	}
	return o.TresWeighted, true
}

// HasTresWeighted returns a boolean if a field has been set.
func (o *V0042Node) HasTresWeighted() bool {
	if o != nil && o.TresWeighted != nil {
		return true
	}

	return false
}

// SetTresWeighted gets a reference to the given float64 and assigns it to the TresWeighted field.
// Deprecated
func (o *V0042Node) SetTresWeighted(v float64) {
	o.TresWeighted = &v
}

// GetSlurmdStartTime returns the SlurmdStartTime field value if set, zero value otherwise.
func (o *V0042Node) GetSlurmdStartTime() V0042Uint64NoValStruct {
	if o == nil || o.SlurmdStartTime == nil {
		var ret V0042Uint64NoValStruct
		return ret
	}
	return *o.SlurmdStartTime
}

// GetSlurmdStartTimeOk returns a tuple with the SlurmdStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetSlurmdStartTimeOk() (*V0042Uint64NoValStruct, bool) {
	if o == nil || o.SlurmdStartTime == nil {
		return nil, false
	}
	return o.SlurmdStartTime, true
}

// HasSlurmdStartTime returns a boolean if a field has been set.
func (o *V0042Node) HasSlurmdStartTime() bool {
	if o != nil && o.SlurmdStartTime != nil {
		return true
	}

	return false
}

// SetSlurmdStartTime gets a reference to the given V0042Uint64NoValStruct and assigns it to the SlurmdStartTime field.
func (o *V0042Node) SetSlurmdStartTime(v V0042Uint64NoValStruct) {
	o.SlurmdStartTime = &v
}

// GetSockets returns the Sockets field value if set, zero value otherwise.
func (o *V0042Node) GetSockets() int32 {
	if o == nil || o.Sockets == nil {
		var ret int32
		return ret
	}
	return *o.Sockets
}

// GetSocketsOk returns a tuple with the Sockets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetSocketsOk() (*int32, bool) {
	if o == nil || o.Sockets == nil {
		return nil, false
	}
	return o.Sockets, true
}

// HasSockets returns a boolean if a field has been set.
func (o *V0042Node) HasSockets() bool {
	if o != nil && o.Sockets != nil {
		return true
	}

	return false
}

// SetSockets gets a reference to the given int32 and assigns it to the Sockets field.
func (o *V0042Node) SetSockets(v int32) {
	o.Sockets = &v
}

// GetThreads returns the Threads field value if set, zero value otherwise.
func (o *V0042Node) GetThreads() int32 {
	if o == nil || o.Threads == nil {
		var ret int32
		return ret
	}
	return *o.Threads
}

// GetThreadsOk returns a tuple with the Threads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetThreadsOk() (*int32, bool) {
	if o == nil || o.Threads == nil {
		return nil, false
	}
	return o.Threads, true
}

// HasThreads returns a boolean if a field has been set.
func (o *V0042Node) HasThreads() bool {
	if o != nil && o.Threads != nil {
		return true
	}

	return false
}

// SetThreads gets a reference to the given int32 and assigns it to the Threads field.
func (o *V0042Node) SetThreads(v int32) {
	o.Threads = &v
}

// GetTemporaryDisk returns the TemporaryDisk field value if set, zero value otherwise.
func (o *V0042Node) GetTemporaryDisk() int32 {
	if o == nil || o.TemporaryDisk == nil {
		var ret int32
		return ret
	}
	return *o.TemporaryDisk
}

// GetTemporaryDiskOk returns a tuple with the TemporaryDisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetTemporaryDiskOk() (*int32, bool) {
	if o == nil || o.TemporaryDisk == nil {
		return nil, false
	}
	return o.TemporaryDisk, true
}

// HasTemporaryDisk returns a boolean if a field has been set.
func (o *V0042Node) HasTemporaryDisk() bool {
	if o != nil && o.TemporaryDisk != nil {
		return true
	}

	return false
}

// SetTemporaryDisk gets a reference to the given int32 and assigns it to the TemporaryDisk field.
func (o *V0042Node) SetTemporaryDisk(v int32) {
	o.TemporaryDisk = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *V0042Node) GetWeight() int32 {
	if o == nil || o.Weight == nil {
		var ret int32
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetWeightOk() (*int32, bool) {
	if o == nil || o.Weight == nil {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *V0042Node) HasWeight() bool {
	if o != nil && o.Weight != nil {
		return true
	}

	return false
}

// SetWeight gets a reference to the given int32 and assigns it to the Weight field.
func (o *V0042Node) SetWeight(v int32) {
	o.Weight = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0042Node) GetTres() string {
	if o == nil || o.Tres == nil {
		var ret string
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetTresOk() (*string, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0042Node) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given string and assigns it to the Tres field.
func (o *V0042Node) SetTres(v string) {
	o.Tres = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *V0042Node) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042Node) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *V0042Node) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *V0042Node) SetVersion(v string) {
	o.Version = &v
}

func (o V0042Node) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Architecture != nil {
		toSerialize["architecture"] = o.Architecture
	}
	if o.BurstbufferNetworkAddress != nil {
		toSerialize["burstbuffer_network_address"] = o.BurstbufferNetworkAddress
	}
	if o.Boards != nil {
		toSerialize["boards"] = o.Boards
	}
	if o.BootTime != nil {
		toSerialize["boot_time"] = o.BootTime
	}
	if o.ClusterName != nil {
		toSerialize["cluster_name"] = o.ClusterName
	}
	if o.Cores != nil {
		toSerialize["cores"] = o.Cores
	}
	if o.SpecializedCores != nil {
		toSerialize["specialized_cores"] = o.SpecializedCores
	}
	if o.CpuBinding != nil {
		toSerialize["cpu_binding"] = o.CpuBinding
	}
	if o.CpuLoad != nil {
		toSerialize["cpu_load"] = o.CpuLoad
	}
	if o.FreeMem != nil {
		toSerialize["free_mem"] = o.FreeMem
	}
	if o.Cpus != nil {
		toSerialize["cpus"] = o.Cpus
	}
	if o.EffectiveCpus != nil {
		toSerialize["effective_cpus"] = o.EffectiveCpus
	}
	if o.SpecializedCpus != nil {
		toSerialize["specialized_cpus"] = o.SpecializedCpus
	}
	if o.Energy != nil {
		toSerialize["energy"] = o.Energy
	}
	if o.ExternalSensors != nil {
		toSerialize["external_sensors"] = o.ExternalSensors
	}
	if o.Extra != nil {
		toSerialize["extra"] = o.Extra
	}
	if o.Power != nil {
		toSerialize["power"] = o.Power
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	if o.ActiveFeatures != nil {
		toSerialize["active_features"] = o.ActiveFeatures
	}
	if o.GpuSpec != nil {
		toSerialize["gpu_spec"] = o.GpuSpec
	}
	if o.Gres != nil {
		toSerialize["gres"] = o.Gres
	}
	if o.GresDrained != nil {
		toSerialize["gres_drained"] = o.GresDrained
	}
	if o.GresUsed != nil {
		toSerialize["gres_used"] = o.GresUsed
	}
	if o.InstanceId != nil {
		toSerialize["instance_id"] = o.InstanceId
	}
	if o.InstanceType != nil {
		toSerialize["instance_type"] = o.InstanceType
	}
	if o.LastBusy != nil {
		toSerialize["last_busy"] = o.LastBusy
	}
	if o.McsLabel != nil {
		toSerialize["mcs_label"] = o.McsLabel
	}
	if o.SpecializedMemory != nil {
		toSerialize["specialized_memory"] = o.SpecializedMemory
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.NextStateAfterReboot != nil {
		toSerialize["next_state_after_reboot"] = o.NextStateAfterReboot
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Hostname != nil {
		toSerialize["hostname"] = o.Hostname
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.OperatingSystem != nil {
		toSerialize["operating_system"] = o.OperatingSystem
	}
	if o.Owner != nil {
		toSerialize["owner"] = o.Owner
	}
	if o.Partitions != nil {
		toSerialize["partitions"] = o.Partitions
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	if o.RealMemory != nil {
		toSerialize["real_memory"] = o.RealMemory
	}
	if o.ResCoresPerGpu != nil {
		toSerialize["res_cores_per_gpu"] = o.ResCoresPerGpu
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.ReasonChangedAt != nil {
		toSerialize["reason_changed_at"] = o.ReasonChangedAt
	}
	if o.ReasonSetByUser != nil {
		toSerialize["reason_set_by_user"] = o.ReasonSetByUser
	}
	if o.ResumeAfter != nil {
		toSerialize["resume_after"] = o.ResumeAfter
	}
	if o.Reservation != nil {
		toSerialize["reservation"] = o.Reservation
	}
	if o.AllocMemory != nil {
		toSerialize["alloc_memory"] = o.AllocMemory
	}
	if o.AllocCpus != nil {
		toSerialize["alloc_cpus"] = o.AllocCpus
	}
	if o.AllocIdleCpus != nil {
		toSerialize["alloc_idle_cpus"] = o.AllocIdleCpus
	}
	if o.TresUsed != nil {
		toSerialize["tres_used"] = o.TresUsed
	}
	if o.TresWeighted != nil {
		toSerialize["tres_weighted"] = o.TresWeighted
	}
	if o.SlurmdStartTime != nil {
		toSerialize["slurmd_start_time"] = o.SlurmdStartTime
	}
	if o.Sockets != nil {
		toSerialize["sockets"] = o.Sockets
	}
	if o.Threads != nil {
		toSerialize["threads"] = o.Threads
	}
	if o.TemporaryDisk != nil {
		toSerialize["temporary_disk"] = o.TemporaryDisk
	}
	if o.Weight != nil {
		toSerialize["weight"] = o.Weight
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableV0042Node struct {
	value *V0042Node
	isSet bool
}

func (v NullableV0042Node) Get() *V0042Node {
	return v.value
}

func (v *NullableV0042Node) Set(val *V0042Node) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042Node) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042Node) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042Node(val *V0042Node) *NullableV0042Node {
	return &NullableV0042Node{value: val, isSet: true}
}

func (v NullableV0042Node) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042Node) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


