/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiJobInfoRespMaxNodes Maximum number of nodes usable by the job
type V0041OpenapiJobInfoRespMaxNodes struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewV0041OpenapiJobInfoRespMaxNodes instantiates a new V0041OpenapiJobInfoRespMaxNodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiJobInfoRespMaxNodes() *V0041OpenapiJobInfoRespMaxNodes {
	this := V0041OpenapiJobInfoRespMaxNodes{}
	return &this
}

// NewV0041OpenapiJobInfoRespMaxNodesWithDefaults instantiates a new V0041OpenapiJobInfoRespMaxNodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiJobInfoRespMaxNodesWithDefaults() *V0041OpenapiJobInfoRespMaxNodes {
	this := V0041OpenapiJobInfoRespMaxNodes{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetSet() bool {
	if o == nil || o.Set == nil {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetSetOk() (*bool, bool) {
	if o == nil || o.Set == nil {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) HasSet() bool {
	if o != nil && o.Set != nil {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *V0041OpenapiJobInfoRespMaxNodes) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetInfinite() bool {
	if o == nil || o.Infinite == nil {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetInfiniteOk() (*bool, bool) {
	if o == nil || o.Infinite == nil {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) HasInfinite() bool {
	if o != nil && o.Infinite != nil {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *V0041OpenapiJobInfoRespMaxNodes) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetNumber() int32 {
	if o == nil || o.Number == nil {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) GetNumberOk() (*int32, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *V0041OpenapiJobInfoRespMaxNodes) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *V0041OpenapiJobInfoRespMaxNodes) SetNumber(v int32) {
	o.Number = &v
}

func (o V0041OpenapiJobInfoRespMaxNodes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Set != nil {
		toSerialize["set"] = o.Set
	}
	if o.Infinite != nil {
		toSerialize["infinite"] = o.Infinite
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiJobInfoRespMaxNodes struct {
	value *V0041OpenapiJobInfoRespMaxNodes
	isSet bool
}

func (v NullableV0041OpenapiJobInfoRespMaxNodes) Get() *V0041OpenapiJobInfoRespMaxNodes {
	return v.value
}

func (v *NullableV0041OpenapiJobInfoRespMaxNodes) Set(val *V0041OpenapiJobInfoRespMaxNodes) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiJobInfoRespMaxNodes) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiJobInfoRespMaxNodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiJobInfoRespMaxNodes(val *V0041OpenapiJobInfoRespMaxNodes) *NullableV0041OpenapiJobInfoRespMaxNodes {
	return &NullableV0041OpenapiJobInfoRespMaxNodes{value: val, isSet: true}
}

func (v NullableV0041OpenapiJobInfoRespMaxNodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiJobInfoRespMaxNodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


