/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043OpenapiJobInfoResp struct for V0043OpenapiJobInfoResp
type V0043OpenapiJobInfoResp struct {
	Jobs []V0043JobInfo `json:"jobs"`
	LastBackfill V0043Uint64NoValStruct `json:"last_backfill"`
	LastUpdate V0043Uint64NoValStruct `json:"last_update"`
	Meta *V0043OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0043OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0043OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0043OpenapiJobInfoResp instantiates a new V0043OpenapiJobInfoResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043OpenapiJobInfoResp(jobs []V0043JobInfo, lastBackfill V0043Uint64NoValStruct, lastUpdate V0043Uint64NoValStruct) *V0043OpenapiJobInfoResp {
	this := V0043OpenapiJobInfoResp{}
	this.Jobs = jobs
	this.LastBackfill = lastBackfill
	this.LastUpdate = lastUpdate
	return &this
}

// NewV0043OpenapiJobInfoRespWithDefaults instantiates a new V0043OpenapiJobInfoResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043OpenapiJobInfoRespWithDefaults() *V0043OpenapiJobInfoResp {
	this := V0043OpenapiJobInfoResp{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *V0043OpenapiJobInfoResp) GetJobs() []V0043JobInfo {
	if o == nil {
		var ret []V0043JobInfo
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetJobsOk() (*[]V0043JobInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Jobs, true
}

// SetJobs sets field value
func (o *V0043OpenapiJobInfoResp) SetJobs(v []V0043JobInfo) {
	o.Jobs = v
}

// GetLastBackfill returns the LastBackfill field value
func (o *V0043OpenapiJobInfoResp) GetLastBackfill() V0043Uint64NoValStruct {
	if o == nil {
		var ret V0043Uint64NoValStruct
		return ret
	}

	return o.LastBackfill
}

// GetLastBackfillOk returns a tuple with the LastBackfill field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetLastBackfillOk() (*V0043Uint64NoValStruct, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastBackfill, true
}

// SetLastBackfill sets field value
func (o *V0043OpenapiJobInfoResp) SetLastBackfill(v V0043Uint64NoValStruct) {
	o.LastBackfill = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *V0043OpenapiJobInfoResp) GetLastUpdate() V0043Uint64NoValStruct {
	if o == nil {
		var ret V0043Uint64NoValStruct
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetLastUpdateOk() (*V0043Uint64NoValStruct, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *V0043OpenapiJobInfoResp) SetLastUpdate(v V0043Uint64NoValStruct) {
	o.LastUpdate = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0043OpenapiJobInfoResp) GetMeta() V0043OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0043OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetMetaOk() (*V0043OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0043OpenapiJobInfoResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0043OpenapiMeta and assigns it to the Meta field.
func (o *V0043OpenapiJobInfoResp) SetMeta(v V0043OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0043OpenapiJobInfoResp) GetErrors() []V0043OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0043OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetErrorsOk() (*[]V0043OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0043OpenapiJobInfoResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0043OpenapiError and assigns it to the Errors field.
func (o *V0043OpenapiJobInfoResp) SetErrors(v []V0043OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0043OpenapiJobInfoResp) GetWarnings() []V0043OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0043OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiJobInfoResp) GetWarningsOk() (*[]V0043OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0043OpenapiJobInfoResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0043OpenapiWarning and assigns it to the Warnings field.
func (o *V0043OpenapiJobInfoResp) SetWarnings(v []V0043OpenapiWarning) {
	o.Warnings = &v
}

func (o V0043OpenapiJobInfoResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["jobs"] = o.Jobs
	}
	if true {
		toSerialize["last_backfill"] = o.LastBackfill
	}
	if true {
		toSerialize["last_update"] = o.LastUpdate
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0043OpenapiJobInfoResp struct {
	value *V0043OpenapiJobInfoResp
	isSet bool
}

func (v NullableV0043OpenapiJobInfoResp) Get() *V0043OpenapiJobInfoResp {
	return v.value
}

func (v *NullableV0043OpenapiJobInfoResp) Set(val *V0043OpenapiJobInfoResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043OpenapiJobInfoResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043OpenapiJobInfoResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043OpenapiJobInfoResp(val *V0043OpenapiJobInfoResp) *NullableV0043OpenapiJobInfoResp {
	return &NullableV0043OpenapiJobInfoResp{value: val, isSet: true}
}

func (v NullableV0043OpenapiJobInfoResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043OpenapiJobInfoResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


