/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043OpenapiReservationResp struct for V0043OpenapiReservationResp
type V0043OpenapiReservationResp struct {
	Reservations []V0043ReservationInfo `json:"reservations"`
	LastUpdate V0043Uint64NoValStruct `json:"last_update"`
	Meta *V0043OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0043OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0043OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0043OpenapiReservationResp instantiates a new V0043OpenapiReservationResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043OpenapiReservationResp(reservations []V0043ReservationInfo, lastUpdate V0043Uint64NoValStruct) *V0043OpenapiReservationResp {
	this := V0043OpenapiReservationResp{}
	this.Reservations = reservations
	this.LastUpdate = lastUpdate
	return &this
}

// NewV0043OpenapiReservationRespWithDefaults instantiates a new V0043OpenapiReservationResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043OpenapiReservationRespWithDefaults() *V0043OpenapiReservationResp {
	this := V0043OpenapiReservationResp{}
	return &this
}

// GetReservations returns the Reservations field value
func (o *V0043OpenapiReservationResp) GetReservations() []V0043ReservationInfo {
	if o == nil {
		var ret []V0043ReservationInfo
		return ret
	}

	return o.Reservations
}

// GetReservationsOk returns a tuple with the Reservations field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiReservationResp) GetReservationsOk() (*[]V0043ReservationInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Reservations, true
}

// SetReservations sets field value
func (o *V0043OpenapiReservationResp) SetReservations(v []V0043ReservationInfo) {
	o.Reservations = v
}

// GetLastUpdate returns the LastUpdate field value
func (o *V0043OpenapiReservationResp) GetLastUpdate() V0043Uint64NoValStruct {
	if o == nil {
		var ret V0043Uint64NoValStruct
		return ret
	}

	return o.LastUpdate
}

// GetLastUpdateOk returns a tuple with the LastUpdate field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiReservationResp) GetLastUpdateOk() (*V0043Uint64NoValStruct, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastUpdate, true
}

// SetLastUpdate sets field value
func (o *V0043OpenapiReservationResp) SetLastUpdate(v V0043Uint64NoValStruct) {
	o.LastUpdate = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0043OpenapiReservationResp) GetMeta() V0043OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0043OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiReservationResp) GetMetaOk() (*V0043OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0043OpenapiReservationResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0043OpenapiMeta and assigns it to the Meta field.
func (o *V0043OpenapiReservationResp) SetMeta(v V0043OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0043OpenapiReservationResp) GetErrors() []V0043OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0043OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiReservationResp) GetErrorsOk() (*[]V0043OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0043OpenapiReservationResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0043OpenapiError and assigns it to the Errors field.
func (o *V0043OpenapiReservationResp) SetErrors(v []V0043OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0043OpenapiReservationResp) GetWarnings() []V0043OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0043OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiReservationResp) GetWarningsOk() (*[]V0043OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0043OpenapiReservationResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0043OpenapiWarning and assigns it to the Warnings field.
func (o *V0043OpenapiReservationResp) SetWarnings(v []V0043OpenapiWarning) {
	o.Warnings = &v
}

func (o V0043OpenapiReservationResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["reservations"] = o.Reservations
	}
	if true {
		toSerialize["last_update"] = o.LastUpdate
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0043OpenapiReservationResp struct {
	value *V0043OpenapiReservationResp
	isSet bool
}

func (v NullableV0043OpenapiReservationResp) Get() *V0043OpenapiReservationResp {
	return v.value
}

func (v *NullableV0043OpenapiReservationResp) Set(val *V0043OpenapiReservationResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043OpenapiReservationResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043OpenapiReservationResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043OpenapiReservationResp(val *V0043OpenapiReservationResp) *NullableV0043OpenapiReservationResp {
	return &NullableV0043OpenapiReservationResp{value: val, isSet: true}
}

func (v NullableV0043OpenapiReservationResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043OpenapiReservationResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


