/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdJobsRespStatisticsEnergy struct for V0041OpenapiSlurmdbdJobsRespStatisticsEnergy
type V0041OpenapiSlurmdbdJobsRespStatisticsEnergy struct {
	Consumed *V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed `json:"consumed,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespStatisticsEnergy instantiates a new V0041OpenapiSlurmdbdJobsRespStatisticsEnergy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespStatisticsEnergy() *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy {
	this := V0041OpenapiSlurmdbdJobsRespStatisticsEnergy{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespStatisticsEnergyWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespStatisticsEnergy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespStatisticsEnergyWithDefaults() *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy {
	this := V0041OpenapiSlurmdbdJobsRespStatisticsEnergy{}
	return &this
}

// GetConsumed returns the Consumed field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) GetConsumed() V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed {
	if o == nil || o.Consumed == nil {
		var ret V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed
		return ret
	}
	return *o.Consumed
}

// GetConsumedOk returns a tuple with the Consumed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) GetConsumedOk() (*V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed, bool) {
	if o == nil || o.Consumed == nil {
		return nil, false
	}
	return o.Consumed, true
}

// HasConsumed returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) HasConsumed() bool {
	if o != nil && o.Consumed != nil {
		return true
	}

	return false
}

// SetConsumed gets a reference to the given V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed and assigns it to the Consumed field.
func (o *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) SetConsumed(v V0041OpenapiSlurmdbdJobsRespStatisticsEnergyConsumed) {
	o.Consumed = &v
}

func (o V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Consumed != nil {
		toSerialize["consumed"] = o.Consumed
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy struct {
	value *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) Get() *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) Set(val *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy(val *V0041OpenapiSlurmdbdJobsRespStatisticsEnergy) *NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy {
	return &NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespStatisticsEnergy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


