/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer struct for V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer
type V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer struct {
	Account *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount `json:"account,omitempty"`
	User *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser `json:"user,omitempty"`
}

// NewV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer instantiates a new V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer() *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer {
	this := V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer{}
	return &this
}

// NewV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerWithDefaults instantiates a new V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerWithDefaults() *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer {
	this := V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) GetAccount() V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount {
	if o == nil || o.Account == nil {
		var ret V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) GetAccountOk() (*V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount and assigns it to the Account field.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) SetAccount(v V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerAccount) {
	o.Account = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) GetUser() V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser {
	if o == nil || o.User == nil {
		var ret V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) GetUserOk() (*V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser and assigns it to the User field.
func (o *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) SetUser(v V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPerUser) {
	o.User = &v
}

func (o V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer struct {
	value *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) Get() *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) Set(val *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer(val *V0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) *NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer {
	return &NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdConfigRespLimitsMaxJobsActiveJobsPer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


