/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042QosLimitsMaxJobsActiveJobs struct for V0042QosLimitsMaxJobsActiveJobs
type V0042QosLimitsMaxJobsActiveJobs struct {
	Per *V0042QosLimitsMaxJobsActiveJobsPer `json:"per,omitempty"`
}

// NewV0042QosLimitsMaxJobsActiveJobs instantiates a new V0042QosLimitsMaxJobsActiveJobs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042QosLimitsMaxJobsActiveJobs() *V0042QosLimitsMaxJobsActiveJobs {
	this := V0042QosLimitsMaxJobsActiveJobs{}
	return &this
}

// NewV0042QosLimitsMaxJobsActiveJobsWithDefaults instantiates a new V0042QosLimitsMaxJobsActiveJobs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042QosLimitsMaxJobsActiveJobsWithDefaults() *V0042QosLimitsMaxJobsActiveJobs {
	this := V0042QosLimitsMaxJobsActiveJobs{}
	return &this
}

// GetPer returns the Per field value if set, zero value otherwise.
func (o *V0042QosLimitsMaxJobsActiveJobs) GetPer() V0042QosLimitsMaxJobsActiveJobsPer {
	if o == nil || o.Per == nil {
		var ret V0042QosLimitsMaxJobsActiveJobsPer
		return ret
	}
	return *o.Per
}

// GetPerOk returns a tuple with the Per field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042QosLimitsMaxJobsActiveJobs) GetPerOk() (*V0042QosLimitsMaxJobsActiveJobsPer, bool) {
	if o == nil || o.Per == nil {
		return nil, false
	}
	return o.Per, true
}

// HasPer returns a boolean if a field has been set.
func (o *V0042QosLimitsMaxJobsActiveJobs) HasPer() bool {
	if o != nil && o.Per != nil {
		return true
	}

	return false
}

// SetPer gets a reference to the given V0042QosLimitsMaxJobsActiveJobsPer and assigns it to the Per field.
func (o *V0042QosLimitsMaxJobsActiveJobs) SetPer(v V0042QosLimitsMaxJobsActiveJobsPer) {
	o.Per = &v
}

func (o V0042QosLimitsMaxJobsActiveJobs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Per != nil {
		toSerialize["per"] = o.Per
	}
	return json.Marshal(toSerialize)
}

type NullableV0042QosLimitsMaxJobsActiveJobs struct {
	value *V0042QosLimitsMaxJobsActiveJobs
	isSet bool
}

func (v NullableV0042QosLimitsMaxJobsActiveJobs) Get() *V0042QosLimitsMaxJobsActiveJobs {
	return v.value
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobs) Set(val *V0042QosLimitsMaxJobsActiveJobs) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042QosLimitsMaxJobsActiveJobs) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042QosLimitsMaxJobsActiveJobs(val *V0042QosLimitsMaxJobsActiveJobs) *NullableV0042QosLimitsMaxJobsActiveJobs {
	return &NullableV0042QosLimitsMaxJobsActiveJobs{value: val, isSet: true}
}

func (v NullableV0042QosLimitsMaxJobsActiveJobs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042QosLimitsMaxJobsActiveJobs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


