/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042PartitionInfoNodes struct for V0042PartitionInfoNodes
type V0042PartitionInfoNodes struct {
	// AllocNodes
	AllowedAllocation *string `json:"allowed_allocation,omitempty"`
	// Nodes
	Configured *string `json:"configured,omitempty"`
	// TotalNodes
	Total *int32 `json:"total,omitempty"`
}

// NewV0042PartitionInfoNodes instantiates a new V0042PartitionInfoNodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042PartitionInfoNodes() *V0042PartitionInfoNodes {
	this := V0042PartitionInfoNodes{}
	return &this
}

// NewV0042PartitionInfoNodesWithDefaults instantiates a new V0042PartitionInfoNodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042PartitionInfoNodesWithDefaults() *V0042PartitionInfoNodes {
	this := V0042PartitionInfoNodes{}
	return &this
}

// GetAllowedAllocation returns the AllowedAllocation field value if set, zero value otherwise.
func (o *V0042PartitionInfoNodes) GetAllowedAllocation() string {
	if o == nil || o.AllowedAllocation == nil {
		var ret string
		return ret
	}
	return *o.AllowedAllocation
}

// GetAllowedAllocationOk returns a tuple with the AllowedAllocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042PartitionInfoNodes) GetAllowedAllocationOk() (*string, bool) {
	if o == nil || o.AllowedAllocation == nil {
		return nil, false
	}
	return o.AllowedAllocation, true
}

// HasAllowedAllocation returns a boolean if a field has been set.
func (o *V0042PartitionInfoNodes) HasAllowedAllocation() bool {
	if o != nil && o.AllowedAllocation != nil {
		return true
	}

	return false
}

// SetAllowedAllocation gets a reference to the given string and assigns it to the AllowedAllocation field.
func (o *V0042PartitionInfoNodes) SetAllowedAllocation(v string) {
	o.AllowedAllocation = &v
}

// GetConfigured returns the Configured field value if set, zero value otherwise.
func (o *V0042PartitionInfoNodes) GetConfigured() string {
	if o == nil || o.Configured == nil {
		var ret string
		return ret
	}
	return *o.Configured
}

// GetConfiguredOk returns a tuple with the Configured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042PartitionInfoNodes) GetConfiguredOk() (*string, bool) {
	if o == nil || o.Configured == nil {
		return nil, false
	}
	return o.Configured, true
}

// HasConfigured returns a boolean if a field has been set.
func (o *V0042PartitionInfoNodes) HasConfigured() bool {
	if o != nil && o.Configured != nil {
		return true
	}

	return false
}

// SetConfigured gets a reference to the given string and assigns it to the Configured field.
func (o *V0042PartitionInfoNodes) SetConfigured(v string) {
	o.Configured = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *V0042PartitionInfoNodes) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042PartitionInfoNodes) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *V0042PartitionInfoNodes) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *V0042PartitionInfoNodes) SetTotal(v int32) {
	o.Total = &v
}

func (o V0042PartitionInfoNodes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedAllocation != nil {
		toSerialize["allowed_allocation"] = o.AllowedAllocation
	}
	if o.Configured != nil {
		toSerialize["configured"] = o.Configured
	}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableV0042PartitionInfoNodes struct {
	value *V0042PartitionInfoNodes
	isSet bool
}

func (v NullableV0042PartitionInfoNodes) Get() *V0042PartitionInfoNodes {
	return v.value
}

func (v *NullableV0042PartitionInfoNodes) Set(val *V0042PartitionInfoNodes) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042PartitionInfoNodes) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042PartitionInfoNodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042PartitionInfoNodes(val *V0042PartitionInfoNodes) *NullableV0042PartitionInfoNodes {
	return &NullableV0042PartitionInfoNodes{value: val, isSet: true}
}

func (v NullableV0042PartitionInfoNodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042PartitionInfoNodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


