/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0040OpenapiAssocsResp struct for V0040OpenapiAssocsResp
type V0040OpenapiAssocsResp struct {
	Associations []V0040Assoc `json:"associations"`
	Meta *V0040OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0040OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0040OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0040OpenapiAssocsResp instantiates a new V0040OpenapiAssocsResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0040OpenapiAssocsResp(associations []V0040Assoc) *V0040OpenapiAssocsResp {
	this := V0040OpenapiAssocsResp{}
	this.Associations = associations
	return &this
}

// NewV0040OpenapiAssocsRespWithDefaults instantiates a new V0040OpenapiAssocsResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0040OpenapiAssocsRespWithDefaults() *V0040OpenapiAssocsResp {
	this := V0040OpenapiAssocsResp{}
	return &this
}

// GetAssociations returns the Associations field value
func (o *V0040OpenapiAssocsResp) GetAssociations() []V0040Assoc {
	if o == nil {
		var ret []V0040Assoc
		return ret
	}

	return o.Associations
}

// GetAssociationsOk returns a tuple with the Associations field value
// and a boolean to check if the value has been set.
func (o *V0040OpenapiAssocsResp) GetAssociationsOk() (*[]V0040Assoc, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Associations, true
}

// SetAssociations sets field value
func (o *V0040OpenapiAssocsResp) SetAssociations(v []V0040Assoc) {
	o.Associations = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0040OpenapiAssocsResp) GetMeta() V0040OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0040OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0040OpenapiAssocsResp) GetMetaOk() (*V0040OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0040OpenapiAssocsResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0040OpenapiMeta and assigns it to the Meta field.
func (o *V0040OpenapiAssocsResp) SetMeta(v V0040OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0040OpenapiAssocsResp) GetErrors() []V0040OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0040OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0040OpenapiAssocsResp) GetErrorsOk() (*[]V0040OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0040OpenapiAssocsResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0040OpenapiError and assigns it to the Errors field.
func (o *V0040OpenapiAssocsResp) SetErrors(v []V0040OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0040OpenapiAssocsResp) GetWarnings() []V0040OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0040OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0040OpenapiAssocsResp) GetWarningsOk() (*[]V0040OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0040OpenapiAssocsResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0040OpenapiWarning and assigns it to the Warnings field.
func (o *V0040OpenapiAssocsResp) SetWarnings(v []V0040OpenapiWarning) {
	o.Warnings = &v
}

func (o V0040OpenapiAssocsResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["associations"] = o.Associations
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0040OpenapiAssocsResp struct {
	value *V0040OpenapiAssocsResp
	isSet bool
}

func (v NullableV0040OpenapiAssocsResp) Get() *V0040OpenapiAssocsResp {
	return v.value
}

func (v *NullableV0040OpenapiAssocsResp) Set(val *V0040OpenapiAssocsResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0040OpenapiAssocsResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0040OpenapiAssocsResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0040OpenapiAssocsResp(val *V0040OpenapiAssocsResp) *NullableV0040OpenapiAssocsResp {
	return &NullableV0040OpenapiAssocsResp{value: val, isSet: true}
}

func (v NullableV0040OpenapiAssocsResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0040OpenapiAssocsResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


