/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043KillJobsRespJobError struct for V0043KillJobsRespJobError
type V0043KillJobsRespJobError struct {
	// String error encountered signaling job
	String *string `json:"string,omitempty"`
	// Numeric error encountered signaling job
	Code *int32 `json:"code,omitempty"`
	// Error message why signaling job failed
	Message *string `json:"message,omitempty"`
}

// NewV0043KillJobsRespJobError instantiates a new V0043KillJobsRespJobError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043KillJobsRespJobError() *V0043KillJobsRespJobError {
	this := V0043KillJobsRespJobError{}
	return &this
}

// NewV0043KillJobsRespJobErrorWithDefaults instantiates a new V0043KillJobsRespJobError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043KillJobsRespJobErrorWithDefaults() *V0043KillJobsRespJobError {
	this := V0043KillJobsRespJobError{}
	return &this
}

// GetString returns the String field value if set, zero value otherwise.
func (o *V0043KillJobsRespJobError) GetString() string {
	if o == nil || o.String == nil {
		var ret string
		return ret
	}
	return *o.String
}

// GetStringOk returns a tuple with the String field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043KillJobsRespJobError) GetStringOk() (*string, bool) {
	if o == nil || o.String == nil {
		return nil, false
	}
	return o.String, true
}

// HasString returns a boolean if a field has been set.
func (o *V0043KillJobsRespJobError) HasString() bool {
	if o != nil && o.String != nil {
		return true
	}

	return false
}

// SetString gets a reference to the given string and assigns it to the String field.
func (o *V0043KillJobsRespJobError) SetString(v string) {
	o.String = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *V0043KillJobsRespJobError) GetCode() int32 {
	if o == nil || o.Code == nil {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043KillJobsRespJobError) GetCodeOk() (*int32, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *V0043KillJobsRespJobError) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *V0043KillJobsRespJobError) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V0043KillJobsRespJobError) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043KillJobsRespJobError) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V0043KillJobsRespJobError) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V0043KillJobsRespJobError) SetMessage(v string) {
	o.Message = &v
}

func (o V0043KillJobsRespJobError) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.String != nil {
		toSerialize["string"] = o.String
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableV0043KillJobsRespJobError struct {
	value *V0043KillJobsRespJobError
	isSet bool
}

func (v NullableV0043KillJobsRespJobError) Get() *V0043KillJobsRespJobError {
	return v.value
}

func (v *NullableV0043KillJobsRespJobError) Set(val *V0043KillJobsRespJobError) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043KillJobsRespJobError) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043KillJobsRespJobError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043KillJobsRespJobError(val *V0043KillJobsRespJobError) *NullableV0043KillJobsRespJobError {
	return &NullableV0043KillJobsRespJobError{value: val, isSet: true}
}

func (v NullableV0043KillJobsRespJobError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043KillJobsRespJobError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


