/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0041OpenapiSlurmdbdJobsRespSteps struct for V0041OpenapiSlurmdbdJobsRespSteps
type V0041OpenapiSlurmdbdJobsRespSteps struct {
	Time *V0041OpenapiSlurmdbdJobsRespTime1 `json:"time,omitempty"`
	ExitCode *V0041OpenapiSlurmdbdJobsRespExitCode `json:"exit_code,omitempty"`
	Nodes *V0041OpenapiSlurmdbdJobsRespNodes `json:"nodes,omitempty"`
	Tasks *V0041OpenapiSlurmdbdJobsRespTasks `json:"tasks,omitempty"`
	// Process ID
	Pid *string `json:"pid,omitempty"`
	CPU *V0041OpenapiSlurmdbdJobsRespCPU `json:"CPU,omitempty"`
	// User ID that requested termination of the step
	KillRequestUser *string `json:"kill_request_user,omitempty"`
	// Current state
	State *[]string `json:"state,omitempty"`
	Statistics *V0041OpenapiSlurmdbdJobsRespStatistics `json:"statistics,omitempty"`
	Step *V0041OpenapiSlurmdbdJobsRespStep `json:"step,omitempty"`
	Task *V0041OpenapiSlurmdbdJobsRespTask `json:"task,omitempty"`
	Tres *V0041OpenapiSlurmdbdJobsRespTres `json:"tres,omitempty"`
}

// NewV0041OpenapiSlurmdbdJobsRespSteps instantiates a new V0041OpenapiSlurmdbdJobsRespSteps object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0041OpenapiSlurmdbdJobsRespSteps() *V0041OpenapiSlurmdbdJobsRespSteps {
	this := V0041OpenapiSlurmdbdJobsRespSteps{}
	return &this
}

// NewV0041OpenapiSlurmdbdJobsRespStepsWithDefaults instantiates a new V0041OpenapiSlurmdbdJobsRespSteps object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0041OpenapiSlurmdbdJobsRespStepsWithDefaults() *V0041OpenapiSlurmdbdJobsRespSteps {
	this := V0041OpenapiSlurmdbdJobsRespSteps{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTime() V0041OpenapiSlurmdbdJobsRespTime1 {
	if o == nil || o.Time == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTime1
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTimeOk() (*V0041OpenapiSlurmdbdJobsRespTime1, bool) {
	if o == nil || o.Time == nil {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasTime() bool {
	if o != nil && o.Time != nil {
		return true
	}

	return false
}

// SetTime gets a reference to the given V0041OpenapiSlurmdbdJobsRespTime1 and assigns it to the Time field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetTime(v V0041OpenapiSlurmdbdJobsRespTime1) {
	o.Time = &v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetExitCode() V0041OpenapiSlurmdbdJobsRespExitCode {
	if o == nil || o.ExitCode == nil {
		var ret V0041OpenapiSlurmdbdJobsRespExitCode
		return ret
	}
	return *o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetExitCodeOk() (*V0041OpenapiSlurmdbdJobsRespExitCode, bool) {
	if o == nil || o.ExitCode == nil {
		return nil, false
	}
	return o.ExitCode, true
}

// HasExitCode returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasExitCode() bool {
	if o != nil && o.ExitCode != nil {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given V0041OpenapiSlurmdbdJobsRespExitCode and assigns it to the ExitCode field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetExitCode(v V0041OpenapiSlurmdbdJobsRespExitCode) {
	o.ExitCode = &v
}

// GetNodes returns the Nodes field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetNodes() V0041OpenapiSlurmdbdJobsRespNodes {
	if o == nil || o.Nodes == nil {
		var ret V0041OpenapiSlurmdbdJobsRespNodes
		return ret
	}
	return *o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetNodesOk() (*V0041OpenapiSlurmdbdJobsRespNodes, bool) {
	if o == nil || o.Nodes == nil {
		return nil, false
	}
	return o.Nodes, true
}

// HasNodes returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasNodes() bool {
	if o != nil && o.Nodes != nil {
		return true
	}

	return false
}

// SetNodes gets a reference to the given V0041OpenapiSlurmdbdJobsRespNodes and assigns it to the Nodes field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetNodes(v V0041OpenapiSlurmdbdJobsRespNodes) {
	o.Nodes = &v
}

// GetTasks returns the Tasks field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTasks() V0041OpenapiSlurmdbdJobsRespTasks {
	if o == nil || o.Tasks == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTasks
		return ret
	}
	return *o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTasksOk() (*V0041OpenapiSlurmdbdJobsRespTasks, bool) {
	if o == nil || o.Tasks == nil {
		return nil, false
	}
	return o.Tasks, true
}

// HasTasks returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasTasks() bool {
	if o != nil && o.Tasks != nil {
		return true
	}

	return false
}

// SetTasks gets a reference to the given V0041OpenapiSlurmdbdJobsRespTasks and assigns it to the Tasks field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetTasks(v V0041OpenapiSlurmdbdJobsRespTasks) {
	o.Tasks = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetPid() string {
	if o == nil || o.Pid == nil {
		var ret string
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetPidOk() (*string, bool) {
	if o == nil || o.Pid == nil {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasPid() bool {
	if o != nil && o.Pid != nil {
		return true
	}

	return false
}

// SetPid gets a reference to the given string and assigns it to the Pid field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetPid(v string) {
	o.Pid = &v
}

// GetCPU returns the CPU field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetCPU() V0041OpenapiSlurmdbdJobsRespCPU {
	if o == nil || o.CPU == nil {
		var ret V0041OpenapiSlurmdbdJobsRespCPU
		return ret
	}
	return *o.CPU
}

// GetCPUOk returns a tuple with the CPU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetCPUOk() (*V0041OpenapiSlurmdbdJobsRespCPU, bool) {
	if o == nil || o.CPU == nil {
		return nil, false
	}
	return o.CPU, true
}

// HasCPU returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasCPU() bool {
	if o != nil && o.CPU != nil {
		return true
	}

	return false
}

// SetCPU gets a reference to the given V0041OpenapiSlurmdbdJobsRespCPU and assigns it to the CPU field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetCPU(v V0041OpenapiSlurmdbdJobsRespCPU) {
	o.CPU = &v
}

// GetKillRequestUser returns the KillRequestUser field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetKillRequestUser() string {
	if o == nil || o.KillRequestUser == nil {
		var ret string
		return ret
	}
	return *o.KillRequestUser
}

// GetKillRequestUserOk returns a tuple with the KillRequestUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetKillRequestUserOk() (*string, bool) {
	if o == nil || o.KillRequestUser == nil {
		return nil, false
	}
	return o.KillRequestUser, true
}

// HasKillRequestUser returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasKillRequestUser() bool {
	if o != nil && o.KillRequestUser != nil {
		return true
	}

	return false
}

// SetKillRequestUser gets a reference to the given string and assigns it to the KillRequestUser field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetKillRequestUser(v string) {
	o.KillRequestUser = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetState() []string {
	if o == nil || o.State == nil {
		var ret []string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetStateOk() (*[]string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetState(v []string) {
	o.State = &v
}

// GetStatistics returns the Statistics field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetStatistics() V0041OpenapiSlurmdbdJobsRespStatistics {
	if o == nil || o.Statistics == nil {
		var ret V0041OpenapiSlurmdbdJobsRespStatistics
		return ret
	}
	return *o.Statistics
}

// GetStatisticsOk returns a tuple with the Statistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetStatisticsOk() (*V0041OpenapiSlurmdbdJobsRespStatistics, bool) {
	if o == nil || o.Statistics == nil {
		return nil, false
	}
	return o.Statistics, true
}

// HasStatistics returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasStatistics() bool {
	if o != nil && o.Statistics != nil {
		return true
	}

	return false
}

// SetStatistics gets a reference to the given V0041OpenapiSlurmdbdJobsRespStatistics and assigns it to the Statistics field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetStatistics(v V0041OpenapiSlurmdbdJobsRespStatistics) {
	o.Statistics = &v
}

// GetStep returns the Step field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetStep() V0041OpenapiSlurmdbdJobsRespStep {
	if o == nil || o.Step == nil {
		var ret V0041OpenapiSlurmdbdJobsRespStep
		return ret
	}
	return *o.Step
}

// GetStepOk returns a tuple with the Step field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetStepOk() (*V0041OpenapiSlurmdbdJobsRespStep, bool) {
	if o == nil || o.Step == nil {
		return nil, false
	}
	return o.Step, true
}

// HasStep returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasStep() bool {
	if o != nil && o.Step != nil {
		return true
	}

	return false
}

// SetStep gets a reference to the given V0041OpenapiSlurmdbdJobsRespStep and assigns it to the Step field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetStep(v V0041OpenapiSlurmdbdJobsRespStep) {
	o.Step = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTask() V0041OpenapiSlurmdbdJobsRespTask {
	if o == nil || o.Task == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTask
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTaskOk() (*V0041OpenapiSlurmdbdJobsRespTask, bool) {
	if o == nil || o.Task == nil {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasTask() bool {
	if o != nil && o.Task != nil {
		return true
	}

	return false
}

// SetTask gets a reference to the given V0041OpenapiSlurmdbdJobsRespTask and assigns it to the Task field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetTask(v V0041OpenapiSlurmdbdJobsRespTask) {
	o.Task = &v
}

// GetTres returns the Tres field value if set, zero value otherwise.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTres() V0041OpenapiSlurmdbdJobsRespTres {
	if o == nil || o.Tres == nil {
		var ret V0041OpenapiSlurmdbdJobsRespTres
		return ret
	}
	return *o.Tres
}

// GetTresOk returns a tuple with the Tres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) GetTresOk() (*V0041OpenapiSlurmdbdJobsRespTres, bool) {
	if o == nil || o.Tres == nil {
		return nil, false
	}
	return o.Tres, true
}

// HasTres returns a boolean if a field has been set.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) HasTres() bool {
	if o != nil && o.Tres != nil {
		return true
	}

	return false
}

// SetTres gets a reference to the given V0041OpenapiSlurmdbdJobsRespTres and assigns it to the Tres field.
func (o *V0041OpenapiSlurmdbdJobsRespSteps) SetTres(v V0041OpenapiSlurmdbdJobsRespTres) {
	o.Tres = &v
}

func (o V0041OpenapiSlurmdbdJobsRespSteps) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Time != nil {
		toSerialize["time"] = o.Time
	}
	if o.ExitCode != nil {
		toSerialize["exit_code"] = o.ExitCode
	}
	if o.Nodes != nil {
		toSerialize["nodes"] = o.Nodes
	}
	if o.Tasks != nil {
		toSerialize["tasks"] = o.Tasks
	}
	if o.Pid != nil {
		toSerialize["pid"] = o.Pid
	}
	if o.CPU != nil {
		toSerialize["CPU"] = o.CPU
	}
	if o.KillRequestUser != nil {
		toSerialize["kill_request_user"] = o.KillRequestUser
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Statistics != nil {
		toSerialize["statistics"] = o.Statistics
	}
	if o.Step != nil {
		toSerialize["step"] = o.Step
	}
	if o.Task != nil {
		toSerialize["task"] = o.Task
	}
	if o.Tres != nil {
		toSerialize["tres"] = o.Tres
	}
	return json.Marshal(toSerialize)
}

type NullableV0041OpenapiSlurmdbdJobsRespSteps struct {
	value *V0041OpenapiSlurmdbdJobsRespSteps
	isSet bool
}

func (v NullableV0041OpenapiSlurmdbdJobsRespSteps) Get() *V0041OpenapiSlurmdbdJobsRespSteps {
	return v.value
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespSteps) Set(val *V0041OpenapiSlurmdbdJobsRespSteps) {
	v.value = val
	v.isSet = true
}

func (v NullableV0041OpenapiSlurmdbdJobsRespSteps) IsSet() bool {
	return v.isSet
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespSteps) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0041OpenapiSlurmdbdJobsRespSteps(val *V0041OpenapiSlurmdbdJobsRespSteps) *NullableV0041OpenapiSlurmdbdJobsRespSteps {
	return &NullableV0041OpenapiSlurmdbdJobsRespSteps{value: val, isSet: true}
}

func (v NullableV0041OpenapiSlurmdbdJobsRespSteps) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0041OpenapiSlurmdbdJobsRespSteps) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


