/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority Association priority factor
type SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority instantiates a new SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority() *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority {
	this := SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority{}
	return &this
}

// NewSlurmdbV0041UsersAssociationAssociationConditionAssociationPriorityWithDefaults instantiates a new SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmdbV0041UsersAssociationAssociationConditionAssociationPriorityWithDefaults() *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority {
	this := SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetSet() bool {
	if o == nil || o.Set == nil {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetSetOk() (*bool, bool) {
	if o == nil || o.Set == nil {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) HasSet() bool {
	if o != nil && o.Set != nil {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetInfinite() bool {
	if o == nil || o.Infinite == nil {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetInfiniteOk() (*bool, bool) {
	if o == nil || o.Infinite == nil {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) HasInfinite() bool {
	if o != nil && o.Infinite != nil {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetNumber() int32 {
	if o == nil || o.Number == nil {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) GetNumberOk() (*int32, bool) {
	if o == nil || o.Number == nil {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) HasNumber() bool {
	if o != nil && o.Number != nil {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) SetNumber(v int32) {
	o.Number = &v
}

func (o SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Set != nil {
		toSerialize["set"] = o.Set
	}
	if o.Infinite != nil {
		toSerialize["infinite"] = o.Infinite
	}
	if o.Number != nil {
		toSerialize["number"] = o.Number
	}
	return json.Marshal(toSerialize)
}

type NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority struct {
	value *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority
	isSet bool
}

func (v NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) Get() *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority {
	return v.value
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) Set(val *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority(val *SlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) *NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority {
	return &NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority{value: val, isSet: true}
}

func (v NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmdbV0041UsersAssociationAssociationConditionAssociationPriority) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


