/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0042CronEntryLine struct for V0042CronEntryLine
type V0042CronEntryLine struct {
	// Start of this entry in file
	Start *int32 `json:"start,omitempty"`
	// End of this entry in file
	End *int32 `json:"end,omitempty"`
}

// NewV0042CronEntryLine instantiates a new V0042CronEntryLine object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0042CronEntryLine() *V0042CronEntryLine {
	this := V0042CronEntryLine{}
	return &this
}

// NewV0042CronEntryLineWithDefaults instantiates a new V0042CronEntryLine object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0042CronEntryLineWithDefaults() *V0042CronEntryLine {
	this := V0042CronEntryLine{}
	return &this
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *V0042CronEntryLine) GetStart() int32 {
	if o == nil || o.Start == nil {
		var ret int32
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042CronEntryLine) GetStartOk() (*int32, bool) {
	if o == nil || o.Start == nil {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *V0042CronEntryLine) HasStart() bool {
	if o != nil && o.Start != nil {
		return true
	}

	return false
}

// SetStart gets a reference to the given int32 and assigns it to the Start field.
func (o *V0042CronEntryLine) SetStart(v int32) {
	o.Start = &v
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *V0042CronEntryLine) GetEnd() int32 {
	if o == nil || o.End == nil {
		var ret int32
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0042CronEntryLine) GetEndOk() (*int32, bool) {
	if o == nil || o.End == nil {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *V0042CronEntryLine) HasEnd() bool {
	if o != nil && o.End != nil {
		return true
	}

	return false
}

// SetEnd gets a reference to the given int32 and assigns it to the End field.
func (o *V0042CronEntryLine) SetEnd(v int32) {
	o.End = &v
}

func (o V0042CronEntryLine) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Start != nil {
		toSerialize["start"] = o.Start
	}
	if o.End != nil {
		toSerialize["end"] = o.End
	}
	return json.Marshal(toSerialize)
}

type NullableV0042CronEntryLine struct {
	value *V0042CronEntryLine
	isSet bool
}

func (v NullableV0042CronEntryLine) Get() *V0042CronEntryLine {
	return v.value
}

func (v *NullableV0042CronEntryLine) Set(val *V0042CronEntryLine) {
	v.value = val
	v.isSet = true
}

func (v NullableV0042CronEntryLine) IsSet() bool {
	return v.isSet
}

func (v *NullableV0042CronEntryLine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0042CronEntryLine(val *V0042CronEntryLine) *NullableV0042CronEntryLine {
	return &NullableV0042CronEntryLine{value: val, isSet: true}
}

func (v NullableV0042CronEntryLine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0042CronEntryLine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


