/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043OpenapiKillJobResp struct for V0043OpenapiKillJobResp
type V0043OpenapiKillJobResp struct {
	// List of jobs signal responses
	Status []V0043KillJobsRespJob `json:"status"`
	Meta *V0043OpenapiMeta `json:"meta,omitempty"`
	Errors *[]V0043OpenapiError `json:"errors,omitempty"`
	Warnings *[]V0043OpenapiWarning `json:"warnings,omitempty"`
}

// NewV0043OpenapiKillJobResp instantiates a new V0043OpenapiKillJobResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043OpenapiKillJobResp(status []V0043KillJobsRespJob) *V0043OpenapiKillJobResp {
	this := V0043OpenapiKillJobResp{}
	this.Status = status
	return &this
}

// NewV0043OpenapiKillJobRespWithDefaults instantiates a new V0043OpenapiKillJobResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043OpenapiKillJobRespWithDefaults() *V0043OpenapiKillJobResp {
	this := V0043OpenapiKillJobResp{}
	return &this
}

// GetStatus returns the Status field value
func (o *V0043OpenapiKillJobResp) GetStatus() []V0043KillJobsRespJob {
	if o == nil {
		var ret []V0043KillJobsRespJob
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V0043OpenapiKillJobResp) GetStatusOk() (*[]V0043KillJobsRespJob, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V0043OpenapiKillJobResp) SetStatus(v []V0043KillJobsRespJob) {
	o.Status = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *V0043OpenapiKillJobResp) GetMeta() V0043OpenapiMeta {
	if o == nil || o.Meta == nil {
		var ret V0043OpenapiMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiKillJobResp) GetMetaOk() (*V0043OpenapiMeta, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *V0043OpenapiKillJobResp) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given V0043OpenapiMeta and assigns it to the Meta field.
func (o *V0043OpenapiKillJobResp) SetMeta(v V0043OpenapiMeta) {
	o.Meta = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *V0043OpenapiKillJobResp) GetErrors() []V0043OpenapiError {
	if o == nil || o.Errors == nil {
		var ret []V0043OpenapiError
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiKillJobResp) GetErrorsOk() (*[]V0043OpenapiError, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *V0043OpenapiKillJobResp) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []V0043OpenapiError and assigns it to the Errors field.
func (o *V0043OpenapiKillJobResp) SetErrors(v []V0043OpenapiError) {
	o.Errors = &v
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *V0043OpenapiKillJobResp) GetWarnings() []V0043OpenapiWarning {
	if o == nil || o.Warnings == nil {
		var ret []V0043OpenapiWarning
		return ret
	}
	return *o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiKillJobResp) GetWarningsOk() (*[]V0043OpenapiWarning, bool) {
	if o == nil || o.Warnings == nil {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *V0043OpenapiKillJobResp) HasWarnings() bool {
	if o != nil && o.Warnings != nil {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []V0043OpenapiWarning and assigns it to the Warnings field.
func (o *V0043OpenapiKillJobResp) SetWarnings(v []V0043OpenapiWarning) {
	o.Warnings = &v
}

func (o V0043OpenapiKillJobResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	return json.Marshal(toSerialize)
}

type NullableV0043OpenapiKillJobResp struct {
	value *V0043OpenapiKillJobResp
	isSet bool
}

func (v NullableV0043OpenapiKillJobResp) Get() *V0043OpenapiKillJobResp {
	return v.value
}

func (v *NullableV0043OpenapiKillJobResp) Set(val *V0043OpenapiKillJobResp) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043OpenapiKillJobResp) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043OpenapiKillJobResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043OpenapiKillJobResp(val *V0043OpenapiKillJobResp) *NullableV0043OpenapiKillJobResp {
	return &NullableV0043OpenapiKillJobResp{value: val, isSet: true}
}

func (v NullableV0043OpenapiKillJobResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043OpenapiKillJobResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


