/*
Slurm REST API

API to access and control Slurm

API version: Slurm-25.05.3
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmapi

import (
	"encoding/json"
)

// V0043OpenapiMetaSlurm struct for V0043OpenapiMetaSlurm
type V0043OpenapiMetaSlurm struct {
	Version *V0043OpenapiMetaSlurmVersion `json:"version,omitempty"`
	// Slurm release string
	Release *string `json:"release,omitempty"`
	// Slurm cluster name
	Cluster *string `json:"cluster,omitempty"`
}

// NewV0043OpenapiMetaSlurm instantiates a new V0043OpenapiMetaSlurm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0043OpenapiMetaSlurm() *V0043OpenapiMetaSlurm {
	this := V0043OpenapiMetaSlurm{}
	return &this
}

// NewV0043OpenapiMetaSlurmWithDefaults instantiates a new V0043OpenapiMetaSlurm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0043OpenapiMetaSlurmWithDefaults() *V0043OpenapiMetaSlurm {
	this := V0043OpenapiMetaSlurm{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *V0043OpenapiMetaSlurm) GetVersion() V0043OpenapiMetaSlurmVersion {
	if o == nil || o.Version == nil {
		var ret V0043OpenapiMetaSlurmVersion
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiMetaSlurm) GetVersionOk() (*V0043OpenapiMetaSlurmVersion, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *V0043OpenapiMetaSlurm) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given V0043OpenapiMetaSlurmVersion and assigns it to the Version field.
func (o *V0043OpenapiMetaSlurm) SetVersion(v V0043OpenapiMetaSlurmVersion) {
	o.Version = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *V0043OpenapiMetaSlurm) GetRelease() string {
	if o == nil || o.Release == nil {
		var ret string
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiMetaSlurm) GetReleaseOk() (*string, bool) {
	if o == nil || o.Release == nil {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *V0043OpenapiMetaSlurm) HasRelease() bool {
	if o != nil && o.Release != nil {
		return true
	}

	return false
}

// SetRelease gets a reference to the given string and assigns it to the Release field.
func (o *V0043OpenapiMetaSlurm) SetRelease(v string) {
	o.Release = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *V0043OpenapiMetaSlurm) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0043OpenapiMetaSlurm) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *V0043OpenapiMetaSlurm) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *V0043OpenapiMetaSlurm) SetCluster(v string) {
	o.Cluster = &v
}

func (o V0043OpenapiMetaSlurm) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Release != nil {
		toSerialize["release"] = o.Release
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	return json.Marshal(toSerialize)
}

type NullableV0043OpenapiMetaSlurm struct {
	value *V0043OpenapiMetaSlurm
	isSet bool
}

func (v NullableV0043OpenapiMetaSlurm) Get() *V0043OpenapiMetaSlurm {
	return v.value
}

func (v *NullableV0043OpenapiMetaSlurm) Set(val *V0043OpenapiMetaSlurm) {
	v.value = val
	v.isSet = true
}

func (v NullableV0043OpenapiMetaSlurm) IsSet() bool {
	return v.isSet
}

func (v *NullableV0043OpenapiMetaSlurm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0043OpenapiMetaSlurm(val *V0043OpenapiMetaSlurm) *NullableV0043OpenapiMetaSlurm {
	return &NullableV0043OpenapiMetaSlurm{value: val, isSet: true}
}

func (v NullableV0043OpenapiMetaSlurm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0043OpenapiMetaSlurm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


