name: Check & Release

## REGULAR USAGE
# Any PR to the main branch will trigger a build, during which
# we run tests and ensure the code is ready for release

## RELEASE USAGE
# Trigger with
# export TAG=0.0.1
# git tag -a $TAG -m "First release"
# git push origin $TAG

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

env:
  GORELEASER_VERSION: "~> v2"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run offline tests
        run: |
          sudo apt install libx11-dev
          make offline-test

      - name: GoReleaser Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "${{ env.GORELEASER_VERSION }}"
          args: build --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-release checks
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make lint
          make update-version-in-go
          make fail-if-any-files-changed

      - name: Release on tag
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: "${{ env.GORELEASER_VERSION }}"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
